// Built-in Danish word packs. Plain common nouns/categories — no licensed
// content. Seeded into the `packs` table by packs.seedBuiltInPacks.

export type SeedPack = { name: string; emoji: string; words: string[] };

export const DANISH_PACKS: SeedPack[] = [
  {
    name: "Dyr",
    emoji: "🦊",
    words: [
      "Hund", "Kat", "Hest", "Ko", "Gris", "Får", "Ged", "Høne",
      "And", "Gås", "Kanin", "Mus", "Rotte", "Egern", "Pindsvin", "Ræv",
      "Ulv", "Bjørn", "Elg", "Hjort", "Løve", "Tiger", "Elefant", "Giraf",
      "Zebra", "Næsehorn", "Abe", "Delfin", "Hval", "Haj", "Sæl", "Pingvin",
      "Ørn", "Ugle", "Krage", "Måge", "Slange", "Frø", "Skildpadde", "Krokodille",
      "Edderkop", "Myre", "Kylling", "Svane", "Due", "Høg", "Falk", "Spurv",
      "Tudse", "Blæksprutte", "Krabbe", "Hummer", "Reje", "Bi", "Hveps", "Flue",
      "Myg", "Bille", "Sommerfugl", "Larve", "Snegl", "Regnorm", "Grævling", "Odder",
      "Flagermus", "Gorilla", "Chimpanse", "Orangutang", "Flodhest", "Antilope", "Struds", "Isbjørn",
      "Kænguru", "Koala", "Næbdyr", "Dovendyr", "Muldvarp", "Hamster", "Marsvin", "Hare",
      "Fasan", "Påfugl", "Kalkun", "Papegøje",
    ],
  },
  {
    name: "Madretter",
    emoji: "🍝",
    words: [
      "pizza", "lasagne", "spaghetti", "kødsovs", "frikadeller", "hakkebøf", "medisterpølse", "flæskesteg",
      "andesteg", "gåsesteg", "kalkun", "kylling", "mørbrad", "bøf", "steg", "kotelet",
      "pølse", "hotdog", "burger", "sandwich", "smørrebrød", "leverpostej", "rullepølse", "spegepølse",
      "hamburgerryg", "roastbeef", "skinke", "bacon", "æg", "spejlæg", "røræg", "blødkogt æg",
      "hårdkogt æg", "omelet", "pandekage", "vaffel", "grød", "havregrød", "risengrød", "øllebrød",
      "suppe", "tomatsuppe", "hønsesuppe", "kartoffelsuppe", "gullasch", "chili con carne", "gryderet", "wokret",
      "sushi", "sashimi", "forårsrulle", "samosa", "taco", "burrito", "enchilada", "quesadilla",
      "fajita", "kebab", "shawarma", "falafel", "hummus", "tzatziki", "guacamole", "salsa",
      "pesto", "tapenade", "salat", "pastasalat", "kartoffelsalat", "coleslaw", "pommes frites", "bagt kartoffel",
      "flødekartofler", "kartoffelmos", "ris", "pasta", "nudler", "couscous", "bulgur", "quinoa",
      "frikadelle", "rugbrød", "ost", "fisk", "kartoffel", "brød", "sovs", "ketchup",
    ],
  },
  {
    name: "Drikkevarer",
    emoji: "☕",
    words: [
      "vand", "danskvand", "kildevand", "isvand", "mælk", "skummetmælk", "minimælk", "letmælk",
      "sødmælk", "kærnemælk", "kakao", "varm kakao", "kaffe", "espresso", "cappuccino", "latte",
      "macchiato", "americano", "iskaffe", "te", "sort te", "grøn te", "hvid te", "urtete",
      "frugtte", "iste", "juice", "æblejuice", "appelsinjuice", "multifrugtjuice", "tomatjuice", "saft",
      "hyldeblomstsaft", "solbærsaft", "ribssaft", "æblemost", "sodavand", "cola", "sportsvand", "ginger ale",
      "tonic", "limonade", "smoothie", "milkshake", "øl", "pilsner", "classic", "pale ale",
      "ipa", "stout", "porter", "hvedeøl", "cider", "vin", "rødvin", "hvidvin",
      "rosévin", "portvin", "sherry", "champagne", "cava", "prosecco", "spumante", "spiritus",
      "vodka", "rom", "gin", "tequila", "whisky", "cognac", "brandy", "likør",
      "snaps", "akvavit", "bitter", "vermouth", "absint", "gløgg", "punch", "cocktail",
    ],
  },
  {
    name: "Frugt & Grønt",
    emoji: "🍎",
    words: [
      "Æble", "Pære", "Banan", "Appelsin", "Citron", "Lime", "Jordbær", "Hindbær",
      "Blåbær", "Kirsebær", "Drue", "Melon", "Vandmelon", "Ananas", "Mango", "Kiwi",
      "Fersken", "Blomme", "Tomat", "Agurk", "Gulerod", "Kartoffel", "Løg", "Hvidløg",
      "Peberfrugt", "Broccoli", "Blomkål", "Spinat", "Salat", "Majs", "Ærter", "Bønner",
      "Svamp", "Aubergine", "Squash", "Rødbede", "Selleri", "Porre", "Radise", "Græskar",
      "Mandarin", "Klementin", "Vindrue", "Nektarin", "Brombær", "Tyttebær", "Tranebær", "Solbær",
      "Ribs", "Stikkelsbær", "Papaya", "Granatæble", "Figen", "Daddel", "Kokosnød", "Chili",
      "Pastinak", "Persillerod", "Forårsløg", "Purløg", "Jordskok", "Kål", "Hvidkål", "Rødkål",
      "Spidskål", "Savojkål", "Grønkål", "Rosenkål", "Rucola", "Feldsalat", "Asparges", "Linser",
      "Champignon", "Portobello", "Kantarel", "Trøffel", "Ingefær", "Gurkemeje", "Oliven", "Kapers",
      "Avocado", "Artiskok",
    ],
  },
  {
    name: "Sport",
    emoji: "⚽",
    words: [
      "Fodbold", "Håndbold", "Basketball", "Volleyball", "Tennis", "Badminton", "Bordtennis", "Golf",
      "Svømning", "Løb", "Cykling", "Ridning", "Boksning", "Brydning", "Karate", "Judo",
      "Gymnastik", "Atletik", "Stavspring", "Højdespring", "Længdespring", "Skøjteløb", "Ishockey", "Skiløb",
      "Snowboard", "Surfing", "Sejlsport", "Roning", "Kajak", "Klatring", "Dart", "Bowling",
      "Curling", "Fægtning", "Triatlon", "Spydkast", "Diskos", "Vægtløftning", "Dans", "Parkour",
      "Floorball", "Rugby", "Amerikansk fodbold", "Baseball", "Cricket", "Dykning", "Vandpolo", "Kajakroning",
      "Sejlads", "Windsurfing", "Kitesurfing", "Kunstskøjteløb", "Mountainbike", "BMX", "Sprint", "Maraton",
      "Hækkeløb", "Stangspring", "Kuglestød", "Diskoskast", "Hammerkast", "Trampolin", "Taekwondo", "Bueskydning",
      "Skydning", "Dressur", "Springridning", "Motorsport", "Formel 1", "Rally", "Motocross", "Speedway",
      "Go-kart", "Styrkeløft", "Bodybuilding", "Crossfit", "Fitness", "Yoga", "Pilates", "Zumba",
      "Aerobic", "Ballet", "Hiphop", "Pardans", "Billard", "Snooker", "Petanque",
    ],
  },
  {
    name: "Danske byer",
    emoji: "🏙️",
    words: [
      "København", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens",
      "Vejle", "Roskilde", "Herning", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge",
      "Holstebro", "Slagelse", "Helsingør", "Hillerød", "Sønderborg", "Svendborg", "Hjørring", "Holbæk",
      "Frederikshavn", "Nørresundby", "Ringsted", "Haderslev", "Skive", "Nykøbing", "Kalundborg", "Aabenraa",
      "Ribe", "Skagen", "Frederikssund", "Grenaa", "Thisted", "Varde", "Middelfart", "Nyborg",
      "Hørsholm", "Taastrup", "Ishøj", "Birkerød", "Farum", "Smørumnedre", "Skanderborg", "Nykøbing Falster",
      "Lillerød", "Korsør", "Nakskov", "Brønderslev", "Haslev", "Hobro", "Værløse", "Hedehusene",
      "Dragør", "Vordingborg", "Hedensted", "Odder", "Struer", "Fløng", "Lystrup", "Jyllinge",
      "Sorø", "Vejen", "Hundested", "Sæby", "Bjerringbro", "Fredensborg", "Bogense", "Kerteminde",
      "Maribo", "Rønne", "Nexø", "Allinge", "Svaneke", "Gudhjem", "Aakirkeby", "Christiansø",
      "Skjern", "Tønder", "Lemvig",
    ],
  },
  {
    name: "Natur",
    emoji: "🌲",
    words: [
      "Skov", "Træ", "Blomst", "Græs", "Busk", "Mose", "Sø", "Å",
      "Flod", "Hav", "Strand", "Klit", "Bjerg", "Bakke", "Dal", "Eng",
      "Mark", "Klippe", "Sten", "Sand", "Jord", "Regn", "Sne", "Tåge",
      "Sky", "Sol", "Måne", "Stjerne", "Vind", "Storm", "Lyn", "Torden",
      "Regnbue", "Vandfald", "Ø", "Fjord", "Gletsjer", "Vulkan", "Ørken", "Jungle",
      "Planet", "Hagl", "Slud", "Blæst", "Orkan", "Tyfon", "Tornado", "Skypumpe",
      "Dis", "Rim", "Frost", "Is", "Tøvejr", "Solopgang", "Solnedgang", "Daggry",
      "Skumring", "Nat", "Dag", "Slette", "Regnskov", "Oase", "Savanne", "Tundra",
      "Isbræ", "Jordskælv", "Bæk", "Ocean", "Bugt", "Kyst", "Rev", "Halvø",
      "Koralrev", "Drypstenshule", "Grotte", "Grus", "Mudder", "Ler", "Støv", "Aske",
      "Kilde", "Gejser", "Sump", "Hede", "Krat",
    ],
  },
  {
    name: "Køkken",
    emoji: "🍳",
    words: [
      "Gryde", "Pande", "Kniv", "Gaffel", "Ske", "Tallerken", "Skål", "Glas",
      "Kop", "Krus", "Komfur", "Ovn", "Køleskab", "Fryser", "Mikroovn", "Opvaskemaskine",
      "Brødrister", "Elkedel", "Kaffemaskine", "Blender", "Røremaskine", "Si", "Rivejern", "Dåseåbner",
      "Proptrækker", "Skærebræt", "Viskestykke", "Forklæde", "Grydeske", "Piskeris", "Spatel", "Saks",
      "Vægt", "Målebæger", "Bageform", "Rullepind", "Termometer", "Tang", "Tragt", "Dørslag",
      "Urtekniv", "Brødkniv", "Kokkekniv", "Kødøkse", "Fjerkræsaks", "Skræller", "Hvidløgspresser", "Oplukker",
      "Slev", "Hulske", "Paletkniv", "Dejskraber", "Madpincet", "Pølsetang", "Måleske", "Køkkenvægt",
      "Stegetermometer", "Ur", "Minutur", "Morter", "Pistil", "Kaffefilter", "Tepose", "Teske",
      "Spiseske", "Bestik", "Dyb tallerken", "Flad tallerken", "Sidetallerken", "Fad", "Kande", "Vandglas",
      "Vinglas", "Ølglas", "Snapseglas", "Underkop", "Kasserolle", "Stegepande", "Grillpande", "Wok",
      "Bradepande", "Springform", "Tærteform", "Muffinform", "Kagerulle", "Udstikker", "Sprøjtepose", "Tyl",
      "Bagepapir", "Stanniol", "Husholdningsfilm", "Frysepose", "Madkasse", "Termokande", "Isterningebakke", "Bageplade",
      "Stegegryde", "Saftpresser",
    ],
  },
  {
    name: "Transport",
    emoji: "🚗",
    words: [
      "Bil", "Bus", "Tog", "Cykel", "Knallert", "Motorcykel", "Lastbil", "Varevogn",
      "Taxa", "Ambulance", "Brandbil", "Politibil", "Traktor", "Gravko", "Sporvogn", "Metro",
      "Fly", "Helikopter", "Raket", "Ballon", "Skib", "Færge", "Båd", "Sejlbåd",
      "Kano", "Kajak", "Jetski", "Ubåd", "Scooter", "Løbehjul", "Rulleskøjter", "Skateboard",
      "Trillebør", "Slæde", "Elevator", "Rulletrappe", "Svævebane", "Gondol", "Hangglider", "Faldskærm",
      "Flyver", "Skraldebil", "Fejemaskine", "Kranbil", "Mejetærsker", "Gravemaskine", "Gaffeltruck", "Bulldozer",
      "Autocamper", "Campingvogn", "Trailer", "Hestevogn", "Kane", "Snescooter", "Svævefly", "Luftballon",
      "Zeppeliner", "Rumfærge", "Satellit", "Letbane", "Monorail", "Bjergbane", "Rullestol", "Barnevogn",
      "Klapvogn", "Indkøbsvogn", "Robåd", "Motorbåd", "Yacht", "Vandscooter", "Gummibåd", "Tømmerflåde",
      "Hovercraft", "Katamaran", "Trehjulet", "Tandemcykel", "Elcykel", "Ladcykel", "Ethjulet", "Segway",
      "Hoverboard", "Rulleski", "Bæreraket", "Drosje", "Karet", "Dumper", "Rutebil", "S-tog",
    ],
  },
  {
    name: "Erhverv",
    emoji: "👷",
    words: [
      "Læge", "Sygeplejerske", "Tandlæge", "Lærer", "Pædagog", "Politibetjent", "Brandmand", "Soldat",
      "Pilot", "Stewardesse", "Kok", "Tjener", "Bager", "Slagter", "Frisør", "Mekaniker",
      "Tømrer", "Murer", "Elektriker", "Blikkenslager", "Maler", "Landmand", "Fisker", "Gartner",
      "Advokat", "Dommer", "Revisor", "Ingeniør", "Arkitekt", "Programmør", "Journalist", "Fotograf",
      "Musiker", "Skuespiller", "Forfatter", "Dyrlæge", "Astronaut", "Bibliotekar", "Postbud", "Chauffør",
      "Farmaceut", "Psykolog", "Fysioterapeut", "Kiropraktor", "Professor", "Forsker", "Redder", "Kaptajn",
      "Sømand", "Skovhugger", "Snedker", "VVS-installatør", "Smed", "Svejser", "Designer", "It-supporter",
      "Bogholder", "Bankrådgiver", "Ejendomsmægler", "Sælger", "Kassedame", "Bartender", "Receptionist", "Kosmetolog",
      "Massør", "Skrædder", "Skomager", "Urmager", "Guldsmed", "Redaktør", "Oversætter", "Tolk",
      "Sanger", "Instruktør", "Kunstner", "Borgmester", "Minister", "Præst", "Bedemand", "Rengøringsassistent",
      "Skraldemand", "Buschauffør", "Taxachauffør", "Lokomotivfører",
    ],
  },
  {
    name: "Tøj og Sko",
    emoji: "👕",
    words: [
      "Trøje", "Skjorte", "T-shirt", "Bluse", "Sweater", "Cardigan", "Jakke", "Frakke",
      "Bukser", "Jeans", "Shorts", "Nederdel", "Kjole", "Strømper", "Sokker", "Undertøj",
      "Sko", "Støvler", "Sandaler", "Sneakers", "Hjemmesko", "Hue", "Hat", "Kasket",
      "Halstørklæde", "Vanter", "Handsker", "Bælte", "Slips", "Butterfly", "Vest", "Badedragt",
      "Badebukser", "Pyjamas", "Regnjakke", "Dunjakke", "Habit", "Smykke", "Solbriller", "Regntøj",
      "Flyverdragt", "Badetøj", "Bikini", "Badeshorts", "Underbukser", "Trusser", "Bh", "Strømpebukser",
      "Nattøj", "Morgenkåbe", "Tørklæde", "Seler", "Blazer", "Smoking", "Hættetrøje", "Top",
      "Singlet", "Leggins", "Joggingbukser", "Overalls", "Gummistøvler", "Vinterstøvler", "Kondisko", "Løbesko",
      "Fodboldstøvler", "Gummisko", "Klipklappere", "Højhælede", "Stiletter", "Laksko", "Læderstøvler", "Ankelstøvler",
      "Snøresko", "Hyttesko", "Sejlersko", "Slippers", "Overtræksbukser", "Termotøj", "Vindjakke", "Læderjakke",
      "Denimjakke", "Fleecejakke", "Skibukser", "Skijakke", "Pandebånd", "Ørevarmer", "Krave", "Manchetter",
      "Forklæde", "Slør",
    ],
  },
  {
    name: "Kroppen",
    emoji: "🫀",
    words: [
      "Hoved", "Hår", "Pande", "Øjne", "Øre", "Næse", "Mund", "Læber",
      "Tænder", "Tunge", "Hage", "Kind", "Hals", "Nakke", "Skulder", "Arm",
      "Albue", "Håndled", "Hånd", "Finger", "Tommel", "Negl", "Bryst", "Mave",
      "Ryg", "Hofte", "Ben", "Knæ", "Lægge", "Ankel", "Fod", "Tå",
      "Hjerte", "Lunge", "Hjerne", "Mavesæk", "Lever", "Nyre", "Knogle", "Muskel",
      "Øjenbryn", "Øje", "Øjenvippe", "Læbe", "Tand", "Gane", "Kæbe", "Strube",
      "Underarm", "Tommelfinger", "Pegefinger", "Langemand", "Ringfinger", "Lillefinger", "Navle", "Rygsøjle",
      "Lænd", "Balle", "Lår", "Skinneben", "Læg", "Hæl", "Storetå", "Hud",
      "Sene", "Marv", "Led", "Brusk", "Blod", "Åre", "Vene", "Arterie",
      "Milt", "Bugspytkirtel", "Tarm", "Tyndtarm", "Tyktarm", "Blindtarm", "Rygmarv", "Nerve",
      "Kirtel", "Skjoldbruskkirtel", "Blære", "Livmoder", "Æggestok",
    ],
  },
  {
    name: "Musikinstrumenter",
    emoji: "🎸",
    words: [
      "Guitar", "Klaver", "Flygel", "Violin", "Bratsch", "Cello", "Kontrabas", "Harpe",
      "Trommer", "Tromme", "Bækken", "Tamburin", "Xylofon", "Marimba", "Trompet", "Basun",
      "Tuba", "Valdhorn", "Saxofon", "Klarinet", "Obo", "Fagot", "Tværfløjte", "Blokfløjte",
      "Mundharmonika", "Harmonika", "Orgel", "Synthesizer", "Banjo", "Mandolin", "Ukulele", "Bas",
      "Triangel", "Castagnetter", "Sækkepibe", "Lyre", "Cembalo", "Theremin", "Konga", "Bongotromme",
      "Keyboard", "Akustisk guitar", "Elguitar", "Basguitar", "Lut", "Piccolofløjte", "Panfløjte", "Basklarinet",
      "Sopransaxofon", "Altsaxofon", "Tenorsaxofon", "Barytonsaxofon", "Kornet", "Flygelhorn", "Trækbasun", "Sousafon",
      "Trommesæt", "Lilletromme", "Stortromme", "Tamtam", "Hi-hat", "Pauke", "Vibrafon", "Klokkespil",
      "Djembe", "Cajon", "Maracas", "Claves", "Rørklokker", "Gongong", "Syngeskål", "Jødeharpe",
      "Mundharpe", "Melodica", "Kazoo", "Drejelire", "Sitar", "Tabla", "Didgeridoo", "Balalajka",
      "Bouzouki", "Oud", "Koto", "Shamisen", "Sampler", "Trommemaskine", "Sequencer", "Mixerpult",
    ],
  },
  {
    name: "Møbler og Hjemmet",
    emoji: "🛋️",
    words: [
      "stol", "bord", "sofa", "seng", "skab", "reol", "kommode", "hylde",
      "skrivebord", "spisebord", "sofabord", "natbord", "lænestol", "puf", "skammel", "bænk",
      "klædeskab", "vitrineskab", "bogreol", "tv-bord", "tæppe", "gardin", "persienne", "lampe",
      "lysekrone", "gulvlampe", "bordlampe", "væglampe", "spejl", "maleri", "plakat", "ramme",
      "vase", "krukke", "urtepotteskjuler", "pude", "dyne", "sengetøj", "lagen", "madras",
      "topmadras", "rullemadras", "vaskemaskine", "tørretumbler", "opvaskemaskine", "køleskab", "fryser", "komfur",
      "ovn", "mikroovn", "brødrister", "elkedel", "kaffemaskine", "blender", "røremaskine", "støvsuger",
      "strygejern", "strygebræt", "tørrestativ", "moppe", "kost", "fejebakke", "spand", "karklud",
      "viskestykke", "håndklæde", "badekåbe", "badeforhæng", "toiletbørste", "skraldespand", "vasketøjskurv", "knagerække",
      "bøjle", "skohylde", "paraplyholder", "dørmåtte", "postkasse", "ringeklokke", "stikkontakt", "forlængerledning",
    ],
  },
  {
    name: "Værktøj",
    emoji: "🔨",
    words: [
      "hammer", "skruetrækker", "skruenøgle", "svensknøgle", "tang", "knibtang", "bidetang", "papegøjetang",
      "rørtang", "sav", "fukssvans", "stiksav", "rundsav", "kædesav", "båndsav", "boremaskine",
      "skruemaskine", "slagnøgle", "vinkelsliber", "slibemaskine", "høvl", "stemmejern", "fil", "rasp",
      "sandpapir", "målebånd", "tommestok", "vaterpas", "vinkelmåler", "skydelære", "koben", "boltsaks",
      "pladesaks", "kniv", "hobbykniv", "spartel", "murske", "fugepistol", "fugebræt", "pensel",
      "malerulle", "malertape", "skruestik", "skruetvinge", "ambolt", "loddekolbe", "svejseapparat", "kompressor",
      "sømpistol", "hæftepistol", "limpistol", "lommelygte", "arbejdslampe", "sikkerhedsbriller", "høreværn", "åndedrætsværn",
      "arbejdshandsker", "sikkerhedssko", "hjelm", "knæbeskyttere", "stige", "stillads", "trillebør", "skovl",
      "spade", "greb", "rive", "hakke", "økse", "flækøkse", "beskæresaks", "hækkesaks",
      "græsslåmaskine", "buskrydder", "løvblæser", "sneskovl", "isskraber", "kost", "sneslynge", "multimeter",
    ],
  },
  {
    name: "Bygninger",
    emoji: "🏰",
    words: [
      "hus", "rækkehus", "lejlighed", "villa", "palæ", "slot", "borg", "fort",
      "fæstning", "tårn", "fyrtårn", "skyskraber", "højhus", "kontorbygning", "rådhus", "bibliotek",
      "museum", "teater", "biograf", "opera", "koncertsal", "skole", "gymnasium", "universitet",
      "børnehave", "vuggestue", "hospital", "klinik", "apotek", "kirke", "katedral", "moske",
      "synagoge", "tempel", "kloster", "station", "lufthavn", "havn", "fabrik", "lagerhal",
      "værksted", "garage", "carport", "skur", "drivhus", "orangeri", "lade", "stald",
      "silo", "mølle", "vindmølle", "vandmølle", "bageri", "slagteri", "supermarked", "indkøbscenter",
      "butik", "restaurant", "café", "bar", "pub", "hotel", "motel", "kro",
      "vandrerhjem", "fængsel", "politistation", "brandstation", "kaserne", "ambassade", "parlament", "domhus",
      "stadion", "sportshal", "svømmehal", "skøjtehal", "ridehal", "telt", "iglo", "tipi",
    ],
  },
  {
    name: "Teknologi",
    emoji: "💻",
    words: [
      "computer", "bærbar", "tablet", "smartphone", "mobiltelefon", "smartwatch", "fjernsyn", "radio",
      "højttaler", "forstærker", "soundbar", "høretelefoner", "headset", "mikrofon", "kamera", "videokamera",
      "drone", "spillekonsol", "controller", "joystick", "mus", "tastatur", "skærm", "monitor",
      "printer", "scanner", "kopiermaskine", "router", "modem", "switch", "server", "harddisk",
      "usb-stik", "hukommelseskort", "powerbank", "oplader", "kabel", "ledning", "batteri", "pære",
      "lommeregner", "gps", "dashcam", "actionkamera", "projektor", "lærred", "robotstøvsuger", "plæneklipperrobot",
      "smart-tv", "e-bogslæser", "digital fotoramme", "røgalarm", "tyverialarm", "overvågningskamera", "termostat", "vejrstation",
      "elbil", "elcykel", "el-løbehjul", "solcelle", "vindmølle", "pacemaker", "høreapparat", "ultralydsscanner",
      "røntgenmaskine", "mri-scanner", "ct-scanner", "ekg-apparat", "respirator", "kuvøse", "3d-printer", "laser",
      "fiberoptik", "mikrochip", "transistor", "kondensator", "modstand", "diode", "printplade", "loddekolbe",
    ],
  },
  {
    name: "Slik og Desserter",
    emoji: "🍬",
    words: [
      "chokolade", "mørk chokolade", "mælkechokolade", "hvid chokolade", "flødebolle", "lakrids", "saltlakrids", "sød lakrids",
      "vingummi", "karamel", "skumfidus", "bolsje", "slikkepind", "tyggegummi", "marcipan", "nougat",
      "konfekt", "pebermynte", "trøffel", "romkugle", "studenterbrød", "hindbærsnitte", "træstammer", "kage",
      "lagkage", "chokoladekage", "gulerodskage", "drømmekage", "citronmåne", "roulade", "mazarinkage", "brownie",
      "muffin", "cupcake", "cookie", "småkage", "vaniljekrans", "brunkage", "pebernød", "klejne",
      "æbleskive", "pandekage", "vaffel", "is", "flødeis", "sodavandsis", "sorbet", "gelato",
      "softice", "ispind", "isvaffel", "dessert", "budding", "fromage", "mousse", "panna cotta",
      "tiramisu", "cheesecake", "æblekage", "rødgrød", "frugtsalat", "risalamande", "koldskål", "kammerjunker",
      "marengs", "pavlova", "crème brûlée", "makron", "tærte", "frugttærte", "citronfromage", "romfromage",
      "chokolademousse", "karamelrand", "honningkage", "sirupskage", "kransekage", "romsnegl", "tebirkes", "spandauer",
      "slik", "popcorn", "chips",
    ],
  },
  {
    name: "Skole og Kontor",
    emoji: "📏",
    words: [
      "blyant", "kuglepen", "fyldepen", "tusch", "overstregningstusch", "farveblyant", "kridt", "tavle",
      "whiteboard", "svamp", "viskelæder", "blyantspidser", "lineal", "vinkelmåler", "passer", "penalhus",
      "saks", "lim", "limstift", "tape", "hæftemaskine", "hæfteklamme", "hulmaskine", "clips",
      "papir", "notesbog", "blok", "kladdehæfte", "ringbind", "mappe", "plastiklomme", "register",
      "konvolut", "frimærke", "brevåbner", "stempel", "blæk", "kalender", "post-it", "opslagstavle",
      "tegnestift", "magnet", "slettelak", "slettepen", "rettelak", "lommeregner", "computer", "mus",
      "tastatur", "musemåtte", "skærm", "printer", "scanner", "makulator", "skrivebord", "kontorstol",
      "skuffedarium", "reol", "papirkurv", "arkivskab", "brevbakke", "tidsskriftsamler", "opslagsværk", "ordbog",
      "leksikon", "atlas", "lærebog", "roman", "digtsamling", "novelle", "kopipapir", "fotopapir",
      "karton", "bølgepap", "pergamentpapir", "madpakke", "drikkedunk", "rygsæk", "skoletaske", "kridttavle",
    ],
  },
  {
    name: "Hobbyer og Fritid",
    emoji: "🎨",
    words: [
      "fodbold", "håndbold", "svømning", "løb", "cykling", "fitness", "yoga", "gymnastik",
      "ridning", "dans", "ballet", "teater", "skuespil", "sang", "kor", "musik",
      "guitar", "klaver", "trommer", "tegning", "maling", "akvarel", "keramik", "strikning",
      "hækling", "syning", "broderi", "patchwork", "smykkefremstilling", "perler", "scrapbooking", "origami",
      "fotografering", "film", "biograf", "læsning", "bøger", "tegneserier", "forfatterskab", "digte",
      "computerspil", "brætspil", "kortspil", "rollespil", "skak", "puslespil", "modelbygning", "lego",
      "samlekort", "frimærker", "mønter", "antikviteter", "loppemarked", "geocaching", "vandring", "camping",
      "fiskeri", "jagt", "ornitologi", "havearbejde", "drivhus", "blomsterbinding", "madlavning", "bagning",
      "ølbrygning", "vinbrygning", "smagning", "rejser", "sprog", "historie", "slægtsforskning", "astronomi",
      "stjernekiggeri", "dykning", "surfing", "sejlads", "skiløb", "snowboarding", "skateboarding", "rulleskøjter",
    ],
  },
];
