import type { SeedPack } from "./types";

// Core built-in Danish word packs — the 20 broad categories the game shipped
// with, deepened. Plain common nouns; no brand names and no licensed content.
// Seeded into the `packs` table by packs.ensureBuiltInPacks.
//
// These stay deliberately BROAD (one "Dyr" pack, not Kæledyr/Vilde dyr/Havdyr)
// so a host's pinned favourite keeps working. Depth is what stops repeats here:
// a pinned pack is the whole draw pool for that room.

export const PACKS_CORE: SeedPack[] = [
  {
    name: "Dyr",
    emoji: "🦊",
    words: [
      "Hund", "Kat", "Hest", "Ko", "Gris", "Får", "Ged", "Høne",
      "And", "Gås", "Kanin", "Mus", "Rotte", "Egern", "Pindsvin", "Ræv",
      "Ulv", "Bjørn", "Elg", "Hjort", "Løve", "Tiger", "Elefant", "Giraf",
      "Zebra", "Næsehorn", "Abe", "Delfin", "Hval", "Haj", "Sæl", "Pingvin",
      "Ørn", "Ugle", "Krage", "Måge", "Slange", "Frø", "Skildpadde", "Krokodille",
      "Edderkop", "Myre", "Kylling", "Svane", "Due", "Høg", "Falk", "Spurv",
      "Tudse", "Blæksprutte", "Krabbe", "Hummer", "Reje", "Bi", "Hveps", "Flue",
      "Myg", "Bille", "Sommerfugl", "Larve", "Snegl", "Regnorm", "Grævling", "Odder",
      "Flagermus", "Gorilla", "Chimpanse", "Orangutang", "Flodhest", "Antilope", "Struds", "Isbjørn",
      "Kænguru", "Koala", "Næbdyr", "Dovendyr", "Muldvarp", "Hamster", "Marsvin", "Hare",
      "Fasan", "Påfugl", "Kalkun", "Papegøje",
      "Ilder", "Mår", "Væsel", "Bæver", "Los", "Vildsvin", "Rådyr", "Dådyr",
      "Krondyr", "Mink", "Vaskebjørn", "Prærieulv", "Sjakal", "Hyæne", "Gepard", "Leopard",
      "Jaguar", "Puma", "Panter", "Bison", "Bøffel", "Yak", "Lama", "Alpaka",
      "Kamel", "Dromedar", "Æsel", "Muldyr", "Pony", "Føl", "Kalv", "Lam",
      "Kid", "Hvalros", "Søløve", "Narhval", "Spækhugger", "Søpindsvin", "Søstjerne", "Vandmand",
      "Koral", "Musling", "Østers", "Konkylie", "Ål", "Torsk", "Laks", "Ørred",
      "Gedde", "Aborre", "Karpe", "Rokke", "Tun", "Makrel", "Rødspætte", "Skrubbe",
      "Stenbider", "Søhest", "Salamander", "Firben", "Gekko", "Leguan", "Varan", "Boa",
      "Python", "Hugorm", "Snog", "Klapperslange", "Kobra", "Alligator", "Strandskade", "Vibe",
      "Stær", "Solsort", "Drossel", "Nattergal", "Lærke", "Mejse", "Blåmejse", "Finke",
      "Dompap", "Gråspurv", "Svale", "Mursejler", "Hejre", "Stork", "Trane", "Skarv",
      "Lom", "Alk", "Lunde", "Musvåge", "Glente", "Tårnfalk", "Natugle", "Sløruge",
      "Isfugl", "Spætte", "Gøg", "Ravn", "Allike", "Markmus", "Vandrotte", "Lemming",
      "Chinchilla", "Ørkenrotte", "Jordegern", "Murmeldyr", "Bæltedyr", "Myresluger", "Pungrotte", "Wombat",
      "Lemur", "Bavian", "Makak", "Gibbon", "Mandril", "Flodsvin", "Tapir", "Okapi",
      "Gnu", "Impala", "Gazelle", "Moskusokse", "Bjergged", "Stenbuk",
    ],
  },
  {
    name: "Madretter",
    emoji: "🍝",
    words: [
      "pizza", "lasagne", "spaghetti", "kødsovs", "frikadeller", "hakkebøf", "medisterpølse", "flæskesteg",
      "andesteg", "gåsesteg", "kalkun", "kylling", "mørbrad", "bøf", "steg", "kotelet",
      "pølse", "hotdog", "burger", "sandwich", "smørrebrød", "leverpostej", "rullepølse", "spegepølse",
      "hamburgerryg", "roastbeef", "skinke", "bacon", "æg", "spejlæg", "røræg", "blødkogt æg",
      "hårdkogt æg", "omelet", "pandekage", "vaffel", "grød", "havregrød", "risengrød", "øllebrød",
      "suppe", "tomatsuppe", "hønsesuppe", "kartoffelsuppe", "gullasch", "chili con carne", "gryderet", "wokret",
      "sushi", "sashimi", "forårsrulle", "samosa", "taco", "burrito", "enchilada", "quesadilla",
      "fajita", "kebab", "shawarma", "falafel", "hummus", "tzatziki", "guacamole", "salsa",
      "pesto", "tapenade", "salat", "pastasalat", "kartoffelsalat", "coleslaw", "pommes frites", "bagt kartoffel",
      "flødekartofler", "kartoffelmos", "ris", "pasta", "nudler", "couscous", "bulgur", "quinoa",
      "frikadelle", "rugbrød", "ost", "fisk", "kartoffel", "brød", "sovs", "ketchup",
      "boller i karry", "biksemad", "stegt flæsk", "æggekage", "tarteletter", "forloren hare", "millionbøf", "karbonade",
      "benløse fugle", "kalvesteg", "lammekølle", "oksesteg", "ribbensteg", "culotte", "skinkesteg", "kyllingelår",
      "kyllingebryst", "andebryst", "fiskefrikadelle", "fiskefilet", "stegt rødspætte", "paneret fisk", "laksefilet", "røget laks",
      "gravad laks", "rejemad", "krabbesalat", "fiskesuppe", "klar suppe", "aspargessuppe", "broccolisuppe", "gulerodssuppe",
      "linsesuppe", "ærtesuppe", "minestrone", "ramen", "curry", "tikka masala", "dal", "biryani",
      "pad thai", "dumplings", "dim sum", "gyoza", "poke bowl", "ceviche", "paella", "risotto",
      "gnocchi", "ravioli", "tortellini", "cannelloni", "carbonara", "bolognese", "calzone", "focaccia",
      "bruschetta", "antipasti", "moussaka", "souvlaki", "gyros", "dolmer", "tagine", "shakshuka",
      "falafelrulle", "pitabrød", "wrap", "quiche", "tærte", "gryde", "ovnret", "frikassé",
      "stuvning", "stroganoff", "schnitzel", "cordon bleu", "wienerschnitzel", "ratatouille", "ostesandwich", "panini",
      "club sandwich", "æggesalat", "rejesalat", "hønsesalat", "tunsalat", "græsk salat", "cæsarsalat", "kikærtesalat",
      "nudelsuppe", "grøntsagsgratin", "kartoffelgratin", "fiskegratin", "tunmousse", "oksehaleragout", "boeuf bourguignon", "coq au vin",
    ],
  },
  {
    name: "Drikkevarer",
    emoji: "☕",
    words: [
      "vand", "danskvand", "kildevand", "isvand", "mælk", "skummetmælk", "minimælk", "letmælk",
      "sødmælk", "kærnemælk", "kakao", "varm kakao", "kaffe", "espresso", "cappuccino", "latte",
      "macchiato", "americano", "iskaffe", "te", "sort te", "grøn te", "hvid te", "urtete",
      "frugtte", "iste", "juice", "æblejuice", "appelsinjuice", "multifrugtjuice", "tomatjuice", "saft",
      "hyldeblomstsaft", "solbærsaft", "ribssaft", "æblemost", "sodavand", "cola", "sportsvand", "ginger ale",
      "tonic", "limonade", "smoothie", "milkshake", "øl", "pilsner", "classic", "pale ale",
      "ipa", "stout", "porter", "hvedeøl", "cider", "vin", "rødvin", "hvidvin",
      "rosévin", "portvin", "sherry", "champagne", "cava", "prosecco", "spumante", "spiritus",
      "vodka", "rom", "gin", "tequila", "whisky", "cognac", "brandy", "likør",
      "snaps", "akvavit", "bitter", "vermouth", "absint", "gløgg", "punch", "cocktail",
      "flat white", "cortado", "mokka", "koldbryg", "filterkaffe", "stempelkaffe", "chai", "matcha",
      "rooibos", "kamillete", "pebermyntete", "ingefærte", "citronte", "honningte", "granatæblejuice", "ananasjuice",
      "druesaft", "pærejuice", "gulerodsjuice", "detoxjuice", "bananmilkshake", "chokolademælk", "ymer", "tykmælk",
      "kefir", "drikkeyoghurt", "proteinshake", "energidrik", "sportsdrik", "appelsinsodavand", "citronsodavand", "mineralvand",
      "postevand", "agurkevand", "citronvand", "kokosvand", "rabarbersaft", "kirsebærsaft", "blåbærsaft", "tranebærjuice",
      "æblecider", "pærecider", "mjød", "hvidtøl", "julebryg", "påskebryg", "bock", "weissbier",
      "alkoholfri øl", "mousserende vin", "dessertvin", "madeira", "marsala", "riesling", "chardonnay", "pinot noir",
      "merlot", "cabernet", "syrah", "tempranillo", "sangria", "hot toddy", "irish coffee", "mojito",
      "daiquiri", "margarita", "negroni", "martini", "gin og tonic", "rom og cola", "whisky sour", "bloody mary",
      "aperol spritz", "espresso martini", "pina colada", "kaffepunch", "dram", "isafkølet te", "sommerdrink", "vinterdrink",
      "frugtpunch", "bowle", "most", "urtesnaps", "kryddersnaps", "kirsebærvin", "hyldeblomstvin", "mousserende saft",
      "maltøl", "brown ale", "amber ale", "session ipa", "hvedebrus",
    ],
  },
  {
    name: "Frugt & Grønt",
    emoji: "🍎",
    words: [
      "Æble", "Pære", "Banan", "Appelsin", "Citron", "Lime", "Jordbær", "Hindbær",
      "Blåbær", "Kirsebær", "Drue", "Melon", "Vandmelon", "Ananas", "Mango", "Kiwi",
      "Fersken", "Blomme", "Tomat", "Agurk", "Gulerod", "Kartoffel", "Løg", "Hvidløg",
      "Peberfrugt", "Broccoli", "Blomkål", "Spinat", "Salat", "Majs", "Ærter", "Bønner",
      "Svamp", "Aubergine", "Squash", "Rødbede", "Selleri", "Porre", "Radise", "Græskar",
      "Mandarin", "Klementin", "Vindrue", "Nektarin", "Brombær", "Tyttebær", "Tranebær", "Solbær",
      "Ribs", "Stikkelsbær", "Papaya", "Granatæble", "Figen", "Daddel", "Kokosnød", "Chili",
      "Pastinak", "Persillerod", "Forårsløg", "Purløg", "Jordskok", "Kål", "Hvidkål", "Rødkål",
      "Spidskål", "Savojkål", "Grønkål", "Rosenkål", "Rucola", "Feldsalat", "Asparges", "Linser",
      "Champignon", "Portobello", "Kantarel", "Trøffel", "Ingefær", "Gurkemeje", "Oliven", "Kapers",
      "Avocado", "Artiskok",
      "Guava", "Litchi", "Dragefrugt", "Passionsfrugt", "Karambol", "Kaki", "Kvæde", "Morbær",
      "Hyben", "Havtorn", "Knoldselleri", "Bladselleri", "Fennikel", "Pak choi", "Kinakål", "Bladbede",
      "Mangold", "Brøndkarse", "Karse", "Endivie", "Radicchio", "Cikorie", "Julesalat", "Iceberg",
      "Romainesalat", "Hovedsalat", "Babyspinat", "Ærteskud", "Bønnespirer", "Mungbønner", "Kikærter", "Kidneybønner",
      "Edamame", "Sojabønner", "Brune bønner", "Hestebønner", "Snitbønner", "Sukkerærter", "Majskolbe", "Babymajs",
      "Græskarkerner", "Solsikkefrø", "Sesamfrø", "Hørfrø", "Chiafrø", "Valnød", "Hasselnød", "Mandel",
      "Cashewnød", "Pistacie", "Pekannød", "Paranød", "Macadamia", "Jordnød", "Rosin", "Sveske",
      "Tørret abrikos", "Tørret figen", "Tørret mango", "Goji", "Physalis", "Pomelo", "Blodappelsin", "Bergamot",
      "Yuzu", "Kumquat", "Tamarind", "Okra", "Peberrod", "Majroe", "Kålrabi", "Glaskål",
      "Turnips", "Batat", "Sødkartoffel", "Yams", "Taro", "Shiitake", "Østershat", "Enoki",
      "Karl johan", "Rørhat", "Skovsvamp", "Morkel", "Ramsløg", "Mynte", "Basilikum", "Persille",
      "Dild", "Timian", "Rosmarin", "Salvie", "Oregano", "Estragon", "Kørvel", "Koriander",
      "Citronmelisse", "Brøndsalat",
    ],
  },
  {
    name: "Sport",
    emoji: "⚽",
    words: [
      "Fodbold", "Håndbold", "Basketball", "Volleyball", "Tennis", "Badminton", "Bordtennis", "Golf",
      "Svømning", "Løb", "Cykling", "Ridning", "Boksning", "Brydning", "Karate", "Judo",
      "Gymnastik", "Atletik", "Stavspring", "Højdespring", "Længdespring", "Skøjteløb", "Ishockey", "Skiløb",
      "Snowboard", "Surfing", "Sejlsport", "Roning", "Kajak", "Klatring", "Dart", "Bowling",
      "Curling", "Fægtning", "Triatlon", "Spydkast", "Diskos", "Vægtløftning", "Dans", "Parkour",
      "Floorball", "Rugby", "Amerikansk fodbold", "Baseball", "Cricket", "Dykning", "Vandpolo", "Kajakroning",
      "Sejlads", "Windsurfing", "Kitesurfing", "Kunstskøjteløb", "Mountainbike", "BMX", "Sprint", "Maraton",
      "Hækkeløb", "Stangspring", "Kuglestød", "Diskoskast", "Hammerkast", "Trampolin", "Taekwondo", "Bueskydning",
      "Skydning", "Dressur", "Springridning", "Motorsport", "Formel 1", "Rally", "Motocross", "Speedway",
      "Go-kart", "Styrkeløft", "Bodybuilding", "Crossfit", "Fitness", "Yoga", "Pilates", "Zumba",
      "Aerobic", "Ballet", "Hiphop", "Pardans", "Billard", "Snooker", "Petanque",
      "Padel", "Squash", "Beachvolley", "Futsal", "Hockey", "Landhockey", "Lacrosse", "Softball",
      "Kricket", "Skiskydning", "Langrend", "Alpint", "Slalom", "Storslalom", "Skihop", "Freestyle",
      "Hurtigløb", "Bobslæde", "Skeleton", "Kælk", "Klatrevæg", "Bouldering", "Bjergbestigning", "Orienteringsløb",
      "Terrænløb", "Forhindringsløb", "Stafetløb", "Ultraløb", "Halvmaraton", "Gadeløb", "Trailløb", "Cykelløb",
      "Landevejscykling", "Banecykling", "Cyclocross", "Gravel", "Enduro", "Downhill", "Synkronsvømning", "Udspring",
      "Tårnspring", "Vandgymnastik", "Aquafitness", "Longboard", "Freerunning", "Trampolinspring", "Rytmisk gymnastik", "Redskabsgymnastik",
      "Tumbling", "Cheerleading", "Akrobatik", "Kampsport", "Kickboksning", "Muay thai", "Jiu-jitsu", "Aikido",
      "Kendo", "Sumo", "Capoeira", "Kårde", "Floret", "Sabel", "Lerdueskydning", "Riffelskydning",
      "Pistolskydning", "Dartkast", "Keglespil", "Kroket", "Minigolf", "Discgolf", "Frisbee", "Ultimate",
      "Boccia", "Kubb", "Tovtrækning", "Armlægning", "Styrketræning", "Spinning", "Indendørs roning", "Kettlebell",
      "Cirkeltræning", "Intervaltræning", "Stavgang", "Vandreture", "Skovtræning", "Gadeidræt", "Rullehockey", "Isfiskeri",
      "Sportsfiskeri", "Faldskærmsudspring", "Drageflyvning", "Kitesurf", "Wakeboard", "Vandski", "Dragebåd", "Kaproning",
      "Sejlkonkurrence", "Orienteringscykling",
    ],
  },
  {
    name: "Danske byer",
    emoji: "🏙️",
    words: [
      "København", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens",
      "Vejle", "Roskilde", "Herning", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge",
      "Holstebro", "Slagelse", "Helsingør", "Hillerød", "Sønderborg", "Svendborg", "Hjørring", "Holbæk",
      "Frederikshavn", "Nørresundby", "Ringsted", "Haderslev", "Skive", "Nykøbing", "Kalundborg", "Aabenraa",
      "Ribe", "Skagen", "Frederikssund", "Grenaa", "Thisted", "Varde", "Middelfart", "Nyborg",
      "Hørsholm", "Taastrup", "Ishøj", "Birkerød", "Farum", "Smørumnedre", "Skanderborg", "Nykøbing Falster",
      "Lillerød", "Korsør", "Nakskov", "Brønderslev", "Haslev", "Hobro", "Værløse", "Hedehusene",
      "Dragør", "Vordingborg", "Hedensted", "Odder", "Struer", "Fløng", "Lystrup", "Jyllinge",
      "Sorø", "Vejen", "Hundested", "Sæby", "Bjerringbro", "Fredensborg", "Bogense", "Kerteminde",
      "Maribo", "Rønne", "Nexø", "Allinge", "Svaneke", "Gudhjem", "Aakirkeby", "Christiansø",
      "Skjern", "Tønder", "Lemvig",
      "Ikast", "Brande", "Give", "Grindsted", "Billund", "Rødding", "Vojens", "Toftlund",
      "Gram", "Løgumkloster", "Højer", "Bredebro", "Skærbæk", "Ølgod", "Oksbøl", "Blåvand",
      "Vorbasse", "Bramming", "Gørding", "Holsted", "Agerbæk", "Nordborg", "Augustenborg", "Gråsten",
      "Padborg", "Kruså", "Tinglev", "Bov", "Rødekro", "Vamdrup", "Lunderskov", "Jelling",
      "Egtved", "Børkop", "Juelsminde", "Løsning", "Tørring", "Uldum", "Bording", "Sunds",
      "Aulum", "Vildbjerg", "Kibæk", "Videbæk", "Spjald", "Tarm", "Hvide Sande", "Ringkøbing",
      "Ulfborg", "Vemb", "Hjerm", "Vinderup", "Karup", "Kjellerup", "Ans", "Ulstrup",
      "Langå", "Hadsten", "Hinnerup", "Hammel", "Galten", "Ry", "Them", "Brædstrup",
      "Egå", "Risskov", "Tranbjerg", "Beder", "Mårslet", "Solbjerg", "Harlev", "Sabro",
      "Trige", "Hadsund", "Arden", "Støvring", "Skørping", "Nibe", "Aars", "Farsø",
      "Løgstør", "Fjerritslev", "Brovst", "Aabybro", "Pandrup", "Blokhus", "Løkken", "Vrå",
      "Tårs", "Sindal", "Hirtshals", "Assens", "Faaborg", "Ringe", "Munkebo", "Otterup",
      "Bogense by", "Glamsbjerg", "Årup", "Ejby", "Præstø", "Stege", "Fakse", "Rødvig",
      "Store Heddinge", "Karise", "Tølløse", "Jyderup", "Gørlev", "Høng",
    ],
  },
  {
    name: "Natur",
    emoji: "🌲",
    words: [
      "Skov", "Træ", "Blomst", "Græs", "Busk", "Mose", "Sø", "Å",
      "Flod", "Hav", "Strand", "Klit", "Bjerg", "Bakke", "Dal", "Eng",
      "Mark", "Klippe", "Sten", "Sand", "Jord", "Regn", "Sne", "Tåge",
      "Sky", "Sol", "Måne", "Stjerne", "Vind", "Storm", "Lyn", "Torden",
      "Regnbue", "Vandfald", "Ø", "Fjord", "Gletsjer", "Vulkan", "Ørken", "Jungle",
      "Planet", "Hagl", "Slud", "Blæst", "Orkan", "Tyfon", "Tornado", "Skypumpe",
      "Dis", "Rim", "Frost", "Is", "Tøvejr", "Solopgang", "Solnedgang", "Daggry",
      "Skumring", "Nat", "Dag", "Slette", "Regnskov", "Oase", "Savanne", "Tundra",
      "Isbræ", "Jordskælv", "Bæk", "Ocean", "Bugt", "Kyst", "Rev", "Halvø",
      "Koralrev", "Drypstenshule", "Grotte", "Grus", "Mudder", "Ler", "Støv", "Aske",
      "Kilde", "Gejser", "Sump", "Hede", "Krat",
      "Vandløb", "Kanal", "Dam", "Tjørn", "Dige", "Vold", "Banke", "Skrænt",
      "Kløft", "Slugt", "Plateau", "Højslette", "Bjergkæde", "Tinde", "Pas", "Morænebakke",
      "Ås", "Dødishul", "Rørskov", "Siv", "Tagrør", "Lyng", "Mos", "Lav",
      "Bregne", "Padderok", "Løvskov", "Nåleskov", "Blandskov", "Plantage", "Lund", "Allé",
      "Læbælte", "Marskeng", "Strandeng", "Salteng", "Vadehav", "Sandbanke", "Revle", "Tange",
      "Odde", "Næs", "Pynt", "Skær", "Holm", "Skærgård", "Fjeldside", "Snegrænse",
      "Trægrænse", "Permafrost", "Tørvemose", "Højmose", "Kær", "Ellesump", "Birkekrat", "Pilekrat",
      "Brombærkrat", "Stjernehimmel", "Nordlys", "Halo", "Solformørkelse", "Måneformørkelse", "Meteor", "Stjerneskud",
      "Komet", "Mælkevejen", "Stjernebillede", "Ebbe", "Tidevand", "Brænding", "Dønning", "Havstrøm",
      "Hvirvel", "Malstrøm", "Brådsø", "Havblik", "Tågebanke", "Morgendug", "Rimfrost", "Isslag",
      "Snefog", "Snedrive", "Tøbrud", "Forårsregn", "Støvregn", "Skybrud", "Hedebølge", "Frostnat",
      "Solskin", "Halvskyet", "Overskyet", "Vindstille", "Brise", "Kuling", "Stormflod", "Højvande",
      "Lavvande", "Klippekyst", "Kridtklint", "Sandflugt", "Hedelandskab", "Engdrag", "Bakkedrag",
    ],
  },
  {
    name: "Køkken",
    emoji: "🍳",
    words: [
      "Gryde", "Pande", "Kniv", "Gaffel", "Ske", "Tallerken", "Skål", "Glas",
      "Kop", "Krus", "Komfur", "Ovn", "Køleskab", "Fryser", "Mikroovn", "Opvaskemaskine",
      "Brødrister", "Elkedel", "Kaffemaskine", "Blender", "Røremaskine", "Si", "Rivejern", "Dåseåbner",
      "Proptrækker", "Skærebræt", "Viskestykke", "Forklæde", "Grydeske", "Piskeris", "Spatel", "Saks",
      "Vægt", "Målebæger", "Bageform", "Rullepind", "Termometer", "Tang", "Tragt", "Dørslag",
      "Urtekniv", "Brødkniv", "Kokkekniv", "Kødøkse", "Fjerkræsaks", "Skræller", "Hvidløgspresser", "Oplukker",
      "Slev", "Hulske", "Paletkniv", "Dejskraber", "Madpincet", "Pølsetang", "Måleske", "Køkkenvægt",
      "Stegetermometer", "Ur", "Minutur", "Morter", "Pistil", "Kaffefilter", "Tepose", "Teske",
      "Spiseske", "Bestik", "Dyb tallerken", "Flad tallerken", "Sidetallerken", "Fad", "Kande", "Vandglas",
      "Vinglas", "Ølglas", "Snapseglas", "Underkop", "Kasserolle", "Stegepande", "Grillpande", "Wok",
      "Bradepande", "Springform", "Tærteform", "Muffinform", "Kagerulle", "Udstikker", "Sprøjtepose", "Tyl",
      "Bagepapir", "Stanniol", "Husholdningsfilm", "Frysepose", "Madkasse", "Termokande", "Isterningebakke", "Bageplade",
      "Stegegryde", "Saftpresser",
      "Dampindsats", "Dampkoger", "Trykkoger", "Slowcooker", "Airfryer", "Sandwichgrill", "Vaffeljern", "Æggekoger",
      "Mælkeskummer", "Kaffekværn", "Stempelkande", "Filtertragt", "Espressokande", "Tekande", "Sukkerskål", "Flødekande",
      "Saltkar", "Peberkværn", "Saltkværn", "Krydderihylde", "Opbevaringsglas", "Patentglas", "Sylteglas", "Plastikbeholder",
      "Frostboks", "Køleelement", "Køletaske", "Isspand", "Isterningeform", "Dejkrog", "Håndmikser", "Stavblender",
      "Foodprocessor", "Minihakker", "Grøntsagshakker", "Spiralskærer", "Mandolinjern", "Ostehøvel", "Ostekniv", "Smørkniv",
      "Filetkniv", "Udbenerkniv", "Santoku", "Tomatkniv", "Æbleudstikker", "Melonkugleske", "Doseringsske", "Portionsske",
      "Isske", "Kagespade", "Tærtespade", "Serveringsgaffel", "Kødgaffel", "Grillspyd", "Grillbørste", "Grillhandske",
      "Grydelap", "Ovnhandske", "Kølerist", "Bagepensel", "Melsigte", "Kagestempel", "Kageform", "Tærtering",
      "Portionsform", "Ramekin", "Souffléform", "Terrin", "Stegeso", "Wokring", "Dampkurv", "Sushimåtte",
      "Morter sæt", "Saltbøsse", "Oliekande", "Eddikeflaske", "Serveringsskål", "Salatskål", "Salatsæt", "Suppeterrin",
      "Sovsekande", "Smørskål", "Ostebræt", "Skærebræt træ", "Opvaskebalje", "Opvaskebørste", "Karklud", "Opvaskehandske",
      "Affaldssortering", "Kompostspand", "Brødkasse", "Frugtskål", "Dåsestativ", "Krydderikværn",
    ],
  },
  {
    name: "Transport",
    emoji: "🚗",
    words: [
      "Bil", "Bus", "Tog", "Cykel", "Knallert", "Motorcykel", "Lastbil", "Varevogn",
      "Taxa", "Ambulance", "Brandbil", "Politibil", "Traktor", "Gravko", "Sporvogn", "Metro",
      "Fly", "Helikopter", "Raket", "Ballon", "Skib", "Færge", "Båd", "Sejlbåd",
      "Kano", "Kajak", "Jetski", "Ubåd", "Scooter", "Løbehjul", "Rulleskøjter", "Skateboard",
      "Trillebør", "Slæde", "Elevator", "Rulletrappe", "Svævebane", "Gondol", "Hangglider", "Faldskærm",
      "Flyver", "Skraldebil", "Fejemaskine", "Kranbil", "Mejetærsker", "Gravemaskine", "Gaffeltruck", "Bulldozer",
      "Autocamper", "Campingvogn", "Trailer", "Hestevogn", "Kane", "Snescooter", "Svævefly", "Luftballon",
      "Zeppeliner", "Rumfærge", "Satellit", "Letbane", "Monorail", "Bjergbane", "Rullestol", "Barnevogn",
      "Klapvogn", "Indkøbsvogn", "Robåd", "Motorbåd", "Yacht", "Vandscooter", "Gummibåd", "Tømmerflåde",
      "Hovercraft", "Katamaran", "Trehjulet", "Tandemcykel", "Elcykel", "Ladcykel", "Ethjulet", "Segway",
      "Hoverboard", "Rulleski", "Bæreraket", "Drosje", "Karet", "Dumper", "Rutebil", "S-tog",
      "El-scooter", "Delebil", "Budcykel", "Christianiacykel", "Transportcykel", "Foldecykel", "Racercykel", "Citybike",
      "Bycykel", "Veteranbil", "Sportsvogn", "Cabriolet", "Stationcar", "Sedan", "Coupé", "Pickup",
      "Minibus", "Turistbus", "Dobbeltdækker", "Ledbus", "Trolleybus", "Skolebus", "Sightseeingbus", "Regionaltog",
      "Intercitytog", "Lyntog", "Godstog", "Damplokomotiv", "Diesellokomotiv", "Godsvogn", "Personvogn", "Sovevogn",
      "Spisevogn", "Kabelbane", "Tandhjulsbane", "Skinnebus", "Draisine", "Containerskib", "Tankskib", "Bulkskib",
      "Krydstogtskib", "Isbryder", "Slæbebåd", "Lodsbåd", "Fiskekutter", "Trawler", "Sejljolle", "Husbåd",
      "Pram", "Vandflyver", "Sportsfly", "Passagerfly", "Fragtfly", "Jetfly", "Propelfly", "Biplan",
      "Ultralet fly", "Luftskib", "Varmluftballon", "Paraglider", "Rumkapsel", "Månebil", "Rover", "Maglev",
      "Skilift", "Stolelift", "Tallerkenlift", "Trappelift", "Sækkevogn", "Palleløfter", "Transportbånd", "Rullebånd",
      "Ladcykel elektrisk", "Knallert 30", "Motorscooter", "Quad", "Firehjulstrækker", "Snescooter bælte", "Mejetærsker vogn", "Tankvogn",
      "Flyttebil", "Kølebil", "Budbil", "Postbil", "Vejhøvl", "Asfaltmaskine", "Tromle", "Minigraver",
      "Teleskoplæsser", "Betonblander", "Betonpumpe", "Dumperbil", "Skovmaskine",
    ],
  },
  {
    name: "Erhverv",
    emoji: "👷",
    words: [
      "Læge", "Sygeplejerske", "Tandlæge", "Lærer", "Pædagog", "Politibetjent", "Brandmand", "Soldat",
      "Pilot", "Stewardesse", "Kok", "Tjener", "Bager", "Slagter", "Frisør", "Mekaniker",
      "Tømrer", "Murer", "Elektriker", "Blikkenslager", "Maler", "Landmand", "Fisker", "Gartner",
      "Advokat", "Dommer", "Revisor", "Ingeniør", "Arkitekt", "Programmør", "Journalist", "Fotograf",
      "Musiker", "Skuespiller", "Forfatter", "Dyrlæge", "Astronaut", "Bibliotekar", "Postbud", "Chauffør",
      "Farmaceut", "Psykolog", "Fysioterapeut", "Kiropraktor", "Professor", "Forsker", "Redder", "Kaptajn",
      "Sømand", "Skovhugger", "Snedker", "VVS-installatør", "Smed", "Svejser", "Designer", "It-supporter",
      "Bogholder", "Bankrådgiver", "Ejendomsmægler", "Sælger", "Kassedame", "Bartender", "Receptionist", "Kosmetolog",
      "Massør", "Skrædder", "Skomager", "Urmager", "Guldsmed", "Redaktør", "Oversætter", "Tolk",
      "Sanger", "Instruktør", "Kunstner", "Borgmester", "Minister", "Præst", "Bedemand", "Rengøringsassistent",
      "Skraldemand", "Buschauffør", "Taxachauffør", "Lokomotivfører",
      "Anlægsgartner", "Landinspektør", "Byplanlægger", "Landskabsarkitekt", "Indretningsarkitekt", "Industridesigner", "Grafiker", "Illustrator",
      "Animator", "Spiludvikler", "Webudvikler", "Systemadministrator", "Netværkstekniker", "Dataanalytiker", "Statistiker", "Matematiker",
      "Fysiker", "Kemiker", "Biolog", "Geolog", "Meteorolog", "Astronom", "Arkæolog", "Historiker",
      "Filosof", "Sociolog", "Antropolog", "Økonom", "Jurist", "Notar", "Anklager", "Forsvarer",
      "Politikommissær", "Kriminalbetjent", "Hundefører", "Toldbetjent", "Fængselsbetjent", "Livvagt", "Vagtmand", "Dørmand",
      "Livredder", "Falckredder", "Ambulancebehandler", "Jordemoder", "Sundhedsplejerske", "Hjemmehjælper", "Ergoterapeut", "Diætist",
      "Optiker", "Bandagist", "Tandplejer", "Tandtekniker", "Klinikassistent", "Laborant", "Bioanalytiker", "Radiograf",
      "Patolog", "Kirurg", "Anæstesilæge", "Børnelæge", "Øjenlæge", "Hudlæge", "Ortopæd", "Dyrepasser",
      "Zoolog", "Skovfoged", "Biavler", "Mejerist", "Konditor", "Sommelier", "Barista", "Kantineleder",
      "Hotelreceptionist", "Rejseleder", "Guide", "Eventkoordinator", "Projektleder", "Indkøber", "Logistikchef", "Lagerarbejder",
      "Truckfører", "Kranfører", "Stilladsarbejder", "Isolatør", "Glarmester", "Tagdækker", "Brolægger", "Asfaltarbejder",
      "Maskinmester", "Skibsfører", "Styrmand", "Flymekaniker", "Lufthavnsansat", "Togfører", "Billetkontrollør", "Buschauffør turist",
      "Kurér", "Flyttemand",
    ],
  },
  {
    name: "Tøj og Sko",
    emoji: "👕",
    words: [
      "Trøje", "Skjorte", "T-shirt", "Bluse", "Sweater", "Cardigan", "Jakke", "Frakke",
      "Bukser", "Jeans", "Shorts", "Nederdel", "Kjole", "Strømper", "Sokker", "Undertøj",
      "Sko", "Støvler", "Sandaler", "Sneakers", "Hjemmesko", "Hue", "Hat", "Kasket",
      "Halstørklæde", "Vanter", "Handsker", "Bælte", "Slips", "Butterfly", "Vest", "Badedragt",
      "Badebukser", "Pyjamas", "Regnjakke", "Dunjakke", "Habit", "Smykke", "Solbriller", "Regntøj",
      "Flyverdragt", "Badetøj", "Bikini", "Badeshorts", "Underbukser", "Trusser", "Bh", "Strømpebukser",
      "Nattøj", "Morgenkåbe", "Tørklæde", "Seler", "Blazer", "Smoking", "Hættetrøje", "Top",
      "Singlet", "Leggins", "Joggingbukser", "Overalls", "Gummistøvler", "Vinterstøvler", "Kondisko", "Løbesko",
      "Fodboldstøvler", "Gummisko", "Klipklappere", "Højhælede", "Stiletter", "Laksko", "Læderstøvler", "Ankelstøvler",
      "Snøresko", "Hyttesko", "Sejlersko", "Slippers", "Overtræksbukser", "Termotøj", "Vindjakke", "Læderjakke",
      "Denimjakke", "Fleecejakke", "Skibukser", "Skijakke", "Pandebånd", "Ørevarmer", "Krave", "Manchetter",
      "Forklæde", "Slør",
      "Poloshirt", "Langærmet", "Kortærmet", "Tanktop", "Body", "Nederdel plisséret", "Cowboybukser", "Chinos",
      "Habitbukser", "Stofbukser", "Culottebukser", "Palazzobukser", "Cargobukser", "Harembukser", "Jumpsuit", "Buksedragt",
      "Sommerkjole", "Festkjole", "Cocktailkjole", "Brudekjole", "Strikkjole", "Skjortekjole", "Tunika", "Poncho",
      "Cape", "Kimono", "Kaftan", "Sarong", "Vindbreaker", "Softshelljakke", "Dunvest", "Quiltet jakke",
      "Parkacoat", "Trenchcoat", "Uldfrakke", "Cardigan lang", "Pullover", "Rullekrave", "V-hals", "Striktrøje",
      "Fleecetrøje", "Sweatshirt", "Træningsjakke", "Træningsbukser", "Cykelshorts", "Badekåbe", "Undertrøje", "Boxershorts",
      "Hipsters", "Tanga", "Sportsbh", "Korset", "Underkjole", "Chemise", "Natskjorte", "Hjemmesko fnug",
      "Futsko", "Klipklapper", "Espadrille", "Mokkasin", "Loafer", "Ballerinasko", "Pumps", "Sandal med rem",
      "Gladiatorsandal", "Wedges", "Platformsko", "Træsko", "Tøffel", "Badesandal", "Vandresko", "Trekkingstøvle",
      "Arbejdsstøvle", "Ridestøvle", "Cowboystøvle", "Chelseaboots", "Snørestøvle", "Regnstøvle", "Skistøvle", "Skøjter",
      "Rulleskøjter sko", "Halstørklæde uld", "Tørklæde silke", "Kasket flad", "Bøllehat", "Stråhat", "Filthat", "Baret",
      "Turban", "Solhat", "Ørering", "Halskæde", "Armbånd", "Ring", "Broche", "Manchetknap",
      "Slipsenål", "Seler bukser", "Livrem", "Taske skulder", "Rygsæk lille", "Mavebælte", "Hårbånd", "Hårspænde",
      "Hårelastik",
    ],
  },
  {
    name: "Kroppen",
    emoji: "🫀",
    words: [
      "Hoved", "Hår", "Pande", "Øjne", "Øre", "Næse", "Mund", "Læber",
      "Tænder", "Tunge", "Hage", "Kind", "Hals", "Nakke", "Skulder", "Arm",
      "Albue", "Håndled", "Hånd", "Finger", "Tommel", "Negl", "Bryst", "Mave",
      "Ryg", "Hofte", "Ben", "Knæ", "Lægge", "Ankel", "Fod", "Tå",
      "Hjerte", "Lunge", "Hjerne", "Mavesæk", "Lever", "Nyre", "Knogle", "Muskel",
      "Øjenbryn", "Øje", "Øjenvippe", "Læbe", "Tand", "Gane", "Kæbe", "Strube",
      "Underarm", "Tommelfinger", "Pegefinger", "Langemand", "Ringfinger", "Lillefinger", "Navle", "Rygsøjle",
      "Lænd", "Balle", "Lår", "Skinneben", "Læg", "Hæl", "Storetå", "Hud",
      "Sene", "Marv", "Led", "Brusk", "Blod", "Åre", "Vene", "Arterie",
      "Milt", "Bugspytkirtel", "Tarm", "Tyndtarm", "Tyktarm", "Blindtarm", "Rygmarv", "Nerve",
      "Kirtel", "Skjoldbruskkirtel", "Blære", "Livmoder", "Æggestok",
      "Isse", "Tinding", "Øjenlåg", "Pupil", "Iris", "Hornhinde", "Næsebor", "Næseryg",
      "Nakkehår", "Adamsæble", "Kraveben", "Skulderblad", "Overarm", "Biceps", "Triceps", "Håndflade",
      "Håndryg", "Knoer", "Fingerspids", "Fingeraftryk", "Brystkasse", "Ribben", "Brystben", "Mellemgulv",
      "Bughule", "Hoftekam", "Korsben", "Haleben", "Skridt", "Lyske", "Knæskal", "Knæhase",
      "Lårmuskel", "Baglår", "Akillessene", "Fodsål", "Fodryg", "Svang", "Vrist", "Tåneglen",
      "Lillefinger tå", "Øreflip", "Øregang", "Trommehinde", "Ørevoks", "Tandkød", "Fortand", "Hjørnetand",
      "Kindtand", "Visdomstand", "Tandemalje", "Spytkirtel", "Mandler", "Stemmebånd", "Luftrør", "Bronkier",
      "Lungeblære", "Mellemgulvmuskel", "Hjerteklap", "Hovedpulsåre", "Kranspulsåre", "Blodplade", "Rødt blodlegeme", "Hvidt blodlegeme",
      "Lymfe", "Lymfeknude", "Knoglemarv", "Ledbånd", "Ledkapsel", "Senehinde", "Muskelfiber", "Nervetråd",
      "Rygrad", "Hvirvel", "Diskus", "Bækken", "Skulderled", "Albueled", "Hofteled", "Knæled",
      "Ankelled", "Håndrodsknogle", "Kraniet", "Kæbeled", "Øjenhule", "Næsehule", "Hjernebark", "Lillehjerne",
      "Hjernestamme", "Hypofyse", "Binyre", "Bugspyt", "Galdeblære", "Tolvfingertarm", "Endetarm", "Urinleder",
      "Urinrør", "Sædleder", "Hårsæk", "Svedkirtel", "Talgkirtel", "Neglerod", "Pigment",
    ],
  },
  {
    name: "Musikinstrumenter",
    emoji: "🎸",
    words: [
      "Guitar", "Klaver", "Flygel", "Violin", "Bratsch", "Cello", "Kontrabas", "Harpe",
      "Trommer", "Tromme", "Bækken", "Tamburin", "Xylofon", "Marimba", "Trompet", "Basun",
      "Tuba", "Valdhorn", "Saxofon", "Klarinet", "Obo", "Fagot", "Tværfløjte", "Blokfløjte",
      "Mundharmonika", "Harmonika", "Orgel", "Synthesizer", "Banjo", "Mandolin", "Ukulele", "Bas",
      "Triangel", "Castagnetter", "Sækkepibe", "Lyre", "Cembalo", "Theremin", "Konga", "Bongotromme",
      "Keyboard", "Akustisk guitar", "Elguitar", "Basguitar", "Lut", "Piccolofløjte", "Panfløjte", "Basklarinet",
      "Sopransaxofon", "Altsaxofon", "Tenorsaxofon", "Barytonsaxofon", "Kornet", "Flygelhorn", "Trækbasun", "Sousafon",
      "Trommesæt", "Lilletromme", "Stortromme", "Tamtam", "Hi-hat", "Pauke", "Vibrafon", "Klokkespil",
      "Djembe", "Cajon", "Maracas", "Claves", "Rørklokker", "Gongong", "Syngeskål", "Jødeharpe",
      "Mundharpe", "Melodica", "Kazoo", "Drejelire", "Sitar", "Tabla", "Didgeridoo", "Balalajka",
      "Bouzouki", "Oud", "Koto", "Shamisen", "Sampler", "Trommemaskine", "Sequencer", "Mixerpult",
      "Fløjte tvær", "Altfløjte", "Basfløjte", "Næseflutte", "Okarina", "Tinfløjte", "Blokfløjte alt", "Blokfløjte sopran",
      "Engelskhorn", "Kontrafagot", "Basetthorn", "Sopraninosaxofon", "Bassaxofon", "Ventilbasun", "Althorn", "Tenorhorn",
      "Euphonium", "Bariton horn", "Piccolotrompet", "Naturtrompet", "Posthorn", "Jagthorn", "Alphorn", "Konkylie horn",
      "Harmonium", "Positiv orgel", "Kirkeorgel", "Elorgel", "Hammondorgel", "Spinet", "Klavikord", "Fortepiano",
      "Elklaver", "Digitalpiano", "Celesta", "Klokkespil rør", "Glockenspil", "Kalimba", "Mbira", "Sansula",
      "Håndpan", "Hangdrum", "Steeldrum", "Tabla par", "Darbuka", "Doumbek", "Bendir", "Riq",
      "Tar tromme", "Frametromme", "Oceandrum", "Regnstok", "Skrabetræ", "Guiro", "Cabasa", "Shaker",
      "Agogo", "Kobjælde", "Træblok", "Tempelblok", "Vibraslap", "Tamburin skind", "Jingle stick", "Klokke",
      "Håndklokke", "Triangel stor", "Fingercymbaler", "Becken", "Splash bækken", "Ride bækken", "Crash bækken", "Kina bækken",
      "Tom tom", "Floortom", "Roto tom", "Timbales", "Bongos par", "Congatromme", "Cajontromme", "Davul",
      "Taiko", "Dhol", "Dholak", "Mridangam", "Kanjira", "Udu", "Log drum", "Zither",
      "Hakkebræt", "Cimbalom", "Autoharpe", "Dulcimer", "Banjolele", "Tenorbanjo", "Resonatorguitar", "Dobro",
      "Tolvstrenget guitar", "Klassisk guitar", "Flamencoguitar", "Slideguitar", "Lap steel", "Kontrabas bue", "Viola da gamba",
    ],
  },
  {
    name: "Møbler og Hjemmet",
    emoji: "🛋️",
    words: [
      "stol", "bord", "sofa", "seng", "skab", "reol", "kommode", "hylde",
      "skrivebord", "spisebord", "sofabord", "natbord", "lænestol", "puf", "skammel", "bænk",
      "klædeskab", "vitrineskab", "bogreol", "tv-bord", "tæppe", "gardin", "persienne", "lampe",
      "lysekrone", "gulvlampe", "bordlampe", "væglampe", "spejl", "maleri", "plakat", "ramme",
      "vase", "krukke", "urtepotteskjuler", "pude", "dyne", "sengetøj", "lagen", "madras",
      "topmadras", "rullemadras", "vaskemaskine", "tørretumbler", "opvaskemaskine", "køleskab", "fryser", "komfur",
      "ovn", "mikroovn", "brødrister", "elkedel", "kaffemaskine", "blender", "røremaskine", "støvsuger",
      "strygejern", "strygebræt", "tørrestativ", "moppe", "kost", "fejebakke", "spand", "karklud",
      "viskestykke", "håndklæde", "badekåbe", "badeforhæng", "toiletbørste", "skraldespand", "vasketøjskurv", "knagerække",
      "bøjle", "skohylde", "paraplyholder", "dørmåtte", "postkasse", "ringeklokke", "stikkontakt", "forlængerledning",
      "chaiselong", "hjørnesofa", "sovesofa", "daybed", "recliner", "gyngestol", "barstol", "kontorstol drejelig",
      "spisebordsstol", "foldestol", "klapstol", "taburet", "sidebord", "konsolbord", "klapbord", "cafébord",
      "havebord", "havestol", "hængekøje", "hængestol", "kurvestol", "reol åben", "vægreol", "hjørnereol",
      "vitrine", "buffet", "anretterbord", "chatol", "sekretær", "kommode høj", "kistebænk", "entrémøbel",
      "garderobeskab", "skoskab", "apotekerskab", "medicinskab", "badeværelsesskab", "køkkenskab", "overskab", "underskab",
      "skuffemodul", "køkkenø", "spisekrog", "bordplade", "vindueskarm", "gulvtæppe", "løber", "dørtæppe",
      "badeforhæng stang", "rullegardin", "plisségardin", "lamelgardin", "mørklægning", "gardinstang", "lysdæmper", "loftlampe",
      "pendel", "spot", "skinnespot", "uplight", "læselampe", "natlampe", "batterilys", "lyskæde",
      "lanterne", "olielampe", "stearinlysestage", "lysestage", "fyrfadslys", "duftlys", "diffusor", "luftrenser",
      "luftfugter", "affugter", "ventilator", "varmeblæser", "radiator", "gulvvarme", "brændeovn", "pejs",
      "brændekurv", "pyntepude", "plaid", "uldtæppe", "sengetæppe", "betræk", "pudebetræk", "sengeramme",
      "sengegavl", "lattenbund", "boxmadras", "sengebord", "spejlkommode", "knage", "vægkrog", "opslagstavle kork",
      "bogstøtte", "skammel fod", "plantestativ", "blomsterkasse", "vandkande",
    ],
  },
  {
    name: "Værktøj",
    emoji: "🔨",
    words: [
      "hammer", "skruetrækker", "skruenøgle", "svensknøgle", "tang", "knibtang", "bidetang", "papegøjetang",
      "rørtang", "sav", "fukssvans", "stiksav", "rundsav", "kædesav", "båndsav", "boremaskine",
      "skruemaskine", "slagnøgle", "vinkelsliber", "slibemaskine", "høvl", "stemmejern", "fil", "rasp",
      "sandpapir", "målebånd", "tommestok", "vaterpas", "vinkelmåler", "skydelære", "koben", "boltsaks",
      "pladesaks", "kniv", "hobbykniv", "spartel", "murske", "fugepistol", "fugebræt", "pensel",
      "malerulle", "malertape", "skruestik", "skruetvinge", "ambolt", "loddekolbe", "svejseapparat", "kompressor",
      "sømpistol", "hæftepistol", "limpistol", "lommelygte", "arbejdslampe", "sikkerhedsbriller", "høreværn", "åndedrætsværn",
      "arbejdshandsker", "sikkerhedssko", "hjelm", "knæbeskyttere", "stige", "stillads", "trillebør", "skovl",
      "spade", "greb", "rive", "hakke", "økse", "flækøkse", "beskæresaks", "hækkesaks",
      "græsslåmaskine", "buskrydder", "løvblæser", "sneskovl", "isskraber", "kost", "sneslynge", "multimeter",
      "forlængerled", "top nøgle", "topnøglesæt", "momentnøgle", "unbrakonøgle", "torxnøgle", "skralde", "skraldenøgle",
      "fastnøgle", "ringnøgle", "rørskærer", "gevindskærer", "gevindbor", "forsænker", "hulsav", "kopbor",
      "spiralbor", "betonbor", "træbor", "metalbor", "murbor", "borepatron", "borestander", "søjleboremaskine",
      "drejebænk", "fræser", "overfræser", "kantfræser", "pudsemaskine", "excentersliber", "båndsliber", "rystepudser",
      "polermaskine", "vinkelbeslag", "skruetrækkerbits", "bitssæt", "magnetholder", "skrueautomat", "skruetvinge lang", "limtvinge",
      "hjørnetvinge", "bænkhøvl", "blokhøvl", "sløjdkniv", "hulmejsel", "stikkeljern", "kløvekile", "brækjern",
      "nedbrydningshammer", "mejselhammer", "slaghammer", "gummihammer", "plasthammer", "kuglehammer", "forhammer", "murerhammer",
      "tagpaphammer", "sømudtrækker", "nittepistol", "popnittetang", "blindnitte", "skruestik bænk", "høvlbænk", "arbejdsbord",
      "savbuk", "geringssav", "geringslade", "kapsav", "dyksav", "styreskinne", "laserlinje", "lasermåler",
      "afstandsmåler", "krydslaser", "snorekridt", "kridtsnor", "blyantsmarkør", "ridsenål", "kørner", "filthætte",
      "slibesvamp", "slibeklods", "stålbørste", "skraber", "tapetkniv", "tapetbørste", "malerbakke", "forlængerskaft",
      "malersprøjte", "kompressorslange", "luftpistol", "sandblæser", "varmluftpistol", "loddetin", "loddefedt", "krympeflex",
      "kabelsko", "aftrækker", "momentnøgle lille",
    ],
  },
  {
    name: "Bygninger",
    emoji: "🏰",
    words: [
      "hus", "rækkehus", "lejlighed", "villa", "palæ", "slot", "borg", "fort",
      "fæstning", "tårn", "fyrtårn", "skyskraber", "højhus", "kontorbygning", "rådhus", "bibliotek",
      "museum", "teater", "biograf", "opera", "koncertsal", "skole", "gymnasium", "universitet",
      "børnehave", "vuggestue", "hospital", "klinik", "apotek", "kirke", "katedral", "moske",
      "synagoge", "tempel", "kloster", "station", "lufthavn", "havn", "fabrik", "lagerhal",
      "værksted", "garage", "carport", "skur", "drivhus", "orangeri", "lade", "stald",
      "silo", "mølle", "vindmølle", "vandmølle", "bageri", "slagteri", "supermarked", "indkøbscenter",
      "butik", "restaurant", "café", "bar", "pub", "hotel", "motel", "kro",
      "vandrerhjem", "fængsel", "politistation", "brandstation", "kaserne", "ambassade", "parlament", "domhus",
      "stadion", "sportshal", "svømmehal", "skøjtehal", "ridehal", "telt", "iglo", "tipi",
      "etagebygning", "andelsbolig", "ejerlejlighed", "kollegium", "bofællesskab", "plejehjem", "døgninstitution", "krisecenter",
      "sundhedshus", "lægehus", "tandlægeklinik", "dyreklinik", "fysioterapi klinik", "genoptræningscenter", "kursuscenter", "konferencecenter",
      "messehal", "udstillingshal", "koncertarena", "multiarena", "biografkompleks", "spillehal", "bowlingcenter", "fitnesscenter",
      "klatrecenter", "danseskole", "musikskole", "aftenskole", "efterskole", "højskole", "handelsskole", "teknisk skole",
      "erhvervsskole", "seminarium", "forskningscenter", "laboratoriebygning", "observatorium", "planetarium", "akvarium", "zoologisk have",
      "botanisk have", "drivhus stort", "væksthus", "gartneri", "planteskole", "dambrug", "hønsehus", "svinestald",
      "kostald", "ridehus", "hundepension", "kennel", "maskinhus", "foderlade", "kornsilo", "vandtårn",
      "transformerstation", "kraftværk", "varmeværk", "vandværk", "rensningsanlæg", "forbrændingsanlæg", "genbrugsstation", "deponi",
      "færgeleje", "kajanlæg", "dok", "tørdok", "skibsværft", "bådhus", "jollehavn", "lystbådehavn",
      "kontroltårn", "terminal", "ankomsthal", "afgangshal", "bagagehal", "hangar", "parkeringshus", "parkeringskælder",
      "busterminal", "rutebilstation", "remise", "sporskifte hus", "banegård", "perronhal", "viadukt", "akvædukt",
      "bunker", "skyttegrav anlæg", "vagttårn", "ringmur", "voldgrav", "borggård", "klokketårn", "spir",
      "kuppel", "søjlegang", "arkade", "pavillon", "orangeri stort",
    ],
  },
  {
    name: "Teknologi",
    emoji: "💻",
    words: [
      "computer", "bærbar", "tablet", "smartphone", "mobiltelefon", "smartwatch", "fjernsyn", "radio",
      "højttaler", "forstærker", "soundbar", "høretelefoner", "headset", "mikrofon", "kamera", "videokamera",
      "drone", "spillekonsol", "controller", "joystick", "mus", "tastatur", "skærm", "monitor",
      "printer", "scanner", "kopiermaskine", "router", "modem", "switch", "server", "harddisk",
      "usb-stik", "hukommelseskort", "powerbank", "oplader", "kabel", "ledning", "batteri", "pære",
      "lommeregner", "gps", "dashcam", "actionkamera", "projektor", "lærred", "robotstøvsuger", "plæneklipperrobot",
      "smart-tv", "e-bogslæser", "digital fotoramme", "røgalarm", "tyverialarm", "overvågningskamera", "termostat", "vejrstation",
      "elbil", "elcykel", "el-løbehjul", "solcelle", "vindmølle", "pacemaker", "høreapparat", "ultralydsscanner",
      "røntgenmaskine", "mri-scanner", "ct-scanner", "ekg-apparat", "respirator", "kuvøse", "3d-printer", "laser",
      "fiberoptik", "mikrochip", "transistor", "kondensator", "modstand", "diode", "printplade", "loddekolbe",
      "bærbar skærm", "ultrabook", "chromebook", "minicomputer", "mikrocomputer", "hovedcomputer", "bundkort", "processor",
      "grafikkort", "hukommelsesmodul", "køleblæser", "vandkøling", "strømforsyning", "kabinet", "netkort", "lydkort",
      "webkamera", "dokumentkamera", "mikrofonarm", "popfilter", "lydinterface", "mixer", "forforstærker", "studiemonitor",
      "øretelefoner", "trådløst headset", "støjreduktion", "højttalersæt", "subwoofer", "lydplanke", "multirumshøjttaler", "smarthøjttaler",
      "stemmeassistent", "smartlampe", "smartstik", "smartlås", "dørklokke video", "bevægelsessensor", "dørsensor", "vandsensor",
      "temperaturføler", "luftkvalitetsmåler", "cO2-måler", "vejrstation lille", "robotplæneklipper", "vinduespudserobot", "gulvvasker", "damprenser",
      "eltandbørste", "hårtrimmer", "skægtrimmer", "glattejern", "krøllejern", "hårtørrer", "massagepistol", "pulsur",
      "aktivitetsmåler", "blodtryksmåler", "blodsukkermåler", "iltmætningsmåler", "febertermometer", "høreapparat lille", "insulinpumpe", "elektrode",
      "oscilloskop", "funktionsgenerator", "spændingsregulator", "transformator", "relæ", "sikring", "jordkabel", "netfilter",
      "antenne", "parabol", "signalforstærker", "repeater", "accesspoint", "netværkskabel", "patchpanel", "fiberkabel",
      "lyslederkabel", "konverter", "adapter", "dockingstation", "kortlæser", "ekstern harddisk", "sSD", "nAS",
      "serverrack", "køleskabsdisplay", "digital kalender", "e-blæk skærm", "projektor lille", "dokumentscanner", "stregkodescanner", "etiketprinter",
      "3d-scanner", "laserskærer", "cnc-fræser", "robotarm",
    ],
  },
  {
    name: "Slik og Desserter",
    emoji: "🍬",
    words: [
      "chokolade", "mørk chokolade", "mælkechokolade", "hvid chokolade", "flødebolle", "lakrids", "saltlakrids", "sød lakrids",
      "vingummi", "karamel", "skumfidus", "bolsje", "slikkepind", "tyggegummi", "marcipan", "nougat",
      "konfekt", "pebermynte", "trøffel", "romkugle", "studenterbrød", "hindbærsnitte", "træstammer", "kage",
      "lagkage", "chokoladekage", "gulerodskage", "drømmekage", "citronmåne", "roulade", "mazarinkage", "brownie",
      "muffin", "cupcake", "cookie", "småkage", "vaniljekrans", "brunkage", "pebernød", "klejne",
      "æbleskive", "pandekage", "vaffel", "is", "flødeis", "sodavandsis", "sorbet", "gelato",
      "softice", "ispind", "isvaffel", "dessert", "budding", "fromage", "mousse", "panna cotta",
      "tiramisu", "cheesecake", "æblekage", "rødgrød", "frugtsalat", "risalamande", "koldskål", "kammerjunker",
      "marengs", "pavlova", "crème brûlée", "makron", "tærte", "frugttærte", "citronfromage", "romfromage",
      "chokolademousse", "karamelrand", "honningkage", "sirupskage", "kransekage", "romsnegl", "tebirkes", "spandauer",
      "slik", "popcorn", "chips",
      "chokoladebar", "nougatstang", "karamelbar", "nøddechokolade", "rosinchokolade", "appelsinchokolade", "mintchokolade", "chokoladekugle",
      "fyldt chokolade", "ganache", "praliné", "krokant", "nougatmasse", "marcipanbrød", "marcipankugle", "kransekagestang",
      "makronbund", "flødeskumskage", "jordbærtærte", "hindbærtærte", "blåbærtærte", "æbletærte", "rabarbertærte", "kirsebærtærte",
      "citrontærte", "chokoladetærte", "nøddetærte", "pekantærte", "banoffi", "cheesecake bagt", "ostekage kold", "tiramisukage",
      "mokkakage", "lagkagebund", "cremefyld", "konditorcreme", "vaniljecreme", "chokoladecreme", "karamelcreme", "flødeskum",
      "marengsbund", "marengstop", "pavlovabund", "brownie fudge", "blondie", "muffin bær", "cupcake glasur", "donut",
      "æbleskive fyldt", "klatkage", "drømmekage stykke", "brunsviger", "kanelsnegl", "romsnegl kage", "direktørsnegl", "kringle",
      "wienerbrødsstang", "smørkage", "hindbærkage", "træstamme kage", "othellolagkage", "sarah bernhardt", "gåsebryst", "napoleonshat",
      "kokosmakron", "kokosskråer", "havregrynskugle", "romkugle stykke", "chokoladekiks", "kiks med creme", "digestive", "smørkringle",
      "finskbrød", "jødekage", "pebernød lille", "brunkage stykke", "honningkage stykke", "sirupssnitte", "mariekiks", "fyldt kiks",
      "isbar", "ispinde", "isdessert", "parfait", "sorbetkugle", "frozen yoghurt", "milkshake is", "isterning frugt",
      "frugtis", "gele", "budding vanilje", "karamelbudding", "risengrød dessert", "æblegrød", "rabarbergrød", "blommegrød",
      "hyldebærsuppe",
    ],
  },
  {
    name: "Skole og Kontor",
    emoji: "📏",
    words: [
      "blyant", "kuglepen", "fyldepen", "tusch", "overstregningstusch", "farveblyant", "kridt", "tavle",
      "whiteboard", "svamp", "viskelæder", "blyantspidser", "lineal", "vinkelmåler", "passer", "penalhus",
      "saks", "lim", "limstift", "tape", "hæftemaskine", "hæfteklamme", "hulmaskine", "clips",
      "papir", "notesbog", "blok", "kladdehæfte", "ringbind", "mappe", "plastiklomme", "register",
      "konvolut", "frimærke", "brevåbner", "stempel", "blæk", "kalender", "post-it", "opslagstavle",
      "tegnestift", "magnet", "slettelak", "slettepen", "rettelak", "lommeregner", "computer", "mus",
      "tastatur", "musemåtte", "skærm", "printer", "scanner", "makulator", "skrivebord", "kontorstol",
      "skuffedarium", "reol", "papirkurv", "arkivskab", "brevbakke", "tidsskriftsamler", "opslagsværk", "ordbog",
      "leksikon", "atlas", "lærebog", "roman", "digtsamling", "novelle", "kopipapir", "fotopapir",
      "karton", "bølgepap", "pergamentpapir", "madpakke", "drikkedunk", "rygsæk", "skoletaske", "kridttavle",
      "blyant tryk", "stiftblyant", "stifter", "blyantsspids", "kulblyant", "pastelkridt", "oliekridt", "farvekridt",
      "akvarelblyant", "fineliner", "kalligrafipen", "gelpen", "rollerpen", "kuglepen klik", "patronpen", "blækpatron",
      "korrekturpen", "permanent tusch", "whiteboardmarker", "tekstmarker", "highlighter", "tuschpen tynd", "tuschpen bred", "skitseblok",
      "tegneblok", "akvarelpapir", "millimeterpapir", "ternet papir", "linjeret papir", "blankt papir", "notesblok lille", "kollegieblok",
      "spiralblok", "kladdeblok", "dagbog", "kalenderbog", "ugekalender", "månedskalender", "årsplan", "planlægningstavle",
      "whiteboardtavle", "flipover", "projektortavle", "laserpeger", "pegepind", "magnetstrimmel", "opslagsmagnet", "tegnestift farvet",
      "papirclips stor", "foldeclips", "brevklemme", "elastik", "gummiring", "hæftemaskine stor", "hæfteklammer", "klammefjerner",
      "hulmaskine stor", "arkivering", "ringbind bred", "ringbind smal", "chartek", "plastomslag", "lamineringslomme", "laminator",
      "makuleringsmaskine", "kopimaskine stor", "printerpatron", "toner", "papirbakke", "papirstakker", "dokumentholder", "bogstøtte kontor",
      "skrivebordsmåtte", "musemåtte gel", "håndledsstøtte", "tastaturbakke", "skærmarm", "skærmforhøjer", "laptopstander", "dokumentkamera",
      "konferencetelefon", "headset kontor", "whiteboardsvamp", "whiteboardrens", "tavlekridt", "kridtsvamp", "projektorlærred", "pointer",
      "navneskilt", "adgangskort", "kontorstol pude", "fodstøtte", "papirkurv sortering", "kaffekop kontor", "termokrus",
    ],
  },
  {
    name: "Hobbyer og Fritid",
    emoji: "🎨",
    words: [
      "fodbold", "håndbold", "svømning", "løb", "cykling", "fitness", "yoga", "gymnastik",
      "ridning", "dans", "ballet", "teater", "skuespil", "sang", "kor", "musik",
      "guitar", "klaver", "trommer", "tegning", "maling", "akvarel", "keramik", "strikning",
      "hækling", "syning", "broderi", "patchwork", "smykkefremstilling", "perler", "scrapbooking", "origami",
      "fotografering", "film", "biograf", "læsning", "bøger", "tegneserier", "forfatterskab", "digte",
      "computerspil", "brætspil", "kortspil", "rollespil", "skak", "puslespil", "modelbygning", "lego",
      "samlekort", "frimærker", "mønter", "antikviteter", "loppemarked", "geocaching", "vandring", "camping",
      "fiskeri", "jagt", "ornitologi", "havearbejde", "drivhus", "blomsterbinding", "madlavning", "bagning",
      "ølbrygning", "vinbrygning", "smagning", "rejser", "sprog", "historie", "slægtsforskning", "astronomi",
      "stjernekiggeri", "dykning", "surfing", "sejlads", "skiløb", "snowboarding", "skateboarding", "rulleskøjter",
      "akrylmaling", "oliemaling", "gouache", "tegneteknik", "croquis", "kalligrafi", "håndbogstavering", "linoleumstryk",
      "serigrafi", "raderering", "træsnit", "mosaik", "glaskunst", "glasfusing", "emaljearbejde", "sølvsmedje",
      "smykkeperler", "makrame", "vævning", "spinding", "filtning", "tovværk", "kurvefletning", "træskæring",
      "drejning i træ", "møbelrestaurering", "polstring", "lædersyning", "bogbinding", "papirfoldning", "kortlavning", "stempling",
      "akvarelmaling", "digital tegning", "fotoredigering", "videoredigering", "podcastoptagelse", "lydproduktion", "sangskrivning", "beatmaking",
      "danseundervisning", "improteater", "standup", "jonglering", "tryllekunst", "kortkunster", "sæbebobler", "drageflyvning hobby",
      "modelfly", "modeltog", "modelskibe", "radiostyret bil", "drone flyvning", "robotbygning", "elektronikbygning", "programmering",
      "brætspilsklub", "rollespil live", "figurmaling", "samlekort spil", "skakklub", "backgammon", "go spil", "dam spil",
      "krydsord", "sudoku", "kryptiske gåder", "escape room", "geologi hobby", "fossiljagt", "metaldetektor", "stenslibning",
      "akvariehobby", "terrarie", "birøgt", "høns i haven", "urtehave", "altankasse", "bonsai", "kaktussamling",
      "svampejagt", "sankning", "vildtplukning", "fluebinding", "fluefiskeri", "kystfiskeri", "put and take", "bueskydning hobby",
      "vinsmagning", "ølsmagning", "kaffebrygning", "hjemmeristning", "ostelavning", "syltning", "fermentering", "røgning af mad",
    ],
  },
];
