import type { SeedPack } from "./types";

// Additional broad family categories, on top of the 20 in packs.core.ts.
// Same rules: plain common nouns, no brand names, no licensed content, and
// every pack broad enough that a host can pin it and still get variety.
//
// Lowercase throughout — the content-quality test only requires each pack to be
// internally consistent, and the core packs already differ from one another.


export const PACKS_EXTRA: SeedPack[] = [
  {
    name: "Lande og Verdensbyer",
    emoji: "🌍",
    words: [
      "norge", "sverige", "finland", "island", "tyskland", "holland", "belgien", "frankrig",
      "spanien", "portugal", "italien", "grækenland", "tyrkiet", "polen", "tjekkiet", "slovakiet",
      "ungarn", "østrig", "schweiz", "slovenien", "kroatien", "serbien", "bulgarien", "rumænien",
      "ukraine", "letland", "litauen", "estland", "irland", "skotland", "wales", "england",
      "marokko", "egypten", "tunesien", "kenya", "tanzania", "sydafrika", "nigeria", "ghana",
      "etiopien", "indien", "pakistan", "nepal", "kina", "japan", "sydkorea", "vietnam",
      "thailand", "cambodja", "laos", "malaysia", "indonesien", "filippinerne", "singapore", "australien",
      "new zealand", "canada", "mexico", "cuba", "jamaica", "brasilien", "argentina", "chile",
      "peru", "colombia", "bolivia", "uruguay", "paraguay", "ecuador", "oslo", "stockholm",
      "helsinki", "reykjavik", "berlin", "hamborg", "münchen", "amsterdam", "rotterdam", "bruxelles",
      "paris", "lyon", "marseille", "madrid", "barcelona", "sevilla", "lissabon", "porto",
      "rom", "milano", "venedig", "firenze", "napoli", "athen", "istanbul", "ankara",
      "warszawa", "krakow", "prag", "budapest", "wien", "salzburg", "zürich", "genève",
      "ljubljana", "zagreb", "beograd", "sofia", "bukarest", "kiev", "riga", "vilnius",
      "tallinn", "dublin", "edinburgh", "london", "manchester", "liverpool", "glasgow", "cardiff",
      "marrakesh", "kairo", "nairobi", "cape town", "lagos", "mumbai", "delhi", "beijing",
      "shanghai", "tokyo", "kyoto", "seoul", "hanoi", "bangkok", "kuala lumpur", "jakarta",
      "manila", "sydney", "melbourne", "auckland", "toronto", "vancouver", "montreal", "mexico city",
      "havana", "rio de janeiro", "sao paulo", "buenos aires", "santiago", "lima",
    ],
  },
  {
    name: "Fester og Højtider",
    emoji: "🎉",
    words: [
      "fødselsdag", "navnedag", "bryllup", "sølvbryllup", "guldbryllup", "forlovelse", "polterabend", "babyshower",
      "barnedåb", "navngivning", "konfirmation", "nonfirmation", "studenterfest", "dimission", "jubilæum", "firmafest",
      "sommerfest", "julefrokost", "nytårsfest", "karneval", "maskebal", "halloween", "fastelavn", "påske",
      "pinse", "jul", "juleaften", "nytårsaften", "helligtrekonger", "mortensaften", "sankthans", "valborgsaften",
      "høstfest", "byfest", "gadefest", "havefest", "grillfest", "temafest", "kostumefest", "overraskelsesfest",
      "afskedsfest", "velkomstfest", "indflytterfest", "husvarmefest", "reception", "banket", "gallamiddag", "festmiddag",
      "brunch", "frokostselskab", "kaffebord", "kagebord", "buffet", "taffel", "skål", "tale",
      "festsang", "hurraråb", "lagkage", "konfetti", "serpentiner", "balloner", "guirlande", "flagstang",
      "bordflag", "borddækning", "dug", "servietter", "bordkort", "navneskilte", "menukort", "blomsterdekoration",
      "lysestager", "festbelysning", "lyskæder", "discokugle", "højttalere", "dansegulv", "scene", "mikrofon",
      "festtelt", "pavillon", "langbord", "buffetbord", "barområde", "garderobe", "gæsteliste", "invitation",
      "indbydelse", "gavebord", "gaveindpakning", "gavekort", "blomsterbuket", "chokoladeæske", "vinflaske", "champagne",
      "skumvin", "festmusik", "orkester", "dj", "fællessang", "sanglege", "konkurrencer", "toastmaster",
      "festudvalg", "oprydning", "efterfest", "natmad", "pølsevogn", "kagebuffet", "slikbord", "bar",
      "cocktailbar", "isbar", "kaffebar", "morgenkaffe", "festtale", "bordplan", "velkomstdrink", "skåltale",
      "brudevals", "kagebord dessert", "festligt lys", "stemningslys", "borddekoration", "festhat", "festfløjte", "stjernekastere",
      "fyrværkeri",
    ],
  },
  {
    name: "Ferie og Rejser",
    emoji: "🧳",
    words: [
      "kuffert", "håndbagage", "rygsæk", "rejsetaske", "weekendtaske", "toilettaske", "pas", "visum",
      "billet", "boardingkort", "rejseforsikring", "valuta", "vekselkontor", "kreditkort", "rejseguide", "kort",
      "rejseplan", "rejsebureau", "charterrejse", "pakkerejse", "rundrejse", "storbyferie", "strandferie", "skiferie",
      "vandreferie", "cykelferie", "campingferie", "sommerhusferie", "krydstogt", "lufthavn", "terminal", "gate",
      "sikkerhedskontrol", "bagagebånd", "told", "ankomst", "afgang", "forsinkelse", "mellemlanding", "vinduesplads",
      "midterplads", "gangplads", "redningsvest", "nødudgang", "kabinepersonale", "pilot", "kaptajn", "luftpude",
      "hotel", "vandrerhjem", "hostel", "pensionat", "feriehus", "ferielejlighed", "campingplads", "telt",
      "campingvogn", "autocamper", "resort", "alt inklusive", "halvpension", "morgenbuffet", "reception", "roomservice",
      "minibar", "hotelværelse", "dobbeltværelse", "enkeltværelse", "udsigt", "altan", "terrasse", "pool",
      "solseng", "parasol", "badehåndklæde", "solcreme", "solbriller", "sommerhat", "snorkel", "dykkermaske",
      "svømmefødder", "badering", "luftmadras", "badebold", "sandslot", "muslingeskal", "strandtaske", "køletaske",
      "seværdighed", "museum", "monument", "udsigtspunkt", "udkigstårn", "gamle bydel", "torv", "markedsplads",
      "souvenirbutik", "postkort", "guidet tur", "byrundtur", "bådtur", "vandretur", "bjergtur", "safaritur",
      "vinsmagning", "madtur", "festival", "koncertrejse", "jetlag", "tidszone", "rejsesyge", "køresyge",
      "rejsemedicin", "oplader", "adapter", "powerbank", "rejsepude", "øjenmaske", "ørepropper", "rejsedagbog",
      "lufthavnstog", "transferbus", "lejebil", "benzinkort", "vejafgift", "færgebillet", "togpass", "vandrestøvler",
      "regnslag", "solskærm",
    ],
  },
  {
    name: "Følelser og Sindsstemninger",
    emoji: "😊",
    words: [
      "glæde", "lykke", "fryd", "begejstring", "jubel", "henrykkelse", "tilfredshed", "ro",
      "fred", "tryghed", "lettelse", "taknemmelighed", "stolthed", "håb", "optimisme", "forventning",
      "spænding", "nysgerrighed", "undren", "forbløffelse", "overraskelse", "chok", "forskrækkelse", "frygt",
      "angst", "panik", "uro", "nervøsitet", "bekymring", "stress", "pres", "træthed",
      "udmattelse", "sløvhed", "kedsomhed", "ligegyldighed", "tomhed", "tristhed", "sorg", "savn",
      "længsel", "vemod", "melankoli", "skuffelse", "skam", "skyld", "anger", "fortrydelse",
      "forlegenhed", "generthed", "usikkerhed", "tvivl", "forvirring", "frustration", "irritation", "utålmodighed",
      "vrede", "raseri", "harme", "bitterhed", "jalousi", "misundelse", "mistillid", "mistro",
      "foragt", "afsky", "væmmelse", "modvilje", "ensomhed", "isolation", "forladthed", "sårbarhed",
      "ømhed", "kærlighed", "forelskelse", "hengivenhed", "omsorg", "medfølelse", "empati", "sympati",
      "venlighed", "varme", "tillid", "respekt", "beundring", "inspiration", "motivation", "drivkraft",
      "mod", "tapperhed", "selvtillid", "selvværd", "ydmyghed", "beskedenhed", "munterhed", "humor",
      "latter", "smil", "gråd", "suk", "sult", "mæthed", "tørst", "kulde",
      "gåsehud", "hjertebanken", "klump i halsen", "tunge skuldre", "lettet ånde", "adrenalin", "energi", "flow",
      "koncentration", "fokus", "distraktion", "rastløshed", "hvile", "døsighed", "opstemthed", "forventningsglæde",
      "hjemve", "nostalgi", "trods", "stædighed", "tryghedsfølelse", "samhørighed", "fremmedhed", "forundring",
      "ærefrygt", "taknemmelig ro",
    ],
  },
  {
    name: "Rummet og Planeter",
    emoji: "🪐",
    words: [
      "sol", "måne", "jorden", "merkur", "venus", "mars", "jupiter", "saturn",
      "uranus", "neptun", "pluto", "dværgplanet", "asteroide", "komet", "meteor", "meteorit",
      "stjerneskud", "stjerne", "dobbeltstjerne", "kæmpestjerne", "dværgstjerne", "rød kæmpe", "hvid dværg", "neutronstjerne",
      "pulsar", "sort hul", "supernova", "nova", "nebulose", "stjernetåge", "galakse", "mælkevejen",
      "andromeda", "stjernehob", "stjernebillede", "karlsvognen", "orion", "cassiopeia", "polarstjernen", "nordstjernen",
      "zodiak", "bane", "kredsløb", "omløbstid", "rotation", "akse", "tyngdekraft", "vægtløshed",
      "tidevandskraft", "lysår", "parsec", "rumtid", "universet", "big bang", "mørkt stof", "mørk energi",
      "baggrundsstråling", "ekspansion", "teleskop", "rumteleskop", "radioteleskop", "observatorium", "planetarium", "kikkert",
      "linse", "spejlteleskop", "stjernekort", "himmelglobus", "raket", "bæreraket", "rumkapsel", "rumfærge",
      "rumstation", "satellit", "sonde", "landingsfartøj", "månebil", "rover", "astronaut", "kosmonaut",
      "rumdragt", "hjelm", "ilttank", "rumvandring", "opsendelse", "nedstyrtning", "landing", "tilbagevenden",
      "kontrolcenter", "nedtælling", "solvind", "solplet", "solstorm", "solformørkelse", "måneformørkelse", "fuldmåne",
      "nymåne", "halvmåne", "månefase", "krater", "månestøv", "marsstøv", "polkalot", "ringsystem",
      "atmosfære", "drivhuseffekt", "iskappe", "gasplanet", "klippeplanet", "exoplanet", "beboelig zone", "rumaffald",
      "mikrometeorit", "stjernestøv", "kosmisk stråling", "tyngdebølge", "lyshastighed", "rumsonde", "månelanding", "marslanding",
      "stjernetegn", "himmelkugle", "ækvatorplan", "ellipsebane", "perihel", "aphel", "meteorsværm", "ildkugle",
      "halefænomen", "kometkerne",
    ],
  },
  {
    name: "Havet og Stranden",
    emoji: "🌊",
    words: [
      "hav", "ocean", "bølge", "brænding", "dønning", "skum", "strømhvirvel", "understrøm",
      "tidevand", "højvande", "lavvande", "ebbe", "revle", "sandbanke", "sandstrand", "stenstrand",
      "klippekyst", "klint", "klit", "marehalm", "strandeng", "lagune", "bugt", "vig",
      "fjord", "sund", "bælte", "stræde", "rev", "koralrev", "skær", "holm",
      "ø", "halvø", "tange", "odde", "næs", "pynt", "mole", "bølgebryder",
      "høfde", "kaj", "havn", "lystbådehavn", "bådebro", "badebro", "badehus", "strandhus",
      "fyrtårn", "sømærke", "bøje", "ankerplads", "anker", "tovværk", "fortøjning", "redningskrans",
      "redningsvest", "livline", "badevagt", "livredder", "badeflag", "badezone", "vandrutsjebane", "strandbar",
      "iskiosk", "strandkurv", "liggestol", "parasol", "strandhåndklæde", "solcreme", "solhat", "badedragt",
      "badebukser", "badering", "luftmadras", "snorkel", "dykkermaske", "svømmefødder", "våddragt", "surfbræt",
      "paddleboard", "kajak", "kano", "jolle", "gummibåd", "sejlbåd", "motorbåd", "sand",
      "skaller", "muslingeskal", "konkylie", "søsten", "rav", "drivtømmer", "tang", "blæretang",
      "ålegræs", "søstjerne", "søpindsvin", "krabbe", "reje", "hummer", "musling", "østers",
      "blæksprutte", "vandmand", "brandmand", "marsvin", "sæl", "delfin", "hval", "haj",
      "torsk", "sild", "makrel", "fladfisk", "ålekvabbe", "hornfisk", "sandorm", "strandsten",
      "måge", "terne", "ryle", "klyde", "skarv fugl", "edderfugl", "havørn", "sandskrivning",
      "sandtang", "skaldyrsskal",
    ],
  },
  {
    name: "Eventyr og Fantasi",
    emoji: "🐉",
    words: [
      "drage", "enhjørning", "griffon", "kentaur", "havfrue", "havmand", "nisse", "trold",
      "kæmpe", "dværg", "elver", "alf", "fe", "ånd", "dæmon", "engel",
      "spøgelse", "genfærd", "genganger", "varulv", "vampyr", "zombie", "mumie", "heks",
      "troldmand", "tryllekunstner", "spåkone", "konge", "dronning", "prins", "prinsesse", "ridder",
      "væbner", "hofnar", "hofdame", "kansler", "rådgiver", "borg", "slot", "tårn",
      "fangehul", "voldgrav", "vindebro", "tronsal", "riddersal", "skatkammer", "hemmelig gang", "sværd",
      "skjold", "rustning", "hjelm", "lanse", "stridsøkse", "bue", "pilekogger", "armbrøst",
      "dolk", "tryllestav", "tryllebog", "trylledrik", "eliksir", "amulet", "talisman", "ring",
      "krystalkugle", "magisk spejl", "lampe", "forbandelse", "forhekselse", "besværgelse", "formular", "magi",
      "trylleformular", "portal", "tidsrejse", "usynlighed", "forvandling", "mørk skov", "hule", "labyrint",
      "ødemark", "sump", "ildbjerg", "isslot", "skyland", "undervandsrige", "underjordisk by", "skattekiste",
      "guldmønt", "ædelsten", "rubin", "safir", "smaragd", "diamant", "perle", "krone",
      "scepter", "profeti", "gåde", "prøvelse", "rejse", "helt", "skurk", "følgesvend",
      "mentor", "forræder", "ulveflok", "kæmpeørn", "flyvende tæppe", "talende dyr", "forhekset træ", "levende statue",
      "skyggevæsen", "ildånde", "frostkæmpe", "stengolem", "alfeland", "troldmandstårn", "drageæg", "kappe",
      "runesten", "oldgammel bog", "seglring", "hemmelig dør", "magisk kilde", "ønskebrønd", "guldnøgle", "sølvpil",
      "månesten", "soltempel",
    ],
  },
  {
    name: "Butikker og Indkøb",
    emoji: "🛒",
    words: [
      "supermarked", "discountbutik", "købmand", "kiosk", "bager", "slagter", "fiskehandler", "grønthandler",
      "ostehandler", "vinhandel", "bageri", "konditori", "delikatesse", "helsekost", "apotek", "materialist",
      "parfumeri", "blomsterbutik", "havecenter", "tøjbutik", "skobutik", "sportsbutik", "legetøjsbutik", "boghandel",
      "papirhandel", "musikbutik", "elektronikbutik", "telefonbutik", "computerbutik", "møbelbutik", "boligbutik", "isenkræmmer",
      "byggemarked", "malerbutik", "dyrehandel", "cykelhandler", "bilforhandler", "autoværksted", "dækcenter", "guldsmed",
      "urmager", "optiker", "frisør", "barber", "negleklinik", "solcenter", "renseri", "skomager",
      "nøgleservice", "genbrugsbutik", "loppemarked", "antikvitetsbutik", "auktionshus", "gårdbutik", "torvehandel", "markedsbod",
      "madvogn", "isbod", "indkøbscenter", "gågade", "strøg", "storcenter", "butiksgade", "torv",
      "marked", "netbutik", "webshop", "postordre", "indkøbsvogn", "indkøbskurv", "indkøbsnet", "papirspose",
      "plastikpose", "stofpose", "kasse", "båndkasse", "selvbetjening", "scanner", "stregkode", "prisskilt",
      "tilbudsskilt", "udsalg", "rabat", "tilbud", "kupon", "kundekort", "bonus", "point",
      "kvittering", "bon", "returret", "bytte", "reklamation", "garanti", "faktura", "betaling",
      "kontant", "kort", "mobilbetaling", "kontaktløs", "pinkode", "kasseapparat", "pengeskuffe", "byttepenge",
      "drikkepenge", "ekspedient", "kassemedarbejder", "butikschef", "lagermedarbejder", "varemodtagelse", "hylde", "reol",
      "køledisk", "frostdisk", "prøverum", "spejl", "kø", "vareprøve", "smagsprøve", "poselukker",
      "vindueskig", "skiltning", "åbningstid", "lukketid", "pakkeshop", "afhentning", "levering", "fragt",
      "returlabel", "indkøbsseddel",
    ],
  },
  {
    name: "Penge og Økonomi",
    emoji: "💰",
    words: [
      "mønt", "seddel", "kontanter", "valuta", "krone", "øre", "euro", "dollar",
      "pund", "yen", "bankkonto", "lønkonto", "budgetkonto", "opsparingskonto", "børneopsparing", "pensionsopsparing",
      "aldersopsparing", "ratepension", "livrente", "kapitalpension", "lån", "boliglån", "billån", "forbrugslån",
      "studielån", "kassekredit", "overtræk", "afdrag", "rente", "rentesats", "gæld", "kreditor",
      "debitor", "restgæld", "gældsbrev", "kaution", "pant", "sikkerhed", "tinglysning", "ejerpantebrev",
      "budget", "regnskab", "bogføring", "bilag", "kvittering", "faktura", "betalingsservice", "girokort",
      "overførsel", "straksoverførsel", "løn", "timeløn", "månedsløn", "bonus", "provision", "feriepenge",
      "fritvalgskonto", "pensionsbidrag", "arbejdsgiverbidrag", "lønseddel", "skat", "indkomstskat", "kildeskat", "trækprocent",
      "fradrag", "personfradrag", "befordringsfradrag", "årsopgørelse", "forskudsopgørelse", "restskat", "moms", "afgift",
      "told", "gebyr", "rykkergebyr", "kontingent", "abonnement", "husleje", "depositum", "forudbetaling",
      "aktie", "obligation", "investering", "indeksfond", "udbytte", "kursgevinst", "kurstab", "portefølje",
      "risikospredning", "afkast", "inflation", "deflation", "konjunktur", "lavkonjunktur", "højkonjunktur", "arbejdsløshed",
      "beskæftigelse", "nationalprodukt", "statsbudget", "statsgæld", "forsikring", "indboforsikring", "ulykkesforsikring", "rejseforsikring",
      "bilforsikring", "husforsikring", "selvrisiko", "præmie", "erstatning", "police", "sparegris", "lommepenge",
      "opsparing", "nødopsparing", "formue", "arv", "gave", "veksling", "kurs", "valutakurs",
      "kontoudtog", "saldo", "hævekort", "betalingskort", "netbank", "mobilbank", "bankrådgiver", "kassekvittering",
      "budgetskema", "sparemål",
    ],
  },
  {
    name: "Sundhed og Sygdom",
    emoji: "🩹",
    words: [
      "forkølelse", "influenza", "feber", "hoste", "snue", "halsbetændelse", "ørebetændelse", "bihulebetændelse",
      "lungebetændelse", "bronkitis", "astma", "allergi", "høfeber", "eksem", "nældefeber", "udslæt",
      "skoldkopper", "mæslinger", "fåresyge", "røde hunde", "mavepine", "kvalme", "opkast", "diarre",
      "forstoppelse", "halsbrand", "madforgiftning", "mavesår", "betændelse", "hovedpine", "migræne", "svimmelhed",
      "træthed", "søvnløshed", "stress", "angst", "depression", "udbrændthed", "nedtrykthed", "brækket arm",
      "forstuvning", "forstrækning", "muskelknude", "senebetændelse", "slidgigt", "leddegigt", "diskusprolaps", "hekseskud",
      "iskias", "sår", "skrammer", "blå mærke", "forbrænding", "forfrysning", "snitsår", "hudafskrabning",
      "vabel", "ar", "plaster", "forbinding", "gaze", "elastikbind", "sårrens", "desinfektion",
      "salve", "creme", "gel", "tablet", "kapsel", "pille", "mikstur", "dråber",
      "næsespray", "inhalator", "injektion", "vaccine", "penicillin", "smertestillende", "febernedsættende", "hostesaft",
      "halstabletter", "næsedråber", "øjendråber", "kølende gel", "varmepude", "ispose", "læge", "praktiserende læge",
      "speciallæge", "vagtlæge", "sygeplejerske", "jordemoder", "fysioterapeut", "kiropraktor", "psykolog", "diætist",
      "konsultation", "undersøgelse", "blodprøve", "urinprøve", "podning", "røntgen", "scanning", "ultralyd",
      "operation", "recept", "henvisning", "sygesikringsbevis", "journal", "diagnose", "behandling", "genoptræning",
      "forebyggelse", "motion", "kost", "søvn", "hvile", "karantæne", "sygemelding", "raskmelding",
      "venteværelse", "tidsbestilling", "skadestue", "ambulance", "hospitalsseng", "drop", "gipsbandage", "krykke",
      "kørestol", "høreprøve",
    ],
  },
  {
    name: "Materialer og Stoffer",
    emoji: "🧱",
    words: [
      "træ", "eg", "bøg", "fyr", "gran", "birk", "ask", "ahorn",
      "teak", "mahogni", "bambus", "kork", "finér", "krydsfiner", "spånplade", "mdf",
      "limtræ", "hårdttræ", "blødttræ", "jern", "stål", "rustfrit stål", "støbejern", "aluminium",
      "kobber", "messing", "bronze", "zink", "tin", "bly", "nikkel", "titanium",
      "krom", "sølv", "guld", "platin", "wolfram", "magnesium", "legering", "sten",
      "granit", "marmor", "skifer", "sandsten", "kalksten", "flint", "basalt", "travertin",
      "brosten", "beton", "cement", "mørtel", "gips", "puds", "kalk", "tegl",
      "mursten", "klinke", "fliser", "terrazzo", "asfalt", "grus", "sand", "ler",
      "jord", "tørv", "mudder", "kridt", "glas", "spejlglas", "hærdet glas", "laminatglas",
      "krystal", "porcelæn", "keramik", "stentøj", "fajance", "lertøj", "plastik", "polyester",
      "nylon", "akryl", "pvc", "polystyren", "silikone", "gummi", "latex", "skum",
      "tekstil", "bomuld", "uld", "silke", "hør", "jute", "hamp", "viskose",
      "fleece", "filt", "læder", "ruskind", "imiteret læder", "pels", "dun", "fjer",
      "garn", "tråd", "snor", "reb", "papir", "pap", "karton", "bølgepap",
      "pergament", "papmaché", "voks", "harpiks", "lim", "lak", "emalje", "maling",
      "glasuld", "stenuld", "isolering", "tagpap", "linoleum", "vinyl", "laminat", "parket",
      "marmorplade", "kompositmateriale",
    ],
  },
  {
    name: "Vejr og Årstider",
    emoji: "⛅",
    words: [
      "solskin", "solstråler", "skygge", "klart vejr", "skyfrit", "halvskyet", "overskyet", "gråvejr",
      "dis", "tåge", "tågebanke", "morgentåge", "regn", "støvregn", "silende regn", "skybrud",
      "byge", "regnbyge", "tordenbyge", "hagl", "slud", "sne", "snefnug", "snebyge",
      "snestorm", "snefog", "snedrive", "snedække", "isslag", "frost", "rimfrost", "nattefrost",
      "tøvejr", "tø", "glatføre", "dug", "morgendug", "fugt", "vind", "brise",
      "kuling", "storm", "orkan", "stormflod", "vindstød", "vindstille", "medvind", "modvind",
      "lyn", "torden", "tordenvejr", "tordenskrald", "lynnedslag", "regnbue", "halo", "solnedgang",
      "solopgang", "tusmørke", "daggry", "skumring", "aftenrøde", "morgenrøde", "nordlys", "hedebølge",
      "varmerekord", "kulderekord", "temperatur", "frostgrader", "luftfugtighed", "lufttryk", "højtryk", "lavtryk",
      "front", "koldfront", "varmfront", "vejrudsigt", "vejrstation", "barometer", "termometer", "vindmåler",
      "regnmåler", "satellitbillede", "vejrkort", "varsel", "uvejrsvarsel", "kuldevarsel", "forår", "tidligt forår",
      "sen sommer", "sommer", "højsommer", "efterår", "sen efterår", "vinter", "midvinter", "jævndøgn",
      "solhverv", "sommersolhverv", "vintersolhverv", "skudår", "årstid", "sæson", "klima", "klimazone",
      "tempereret", "subtropisk", "tropisk", "arktisk", "ørkenklima", "kystklima", "indlandsklima", "mikroklima",
      "drivhuseffekt", "blæsevejr", "solskinstime", "regnvejrsdag", "snevejrsdag", "frostvejr", "sommervarme", "vinterkulde",
      "skydække", "cirrusskyer", "cumulusskyer", "tordensky", "regnfrakke", "paraply", "gummistøvler", "solhat sommer",
      "skisæson", "badesæson",
    ],
  },
  {
    name: "Haven og Planter",
    emoji: "🌱",
    words: [
      "have", "forhave", "baghave", "køkkenhave", "urtehave", "prydhave", "staudebed", "blomsterbed",
      "højbed", "drivbænk", "drivhus", "orangeri", "væksthus", "planteskole", "kolonihave", "altankasse",
      "urtepotte", "krukke", "plantekasse", "hængepotte", "græsplæne", "plæneklipper", "buskrydder", "hækkeklipper",
      "havesaks", "beskæresaks", "grensaks", "spade", "skovl", "greb", "rive", "hakke",
      "lugejern", "plantespade", "vandkande", "haveslange", "vandingssystem", "sprinkler", "regnvandstønde", "kompostbeholder",
      "kompost", "muld", "plantejord", "spagnum", "gødning", "kalk", "ukrudt", "ukrudtsdug",
      "barkflis", "havegrus", "frø", "frøpose", "stikling", "aflægger", "knold", "blomsterløg",
      "rodklump", "podning", "spirekasse", "drivhusbord", "rose", "tulipan", "påskelilje", "erantis",
      "vintergæk", "krokus", "hyacint", "anemone", "valmue", "solsikke", "margerit", "lavendel",
      "salvie", "mynte", "rosmarin", "timian", "purløg", "persille", "dild", "basilikum",
      "hortensia", "syren", "jasmin", "klematis", "vedbend", "vildvin", "rododendron", "azalea",
      "magnolia", "kirsebærtræ", "æbletræ", "pæretræ", "blommetræ", "valnøddetræ", "hasselbusk", "ribsbusk",
      "solbærbusk", "stikkelsbærbusk", "hindbærbusk", "jordbærplante", "hæk", "ligusterhæk", "bøgehæk", "thuja",
      "buksbom", "espalier", "pergola", "terrasse", "havegang", "trædesten", "havemøbler", "hammock",
      "bålfad", "havegrill", "fuglebad", "fuglehus", "insekthotel", "havedam", "springvand", "havelys",
      "bregnebed", "stenbed", "grusbed", "blomsterkasse", "potteskjuler", "plantekrukke", "opbindingspind", "plantenet",
      "drivhusrude", "havehandsker",
    ],
  },
  {
    name: "Bondegården",
    emoji: "🚜",
    words: [
      "gård", "gårdsplads", "stuehus", "staldbygning", "kostald", "svinestald", "hestestald", "fårefold",
      "hønsehus", "andehus", "lade", "høloft", "foderlade", "maskinhus", "værksted", "silo",
      "kornsilo", "gylletank", "mødding", "vandtrug", "mark", "ager", "brakmark", "græsmark",
      "kornmark", "majsmark", "rapsmark", "kartoffelmark", "roemark", "engdrag", "hegn", "elhegn",
      "pigtråd", "ledsted", "markvej", "grøft", "dræn", "læhegn", "markskel", "jordvold",
      "traktor", "plov", "harve", "såmaskine", "gødningsspreder", "marksprøjte", "mejetærsker", "halmpresser",
      "ballevogn", "gyllevogn", "frontlæsser", "teleskoplæsser", "minilæsser", "rendegraver", "tipvogn", "foderblander",
      "malkemaskine", "malkerobot", "klovbeskærer", "kreaturvogn", "ko", "kalv", "tyr", "kvie",
      "malkeko", "ammeko", "gris", "so", "orne", "pattegris", "får", "vædder",
      "lam", "ged", "gedebuk", "kid", "hest", "hoppe", "hingst", "føl",
      "høne", "hane", "kylling", "and", "gås", "kalkun", "perlehøne", "gårdkanin",
      "ladekat", "gårdhund", "hø", "halm", "ensilage", "wrapballe", "kraftfoder", "korn",
      "hvede", "byg", "rug", "havre", "majs", "raps", "kartofler", "roer",
      "markærter", "kløver", "græs", "lucerne", "frøgræs", "efterafgrøde", "høst", "såning",
      "pløjning", "harvning", "gødskning", "sprøjtning", "malkning", "foderrunde", "udmugning", "dyrlægebesøg",
      "mælkespand", "foderskovl", "greb til møg", "træsko gård", "kalvehytte", "hønsegård", "æggebakke", "mælketank",
      "halmballe", "kornlager",
    ],
  },
];
