import type { QuestionPair } from "./types";

// "Krydret indhold" — the adult-leaning Spørgsmål pool. Opt-in via the host's
// settings toggle; never drawn unless someone explicitly turned it on.
//
// Same authoring rules as the family pool, and they matter more here: the
// answer must still be ONE WORD, crew and imposter must demand the same TYPE of
// answer, and every question must stand alone — a player only ever sees their
// own side, so a question that leans on its partner is unanswerable.
//
// Register: blunt and suggestive, never crude or clinical. Nothing targets a
// real person, and nothing assumes anyone's relationship status, orientation,
// or gender.

export const QUESTIONS_PARTY: QuestionPair[] = [
  // ——— Fest, druk og nattelivet ———
  { crew: "Hvad drikker du, når du vil holde den kørende hele natten?", imposter: "Hvad drikker du, når du bare skal slappe af?" },
  { crew: "Hvad er den værste drink, du har smagt?", imposter: "Hvad er den drink, du altid fortryder?" },
  { crew: "Hvor mange genstande er din grænse?", imposter: "Hvor mange timer varer en god bytur for dig?" },
  { crew: "Hvad spiser du på vej hjem fra byen?", imposter: "Hvad spiser du, når du kommer sultet hjem?" },
  { crew: "Hvad er det dummeste, du har gjort i fuldskab?", imposter: "Hvad er det sjoveste, du har gjort til en fest?" },
  { crew: "Hvilken sang får dig altid på dansegulvet?", imposter: "Hvilken sang synger du altid til karaoke?" },
  { crew: "Hvad mistede du sidst på en bytur?", imposter: "Hvad har du efterladt hos en fremmed?" },
  { crew: "Hvor mange gange er du kommet hjem efter solopgang?", imposter: "Hvor mange gange er du taget direkte på arbejde efter en fest?" },
  { crew: "Hvad er din bedste kur mod tømmermænd?", imposter: "Hvad er din bedste undskyldning for en fridag?" },
  { crew: "Hvem i gruppen bliver først fuld?", imposter: "Hvem i gruppen holder længst ud?" },
  { crew: "Hvem i gruppen ville starte en efterfest?", imposter: "Hvem i gruppen forsvinder først hjem?" },
  { crew: "Hvem i gruppen ville sige ja til en shot lige nu?", imposter: "Hvem i gruppen ville bestille en vand i stedet?" },
  { crew: "Hvad er det seneste tidspunkt, du er kommet hjem?", imposter: "Hvad er det tidligste, du har forladt en fest?" },
  { crew: "Hvor mange gange har du sunget karaoke offentligt?", imposter: "Hvor mange gange har du danset på et bord?" },
  { crew: "Hvad er den mest pinlige besked, du har sendt i fuldskab?", imposter: "Hvad er det mærkeligste, du har købt sent om natten?" },
  { crew: "Hvilket sted ender jeres bytur altid?", imposter: "Hvilket sted starter I altid?" },
  { crew: "Hvem i gruppen ville tabe et drukspil først?", imposter: "Hvem i gruppen snyder mest i et spil?" },
  { crew: "Hvor mange gange har du lovet dig selv aldrig igen?", imposter: "Hvor mange gange har du brudt det løfte samme måned?" },
  { crew: "Hvad tager du altid med i byen?", imposter: "Hvad glemmer du altid derhjemme?" },
  { crew: "Hvem i gruppen ville komme i klammeri i en kø?", imposter: "Hvem i gruppen ville tale sig ud af alt?" },

  // ——— Dating, flirt og forhold ———
  { crew: "Hvad er din bedste åbningsreplik?", imposter: "Hvad er den værste replik, du har fået?" },
  { crew: "Hvad er dit største red flag?", imposter: "Hvad er dit bedste salgsargument?" },
  { crew: "Hvad lægger du først mærke til hos en, du er tiltrukket af?", imposter: "Hvad får dig hurtigst til at miste interessen?" },
  { crew: "Hvor gammel var du ved dit første kys?", imposter: "Hvor gammel var du, da du første gang blev forelsket?" },
  { crew: "Hvor mange dates har du været på i år?", imposter: "Hvor mange samtaler er gået i sig selv?" },
  { crew: "Hvad er det værste sted at tage på en første date?", imposter: "Hvad er det bedste sted at tage på en første date?" },
  { crew: "Hvad ville få dig til at gå midt i en date?", imposter: "Hvad ville få dig til at blive resten af aftenen?" },
  { crew: "Hvad er den mest pinlige date, du har været på?", imposter: "Hvad er den bedste date, du har været på?" },
  { crew: "Hvor mange gange har du fortrudt en sms til en eks?", imposter: "Hvor mange gange har du slettet et nummer og fortrudt?" },
  { crew: "Hvad er det sødeste, nogen har gjort for dig?", imposter: "Hvad er det sødeste, du har gjort for en anden?" },
  { crew: "Hvem i gruppen ville flirte med en servitrice?", imposter: "Hvem i gruppen ville blive rød i hovedet af et kompliment?" },
  { crew: "Hvem i gruppen ville tage første skridt?", imposter: "Hvem i gruppen ville vente for evigt?" },
  { crew: "Hvem i gruppen ville date en kollega?", imposter: "Hvem i gruppen holder arbejde og privatliv adskilt?" },
  { crew: "Hvad er det vigtigste hos en partner?", imposter: "Hvad kan du slet ikke leve med?" },
  { crew: "Hvad kalder du din kæreste eller ville kalde en?", imposter: "Hvad ville du hade at blive kaldt?" },
  { crew: "Hvor mange forhold har du haft, der varede over et år?", imposter: "Hvor mange gange er du blevet forelsket for alvor?" },
  { crew: "Hvad er den bedste undskyldning for at aflyse en date?", imposter: "Hvad er den mest gennemskuelige løgn, du har brugt?" },
  { crew: "Hvilken egenskab tiltrækker dig mest?", imposter: "Hvilken egenskab skræmmer dig væk?" },
  { crew: "Hvad gør du, hvis du ser din eks i byen?", imposter: "Hvad gør du, hvis nogen flirter med dig foran andre?" },
  { crew: "Hvem i gruppen ville sige jeg elsker dig først?", imposter: "Hvem i gruppen ville vente længst med at sige det?" },

  // ——— Pinlige indrømmelser ———
  { crew: "Hvad er det mest pinlige, der er sket dig offentligt?", imposter: "Hvad er det mest pinlige, du har gjort på arbejdet?" },
  { crew: "Hvad har du løjet om for at slippe ud af noget?", imposter: "Hvad har du løjet om for at komme med til noget?" },
  { crew: "Hvad har du gjort, som du aldrig har fortalt nogen?", imposter: "Hvad har du fortalt en enkelt person og fortrudt?" },
  { crew: "Hvor mange gange har du meldt dig syg uden at være det?", imposter: "Hvor mange gange er du kommet for sent uden en grund?" },
  { crew: "Hvad har du taget med hjem, som ikke var dit?", imposter: "Hvad har du beholdt, som du burde have afleveret?" },
  { crew: "Hvad er det værste, du har sagt om en ven?", imposter: "Hvad er det pæneste, du har sagt for at slippe udenom?" },
  { crew: "Hvad ville du slette først fra din browserhistorik?", imposter: "Hvad ville du slette først fra dine beskeder?" },
  { crew: "Hvad er det mærkeligste, du har gjort alene hjemme?", imposter: "Hvad gør du, som du aldrig ville gøre foran andre?" },
  { crew: "Hvem i gruppen har den vildeste fortid?", imposter: "Hvem i gruppen virker mest uskyldig?" },
  { crew: "Hvem i gruppen ville aldrig kunne holde på en hemmelighed?", imposter: "Hvem i gruppen ved mest om alle andre?" },
  { crew: "Hvad har du gjort for at undgå at møde nogen?", imposter: "Hvad har du fundet på for at slippe ud af en samtale?" },
  { crew: "Hvor mange gange har du ladet som om du kendte nogen?", imposter: "Hvor mange gange har du glemt en persons navn midt i en snak?" },
  { crew: "Hvad var din vildeste fase som teenager?", imposter: "Hvad var din mest pinlige frisure?" },
  { crew: "Hvad er det dyreste, du har fortrudt at købe?", imposter: "Hvad har du købt i fuldskab?" },
  { crew: "Hvem i gruppen ville blive taget i en løgn først?", imposter: "Hvem i gruppen lyver mest overbevisende?" },
  { crew: "Hvad snød du med i skolen?", imposter: "Hvad slap du afsted med derhjemme?" },
  { crew: "Hvad ville komme frem, hvis nogen læste din telefon?", imposter: "Hvad ville overraske folk mest ved dit søgefelt?" },
  { crew: "Hvor mange gange er du sneget dig ud som ung?", imposter: "Hvor mange gange blev du opdaget?" },

  // ——— Grænser, hemmeligheder og moral ———
  { crew: "Hvad ville du aldrig tilgive?", imposter: "Hvad kan du tilgive med det samme?" },
  { crew: "Hvad ville få dig til at afsløre en vens hemmelighed?", imposter: "Hvad ville få dig til at lyve for en ven?" },
  { crew: "Hvor mange hemmeligheder holder du lige nu?", imposter: "Hvor mange mennesker kender din største hemmelighed?" },
  { crew: "Hvad ville du gøre for en million?", imposter: "Hvad ville du aldrig gøre uanset beløbet?" },
  { crew: "Hvad er din største fristelse?", imposter: "Hvad har du sværest ved at sige nej til?" },
  { crew: "Hvad ville du ændre ved dig selv, hvis du kunne?", imposter: "Hvad ville du aldrig ændre?" },
  { crew: "Hvem i gruppen ville stjæle en skiltning som souvenir?", imposter: "Hvem i gruppen ville tale sig ud af en bøde?" },
  { crew: "Hvem i gruppen ville bryde reglerne først?", imposter: "Hvem i gruppen retter altid andre?" },
  { crew: "Hvad er den mest ulovlige ting, du har gjort?", imposter: "Hvad er det frækkeste, du er sluppet afsted med?" },
  { crew: "Hvad ville du gøre, hvis ingen nogensinde fik det at vide?", imposter: "Hvad gør du kun, når du er helt alene?" },
  { crew: "Hvad er du mest hemmelighedsfuld omkring?", imposter: "Hvad deler du alt for meget om?" },
  { crew: "Hvem i gruppen ville sladre først?", imposter: "Hvem i gruppen tager en hemmelighed med i graven?" },

  // ——— Krop, udseende og nærhed ———
  { crew: "Hvad er du mest usikker på ved dit udseende?", imposter: "Hvad er du mest tilfreds med ved dit udseende?" },
  { crew: "Hvor lang tid bruger du på at gøre dig klar til en date?", imposter: "Hvor lang tid bruger du foran spejlet på en normal dag?" },
  { crew: "Hvad har du overvejet at få lavet?", imposter: "Hvad ville du aldrig få lavet?" },
  { crew: "Hvor mange tatoveringer kunne du finde på at få?", imposter: "Hvor mange piercinger har du haft?" },
  { crew: "Hvad går du i, når du skal føle dig godt tilpas?", imposter: "Hvad går du i, når ingen ser dig?" },
  { crew: "Hvem i gruppen bruger længst tid på badeværelset?", imposter: "Hvem i gruppen er hurtigst klar?" },
  { crew: "Hvem i gruppen ville hoppe nøgen i havet?", imposter: "Hvem i gruppen ville blive stående på stranden?" },
  { crew: "Hvad er det mest afslørende tøj, du ejer?", imposter: "Hvad er det mest komfortable tøj, du ejer?" },
  { crew: "Hvor mange gange om ugen ser du dig selv i spejlet med vilje?", imposter: "Hvor mange selfies tager du på en måned?" },
  { crew: "Hvad ville du ændre ved din krop for en dag?", imposter: "Hvad ville du gerne kunne med din krop?" },

  // ——— Penge, arbejde og ærlighed ———
  { crew: "Hvad har du løjet om til en jobsamtale?", imposter: "Hvad har du overdrevet på dit CV?" },
  { crew: "Hvor meget skulle du have for at sige op i morgen?", imposter: "Hvor meget skulle du have for at flytte til udlandet?" },
  { crew: "Hvad bruger du penge på, som du skammer dig lidt over?", imposter: "Hvad sparer du på, som du burde bruge mere på?" },
  { crew: "Hvad er det dyreste, du har købt uden at tænke?", imposter: "Hvad er det billigste køb, der gjorde dig gladest?" },
  { crew: "Hvem i gruppen ville glemme at betale sin del?", imposter: "Hvem i gruppen betaler altid for meget?" },
  { crew: "Hvem i gruppen ville sige sin mening til chefen?", imposter: "Hvem i gruppen ville holde helt lav profil?" },
  { crew: "Hvad har du gjort på arbejdet, som du aldrig fortalte?", imposter: "Hvad har du taget med hjem fra et kontor?" },
  { crew: "Hvor mange gange har du taget en lang frokost med vilje?", imposter: "Hvor mange gange er du gået tidligt uden at sige det?" },
  { crew: "Hvad ville du gøre, hvis du fandt en tegnebog med penge i?", imposter: "Hvad ville du gøre, hvis du fik for mange penge tilbage?" },

  // ——— Gruppen, drama og dynamik ———
  { crew: "Hvem i gruppen ville starte et drama?", imposter: "Hvem i gruppen ville lægge låg på et skænderi?" },
  { crew: "Hvem i gruppen ville overleve en reality-serie længst?", imposter: "Hvem i gruppen ville blive stemt ud først?" },
  { crew: "Hvem i gruppen har flest eksser?", imposter: "Hvem i gruppen har været single længst?" },
  { crew: "Hvem i gruppen ville sende en risky besked?", imposter: "Hvem i gruppen ville slette den igen straks?" },
  { crew: "Hvem i gruppen ville tage med hjem til en fremmed?", imposter: "Hvem i gruppen ville insistere på at følge alle hjem?" },
  { crew: "Hvem i gruppen ville dele en pinlig historie om sig selv?", imposter: "Hvem i gruppen holder kortene tæt?" },
  { crew: "Hvem i gruppen ville sige noget upassende til en middag?", imposter: "Hvem i gruppen redder situationen bagefter?" },
  { crew: "Hvem i gruppen kysser flest til en fest?", imposter: "Hvem i gruppen bliver oftest inviteret ud?" },
  { crew: "Hvem i gruppen ville lyve om sin alder?", imposter: "Hvem i gruppen er mest ærlig, selv når det gør ondt?" },
  { crew: "Hvem i gruppen ville ende med at betale for alle?", imposter: "Hvem i gruppen glemmer altid sin pung?" },
  { crew: "Hvem i gruppen ville sige ja til at bytte bolig med en fremmed?", imposter: "Hvem i gruppen ville aldrig lade nogen sove i deres seng?" },
  { crew: "Hvem i gruppen ville tage på ferie helt alene?", imposter: "Hvem i gruppen kan ikke være alene en hel weekend?" },

  // ——— Blandet krydret ———
  { crew: "Hvad er den mest pinlige sang på din playliste?", imposter: "Hvad er den mest pinlige film, du elsker?" },
  { crew: "Hvad ville du gøre for at slippe ud af en dårlig date?", imposter: "Hvad ville du finde på for at forlade en fest tidligt?" },
  { crew: "Hvor mange gange har du sagt ja til noget, du fortrød med det samme?", imposter: "Hvor mange gange har du sagt nej og fortrudt?" },
  { crew: "Hvad er det mest impulsive, du har gjort?", imposter: "Hvad er det mest planlagte, du har gjort?" },
  { crew: "Hvad ville få dig til at forlade en fest øjeblikkeligt?", imposter: "Hvad ville få dig til at blive til det sidste?" },
  { crew: "Hvem i gruppen ville prøve noget ulovligt på ferie?", imposter: "Hvem i gruppen ville læse reglerne først?" },
  { crew: "Hvem i gruppen ville sige noget grænseoverskridende?", imposter: "Hvem i gruppen ville undskylde bagefter?" },
  { crew: "Hvad er den værste undskyldning, du har fået?", imposter: "Hvad er den bedste undskyldning, du har brugt?" },
  { crew: "Hvad har du gjort for at imponere nogen?", imposter: "Hvad har du gjort for at få nogens opmærksomhed?" },
  { crew: "Hvad er det pinligste, du har gjort i skolen?", imposter: "Hvad er det pinligste, du har gjort på en arbejdsplads?" },
  { crew: "Hvor mange gange har du fortrudt en besked om morgenen?", imposter: "Hvor mange gange har du slettet et opslag?" },
  { crew: "Hvad ville du aldrig fortælle dine forældre?", imposter: "Hvad ville du aldrig fortælle en chef?" },
  { crew: "Hvad er den mest vovede ting i dit skab?", imposter: "Hvad er det mest slidte tøj, du stadig bruger?" },
  { crew: "Hvem i gruppen ville tage på date med en fra en app i aften?", imposter: "Hvem i gruppen ville aldrig bruge en app?" },
  { crew: "Hvad var din vildeste ferie?", imposter: "Hvad var din mest kedelige ferie?" },
  { crew: "Hvad er den bedste undskyldning for at gå tidligt hjem?", imposter: "Hvad er den bedste grund til at blive?" },
  { crew: "Hvad ville stå i din pinlige dagbog fra ungdommen?", imposter: "Hvad ville stå på din vildeste ønskeliste?" },
  { crew: "Hvem i gruppen ville sige ja til en tatovering i aften?", imposter: "Hvem i gruppen ville tale de andre fra en dum idé?" },
  { crew: "Hvad er det mest hemmelige køb, du har lavet?", imposter: "Hvad har du gemt væk, så ingen ser det?" },
  { crew: "Hvor mange gange har du løjet for at virke mere interessant?", imposter: "Hvor mange gange har du overdrevet en historie?" },
  { crew: "Hvad er du villig til at gøre for at vinde et væddemål?", imposter: "Hvad ville du aldrig gøre uanset præmien?" },
  { crew: "Hvem i gruppen ville flirte for at få rabat?", imposter: "Hvem i gruppen ville klage for at få rabat?" },
  { crew: "Hvad er det frækkeste sted, du er blevet kysset?", imposter: "Hvad er det mest romantiske sted, du har været?" },
  { crew: "Hvad ville få dig til at slette en app for altid?", imposter: "Hvad ville få dig til at blokere nogen?" },
  { crew: "Hvem i gruppen har den mest pinlige søgehistorik?", imposter: "Hvem i gruppen ville aldrig låne sin telefon ud?" },

  // ——— Endnu mere krydret ———
  { crew: "Hvad er det mest pinlige, du har sagt til en, du var lun på?", imposter: "Hvad er det bedste, nogen har sagt til dig?" },
  { crew: "Hvad ville du gøre, hvis du så din chef i byen sent?", imposter: "Hvad ville du gøre, hvis du mødte en eks til en fest?" },
  { crew: "Hvad er den vildeste undskyldning, du er sluppet afsted med?", imposter: "Hvad er den mest gennemskuelige løgn, du er blevet fanget i?" },
  { crew: "Hvad har du gjort, som din familie ikke ved?", imposter: "Hvad har du gjort, som kun én ven ved?" },
  { crew: "Hvad ville du gøre for at komme ind på et udsolgt sted?", imposter: "Hvad ville du gøre for at slippe uden om en kø?" },
  { crew: "Hvem i gruppen ville ende i en avis for noget dumt?", imposter: "Hvem i gruppen ville ende i en avis for noget flot?" },
  { crew: "Hvad var din mest pinlige forelskelse?", imposter: "Hvad var din længste forelskelse?" },
  { crew: "Hvad ville du bytte en hemmelighed for?", imposter: "Hvad ville du aldrig sælge?" },
  { crew: "Hvor mange gange har du kysset nogen, du lige havde mødt?", imposter: "Hvor mange gange har du fortrudt det?" },
  { crew: "Hvad er det mest spontane, du har sagt ja til?", imposter: "Hvad er det mest gennemtænkte, du har sagt nej til?" },
  { crew: "Hvem i gruppen ville tage tøjet af på et væddemål?", imposter: "Hvem i gruppen ville betale sig fra en straf?" },
  { crew: "Hvad er den mest akavede besked, du har modtaget?", imposter: "Hvad er den mest akavede besked, du har sendt?" },
  { crew: "Hvad ville du gøre, hvis ingen dømte dig?", imposter: "Hvad holder du dig fra på grund af andres blik?" },
  { crew: "Hvem i gruppen ville danse først?", imposter: "Hvem i gruppen skal overtales længst?" },
  { crew: "Hvad er det mest voksne, du har gjort i år?", imposter: "Hvad er det mest barnlige, du har gjort i år?" },
  { crew: "Hvad har du sagt ja til efter midnat, som du fortrød?", imposter: "Hvad har du købt efter midnat?" },
  { crew: "Hvad er det frækkeste, du har skrevet i en besked?", imposter: "Hvad er det sødeste, du har skrevet?" },
  { crew: "Hvem i gruppen ville tage på tur med en fremmed?", imposter: "Hvem i gruppen ville tjekke ID først?" },

  { crew: "Hvad er det mest pinlige, du har gjort for kærlighed?", imposter: "Hvad er det mest romantiske, du har gjort?" },
  { crew: "Hvad ville du gøre, hvis du kunne slette én aften?", imposter: "Hvad ville du gøre, hvis du kunne gentage én aften?" },
  { crew: "Hvad er den værste besked at vågne op til?", imposter: "Hvad er den bedste besked at vågne op til?" },
  { crew: "Hvem i gruppen ville sige ja til en fest på en tirsdag?", imposter: "Hvem i gruppen ville insistere på at gå tidligt?" },
  { crew: "Hvad er det mest hemmelige, du har på din telefon?", imposter: "Hvad er det mest kedelige på din telefon?" },
  { crew: "Hvad ville du gøre for aldrig at få tømmermænd igen?", imposter: "Hvad ville du give for en ekstra times søvn?" },
  { crew: "Hvad er den værste ting at sige på en date?", imposter: "Hvad er den bedste ting at sige på en date?" },
  { crew: "Hvem i gruppen ville flirte med en fremmed på gaden?", imposter: "Hvem i gruppen ville kigge ned i asfalten?" },
  { crew: "Hvad har du gjort, som du ville benægte i retten?", imposter: "Hvad har du gjort, som du er hemmeligt stolt af?" },
  { crew: "Hvad er den mest upassende ting, du har grinet af?", imposter: "Hvad er det mest alvorlige, du har taget useriøst?" },
  { crew: "Hvor mange gange har du kysset på en første date?", imposter: "Hvor mange første dates har du haft i år?" },
  { crew: "Hvad ville du gøre, hvis du fandt din egen dagbog fra 15 år?", imposter: "Hvad ville du gøre, hvis nogen læste dine gamle beskeder?" },
];
