import type { ScalePair } from "./types";

// Family-tier prompt pairs for "Måleren" (the 1–5 scale mode).
//
// Every prompt is answered privately on the same 1–5 scale. The imposter
// receives the related-but-different prompt, then everyone compares their
// revealed numbers to identify the odd answer out.
//
// Authoring rules:
//   1. HARD LIMIT 70 characters — enforced by convex/content-length.test.ts.
//      The reveal card shrinks to fit, but past ~70 it stops being readable at
//      arm's length on a 320px phone.
//   2. Both prompts must make sense on the SAME 1–5 scale (never/altid,
//      slet ikke/fuldstændig), so a 4 is only suspicious because of its content.
//   3. The imposter prompt must be adjacent, not opposite. If a crew 5 implies
//      an imposter 1, the imposter is caught by arithmetic instead of by play.
//   4. VARY THE OPENER. "Hvor god er du til" and "Hvor meget" are capped at
//      25% of the pool each by convex/content-quality.test.ts.

export const SCALE_FAMILY: ScalePair[] = [
  { crew: "Hvor konkurrencemenneske er du?", imposter: "Hvor stædig er du?" },
  { crew: "Hvor god er du til at holde på en hemmelighed?", imposter: "Hvor god er du til at holde masken, når du lyver?" },
  { crew: "Hvor spontan er du?", imposter: "Hvor god er du til at planlægge?" },
  { crew: "Hvor god er du til at komme til tiden?", imposter: "Hvor utålmodig er du, når du venter?" },
  { crew: "Hvor eventyrlysten er du på ferie?", imposter: "Hvor tryghedselskende er du derhjemme?" },
  { crew: "Hvor god er du til at lave mad?", imposter: "Hvor kræsen er du med mad?" },
  { crew: "Hvor god er du til at huske navne?", imposter: "Hvor god er du til at huske ansigter?" },
  { crew: "Hvor meget danser du til en fest?", imposter: "Hvor meget synger du med på musik?" },
  { crew: "Hvor god er du til at spare penge?", imposter: "Hvor nemt køber du noget på impuls?" },
  { crew: "Hvor social er du i en stor gruppe?", imposter: "Hvor meget har du brug for alenetid?" },
  { crew: "Hvor god er du til at samle møbler?", imposter: "Hvor god er du til at læse en brugsanvisning?" },
  { crew: "Hvor modig er du i en rutsjebane?", imposter: "Hvor nervøs bliver du før en flyrejse?" },
  { crew: "Hvor god er du til at svare på beskeder hurtigt?", imposter: "Hvor ofte glemmer du at svare på beskeder?" },
  { crew: "Hvor god er du til at finde vej uden GPS?", imposter: "Hvor let farer du vild i et nyt område?" },
  { crew: "Hvor meget går du op i dit udseende?", imposter: "Hvor længe bruger du på at vælge tøj?" },
  { crew: "Hvor god er du til at holde orden?", imposter: "Hvor meget roder du derhjemme?" },
  { crew: "Hvor god er du til at tage imod kritik?", imposter: "Hvor god er du til at give kritik?" },
  { crew: "Hvor meget ser du reality-tv?", imposter: "Hvor meget følger du med i sladder?" },
  { crew: "Hvor god er du til at vågne om morgenen?", imposter: "Hvor meget bruger du snooze-knappen?" },
  { crew: "Hvor meget stoler du på din mavefornemmelse?", imposter: "Hvor meget overtænker du små ting?" },
  { crew: "Hvor god er du til at forhandle?", imposter: "Hvor meget hader du at prutte om prisen?" },
  { crew: "Hvor meget elsker du overraskelser?", imposter: "Hvor meget bryder du dig om at have kontrol?" },
  { crew: "Hvor god er du til at vinde et skænderi?", imposter: "Hvor ofte giver du dig for at bevare freden?" },
  { crew: "Hvor meget tør du prøve ny mad?", imposter: "Hvor meget holder du dig til det velkendte?" },
  { crew: "Hvor god er du til at holde en plante i live?", imposter: "Hvor god er du til at passe et kæledyr?" },
  { crew: "Hvor meget griner du af dårlige jokes?", imposter: "Hvor ofte fortæller du selv dårlige jokes?" },
  { crew: "Hvor god er du til at gemme en gavehemmelighed?", imposter: "Hvor god er du til at gætte en overraskelse?" },
  { crew: "Hvor meget savner du sommer om vinteren?", imposter: "Hvor meget savner du vinter om sommeren?" },
  { crew: "Hvor meget elsker du at være i centrum?", imposter: "Hvor nervøs bliver du, når alle kigger på dig?" },
  { crew: "Hvor god er du til at holde dig vågen sent?", imposter: "Hvor frisk er du tidligt om morgenen?" },

  // ——— Personlighed og temperament ———
  { crew: "Hvor tålmodig er du i en lang kø?", imposter: "Hvor irriteret bliver du i myldretid?" },
  { crew: "Hvor stædig er du i en diskussion?", imposter: "Hvor svært har du ved at sige undskyld?" },
  { crew: "Hvor optimistisk er du om fremtiden?", imposter: "Hvor meget bekymrer du dig om penge?" },
  { crew: "Hvor nysgerrig er du efter naboens liv?", imposter: "Hvor meget lytter du med i toget?" },
  { crew: "Hvor generøs er du med gaver?", imposter: "Hvor svært har du ved at modtage gaver?" },
  { crew: "Hvor kritisk er du over for dig selv?", imposter: "Hvor hård er du ved andre?" },
  { crew: "Hvor overtroisk er du?", imposter: "Hvor meget tror du på held?" },
  { crew: "Hvor jaloux type er du?", imposter: "Hvor let bliver du misundelig?" },
  { crew: "Hvor dramatisk reagerer du på dårlige nyheder?", imposter: "Hvor rolig er du i en krise?" },
  { crew: "Hvor doven er du en søndag?", imposter: "Hvor produktiv er du en mandag?" },
  { crew: "Hvor genert er du blandt fremmede?", imposter: "Hvor let falder du i snak med en fremmed?" },
  { crew: "Hvor stolt er du af dit arbejde?", imposter: "Hvor tit praler du af det, du laver?" },
  { crew: "Hvor sarkastisk er du til daglig?", imposter: "Hvor tørt er dit humor?" },
  { crew: "Hvor naiv er du over for gode tilbud?", imposter: "Hvor let bliver du overtalt?" },
  { crew: "Hvor perfektionistisk er du?", imposter: "Hvor svært har du ved at aflevere noget?" },
  { crew: "Hvor impulsiv er du med beslutninger?", imposter: "Hvor længe overvejer du et køb?" },
  { crew: "Hvor konfliktsky er du?", imposter: "Hvor tit siger du din mening direkte?" },
  { crew: "Hvor sentimental er du med gamle ting?", imposter: "Hvor svært har du ved at smide ud?" },
  { crew: "Hvor nærig er du med din egen mad?", imposter: "Hvor gerne deler du din dessert?" },
  { crew: "Hvor bange er du for at fejle?", imposter: "Hvor meget presser du dig selv?" },

  // ——— Hverdagsvaner ———
  { crew: "Hvor ofte glemmer du, hvor du lagde din telefon?", imposter: "Hvor tit leder du efter dine nøgler?" },
  { crew: "Hvor tit rydder du op uden at blive bedt om det?", imposter: "Hvor tit vasker du op med det samme?" },
  { crew: "Hvor tit spiser du morgenmad?", imposter: "Hvor tit springer du frokosten over?" },
  { crew: "Hvor ofte tager du trappen frem for elevatoren?", imposter: "Hvor tit går du en tur uden mål?" },
  { crew: "Hvor tit laver du mad fra bunden?", imposter: "Hvor tit bestiller du take-away?" },
  { crew: "Hvor tit skifter du sengetøj?", imposter: "Hvor tit støvsuger du hjemme?" },
  { crew: "Hvor ofte tjekker du din telefon i sengen?", imposter: "Hvor tit ser du serier til langt ud på natten?" },
  { crew: "Hvor tit går du i seng på et fornuftigt tidspunkt?", imposter: "Hvor tit står du op med det samme?" },
  { crew: "Hvor tit synger du med i bilen?", imposter: "Hvor tit nynner du uden at opdage det?" },
  { crew: "Hvor ofte taler du med dig selv?", imposter: "Hvor tit tænker du højt?" },
  { crew: "Hvor tit drikker du vand i løbet af en dag?", imposter: "Hvor tit glemmer du at spise frugt?" },
  { crew: "Hvor tit læser du en bog færdig?", imposter: "Hvor tit starter du på noget nyt før tid?" },
  { crew: "Hvor ofte lader du opvasken stå til dagen efter?", imposter: "Hvor tit lader du vasketøjet ligge i maskinen?" },
  { crew: "Hvor tit kommer du for sent til en aftale?", imposter: "Hvor tit møder du op alt for tidligt?" },
  { crew: "Hvor tit siger du ja til noget, du ikke gider?", imposter: "Hvor tit aflyser du i sidste øjeblik?" },

  // ——— Sociale situationer ———
  { crew: "Hvor godt kan du lide overraskelsesfester?", imposter: "Hvor gerne er du vært for en fest?" },
  { crew: "Hvor let falder du i snak til en fest?", imposter: "Hvor tidligt går du hjem fra en fest?" },
  { crew: "Hvor godt kan du huske folks fødselsdage?", imposter: "Hvor god er du til at sende en hilsen?" },
  { crew: "Hvor meget fylder du i en samtale?", imposter: "Hvor god er du til at lytte færdigt?" },
  { crew: "Hvor svært er det for dig at sige nej?", imposter: "Hvor tit tager du for meget på dig?" },
  { crew: "Hvor gerne holder du tale for en forsamling?", imposter: "Hvor nervøs bliver du foran en gruppe?" },
  { crew: "Hvor godt kan du lide small talk?", imposter: "Hvor hurtigt keder du dig i en samtale?" },
  { crew: "Hvor ofte tager du initiativ til at mødes?", imposter: "Hvor tit venter du på, at andre skriver?" },
  { crew: "Hvor let får du nye venner?", imposter: "Hvor god er du til at holde kontakten?" },
  { crew: "Hvor meget nyder du at være alene hjemme?", imposter: "Hvor hurtigt keder du dig alene?" },
  { crew: "Hvor gerne danser du, når ingen kigger?", imposter: "Hvor gerne synger du karaoke?" },
  { crew: "Hvor godt kan du lide at blive fotograferet?", imposter: "Hvor tit sletter du billeder af dig selv?" },
  { crew: "Hvor meget betyder andres mening for dig?", imposter: "Hvor let bliver du såret af en kommentar?" },
  { crew: "Hvor god er du til at trøste en ven?", imposter: "Hvor god er du til at give et godt råd?" },
  { crew: "Hvor gerne mødes du med nye mennesker?", imposter: "Hvor tryg er du i en stor forsamling?" },

  // ——— Evner og færdigheder ———
  { crew: "Hvor god er du til at bage en kage?", imposter: "Hvor god er du til at følge en opskrift?" },
  { crew: "Hvor god er du til hovedregning?", imposter: "Hvor hurtigt regner du drikkepenge ud?" },
  { crew: "Hvor god er du til at parkere i et snævert hul?", imposter: "Hvor rolig er du bag rattet i myldretid?" },
  { crew: "Hvor god er du til at slå græs lige?", imposter: "Hvor godt holder du orden i haven?" },
  { crew: "Hvor god er du til at pakke en kuffert?", imposter: "Hvor tit pakker du for meget med?" },
  { crew: "Hvor god er du til at binde et gavebånd?", imposter: "Hvor pænt pakker du gaver ind?" },
  { crew: "Hvor god er du til at huske en vittighed?", imposter: "Hvor god er du til at fortælle en historie?" },
  { crew: "Hvor god er du til at stave?", imposter: "Hvor tit slår du et ord op?" },
  { crew: "Hvor god er du til at tegne?", imposter: "Hvor kreativ føler du dig?" },
  { crew: "Hvor god er du til at spille kort?", imposter: "Hvor godt kan du bluffe?" },
  { crew: "Hvor god er du til at svømme?", imposter: "Hvor tryg er du på dybt vand?" },
  { crew: "Hvor god er du til at cykle i trafikken?", imposter: "Hvor tit tager du cyklen frem for bussen?" },
  { crew: "Hvor god er du til at fikse ting selv?", imposter: "Hvor hurtigt ringer du efter en fagmand?" },
  { crew: "Hvor god er du til at forklare en vej?", imposter: "Hvor god er du til at læse et kort?" },
  { crew: "Hvor god er du til at holde en plan?", imposter: "Hvor tit laver du en to-do-liste?" },
  { crew: "Hvor god er du til at gætte en films slutning?", imposter: "Hvor tit spolerer du en pointe for andre?" },
  { crew: "Hvor god er du til at klippe dit eget hår?", imposter: "Hvor tit skifter du frisure?" },
  { crew: "Hvor stærk er din viljestyrke omkring slik?", imposter: "Hvor tit falder du i med noget usundt?" },

  // ——— Mod, frygt og risiko ———
  { crew: "Hvor bange er du for edderkopper?", imposter: "Hvor ubehageligt synes du, insekter er?" },
  { crew: "Hvor bange er du for højder?", imposter: "Hvor svimmel bliver du på en altan?" },
  { crew: "Hvor bange er du for mørke?", imposter: "Hvor utryg er du alene hjemme om natten?" },
  { crew: "Hvor bange er du for tandlægen?", imposter: "Hvor meget udsætter du en lægetid?" },
  { crew: "Hvor modig er du på dybt vand?", imposter: "Hvor gerne hopper du i fra en høj kant?" },
  { crew: "Hvor risikovillig er du med penge?", imposter: "Hvor tit spiller du lotto?" },
  { crew: "Hvor sandsynligt er det, at du prøver bungyjump?", imposter: "Hvor gerne ville du prøve faldskærm?" },
  { crew: "Hvor tryg er du ved at køre i tæt tåge?", imposter: "Hvor nervøs bliver du på glatte veje?" },
  { crew: "Hvor gerne sover du i telt i skoven?", imposter: "Hvor godt sover du et fremmed sted?" },
  { crew: "Hvor bange er du for at tale i telefon?", imposter: "Hvor gerne skriver du frem for at ringe?" },

  // ——— Penge og forbrug ———
  { crew: "Hvor meget bruger du på tøj om måneden?", imposter: "Hvor tit køber du noget, du ikke bruger?" },
  { crew: "Hvor god er du til at holde et budget?", imposter: "Hvor tit tjekker du din bankkonto?" },
  { crew: "Hvor meget ville du give for en god madoplevelse?", imposter: "Hvor vigtigt er det, at maden ser flot ud?" },
  { crew: "Hvor svært er det for dig at spare op?", imposter: "Hvor hurtigt ryger din løn?" },
  { crew: "Hvor gerne låner du penge ud til en ven?", imposter: "Hvor svært er det at bede om penge tilbage?" },
  { crew: "Hvor meget går du op i tilbud?", imposter: "Hvor tit køber du noget, fordi det er billigt?" },
  { crew: "Hvor tit giver du drikkepenge?", imposter: "Hvor meget lægger du oven i regningen?" },
  { crew: "Hvor gerne køber du brugt frem for nyt?", imposter: "Hvor tit går du på loppemarked?" },
  { crew: "Hvor meget fylder pris, når du vælger vin?", imposter: "Hvor godt kan du smage forskel på vin?" },
  { crew: "Hvor svært har du ved at forhandle en pris?", imposter: "Hvor tit beder du om rabat?" },

  // ——— Mad og smag ———
  { crew: "Hvor stærk mad kan du klare?", imposter: "Hvor gerne prøver du en ny ret?" },
  { crew: "Hvor meget elsker du morgenmad?", imposter: "Hvor vigtigt er kaffe for din morgen?" },
  { crew: "Hvor tit spiser du grønt?", imposter: "Hvor godt kan du lide salat?" },
  { crew: "Hvor gerne spiser du de samme ting hver uge?", imposter: "Hvor tit prøver du en ny opskrift?" },
  { crew: "Hvor meget betyder dessert for et måltid?", imposter: "Hvor svært er det at sige nej til slik?" },
  { crew: "Hvor gerne spiser du alene på restaurant?", imposter: "Hvor tit går du ud at spise?" },
  { crew: "Hvor kræsen var du som barn?", imposter: "Hvor meget har din smag ændret sig?" },
  { crew: "Hvor gerne smager du på noget ukendt?", imposter: "Hvor eventyrlysten er du på en menu?" },
  { crew: "Hvor ofte spiser du rester dagen efter?", imposter: "Hvor tit smider du mad ud?" },
  { crew: "Hvor vigtigt er det, at maden er varm nok?", imposter: "Hvor tit sender du en ret retur?" },

  // ——— Hjem og orden ———
  { crew: "Hvor pænt er der på dit skrivebord lige nu?", imposter: "Hvor mange bunker har du liggende?" },
  { crew: "Hvor tit laver du hovedrengøring?", imposter: "Hvor grundig er du, når du gør rent?" },
  { crew: "Hvor meget går du op i indretning?", imposter: "Hvor tit flytter du rundt på møblerne?" },
  { crew: "Hvor rodet er din taske?", imposter: "Hvor let finder du noget i din lomme?" },
  { crew: "Hvor tit laver du din seng om morgenen?", imposter: "Hvor vigtigt er det, at soveværelset er pænt?" },
  { crew: "Hvor mange planter passer du godt?", imposter: "Hvor grøn er du i fingrene?" },
  { crew: "Hvor gerne inviterer du gæster hjem?", imposter: "Hvor meget rydder du op før besøg?" },
  { crew: "Hvor godt kan du lide at have gæster overnattende?", imposter: "Hvor gerne sover du hos andre?" },

  // ——— Hvor sandsynligt er det, at ... ———
  { crew: "Hvor sandsynligt er det, at du synger i badet i dag?", imposter: "Hvor sandsynligt er det, at du danser i køkkenet?" },
  { crew: "Hvor sandsynligt er det, at du glemmer et navn i dag?", imposter: "Hvor tit siger du hej uden at vide hvem det er?" },
  { crew: "Hvor sandsynligt er det, at du falder i søvn foran tv?", imposter: "Hvor tit tager du en lur om eftermiddagen?" },
  { crew: "Hvor sandsynligt er det, at du taber din telefon i dag?", imposter: "Hvor mange ridser er der på din skærm?" },
  { crew: "Hvor sandsynligt er det, at du kommer for sent i morgen?", imposter: "Hvor tit trykker du snooze mere end én gang?" },
  { crew: "Hvor sandsynligt er det, at du spiser slik i aften?", imposter: "Hvor tit spiser du noget efter aftensmaden?" },
  { crew: "Hvor sandsynligt er det, at du græder til en film?", imposter: "Hvor let bliver du rørt af en god sang?" },
  { crew: "Hvor sandsynligt er det, at du siger ja til en tur ud?", imposter: "Hvor gerne bliver du hjemme en fredag?" },
  { crew: "Hvor sandsynligt er det, at du prøver et nyt sprog?", imposter: "Hvor gerne lærer du noget helt nyt?" },
  { crew: "Hvor sandsynligt er det, at du flytter til udlandet?", imposter: "Hvor godt kunne du bo langt fra familien?" },
  { crew: "Hvor sandsynligt er det, at du får et kæledyr mere?", imposter: "Hvor gerne passer du andres dyr?" },
  { crew: "Hvor sandsynligt er det, at du løber et maraton?", imposter: "Hvor gerne træner du udendørs om vinteren?" },
  { crew: "Hvor sandsynligt er det, at du starter noget for dig selv?", imposter: "Hvor gerne er du din egen chef?" },
  { crew: "Hvor sandsynligt er det, at du bliver berømt?", imposter: "Hvor gerne ville du være kendt?" },
  { crew: "Hvor sandsynligt er det, at du taber noget i dag?", imposter: "Hvor kluntet føler du dig til daglig?" },
  { crew: "Hvor sandsynligt er det, at du bliver forkølet i vinter?", imposter: "Hvor tit bliver du syg om året?" },
  { crew: "Hvor sandsynligt er det, at du får en parkeringsbøde?", imposter: "Hvor tit tager du en chance med tiden?" },
  { crew: "Hvor sandsynligt er det, at du bager i denne uge?", imposter: "Hvor tit står du i køkkenet for sjov?" },

  // ——— Hvor enig er du i, at ... ———
  { crew: "Hvor enig er du i, at ananas hører til på pizza?", imposter: "Hvor gerne blander du sødt og salt?" },
  { crew: "Hvor enig er du i, at morgenstund har guld i mund?", imposter: "Hvor meget er du et morgenmenneske?" },
  { crew: "Hvor enig er du i, at man skal sige sin mening?", imposter: "Hvor direkte er du over for folk?" },
  { crew: "Hvor enig er du i, at penge gør lykkelig?", imposter: "Hvor meget fylder økonomi i dit humør?" },
  { crew: "Hvor enig er du i, at alle bør kunne lave mad?", imposter: "Hvor vigtigt er det at kunne klare sig selv?" },
  { crew: "Hvor enig er du i, at ferie er bedst i udlandet?", imposter: "Hvor gerne holder du ferie i Danmark?" },
  { crew: "Hvor enig er du i, at man skal møde til tiden?", imposter: "Hvor irriteret bliver du, når andre er sene?" },
  { crew: "Hvor enig er du i, at katte er bedre end hunde?", imposter: "Hvor meget er du et kattemenneske?" },
  { crew: "Hvor enig er du i, at sociale medier er tidsspilde?", imposter: "Hvor tit fortryder du din skærmtid?" },
  { crew: "Hvor enig er du i, at bogen altid er bedre end filmen?", imposter: "Hvor tit læser du bogen først?" },
  { crew: "Hvor enig er du i, at man skal sove otte timer?", imposter: "Hvor meget går du op i din søvn?" },
  { crew: "Hvor enig er du i, at det er okay at spise alene ude?", imposter: "Hvor tryg er du i eget selskab offentligt?" },
  { crew: "Hvor enig er du i, at vinteren er bedre end sommeren?", imposter: "Hvor godt kan du lide kulde?" },
  { crew: "Hvor enig er du i, at man skal rejse sig for ældre?", imposter: "Hvor opmærksom er du på andre i bussen?" },
  { crew: "Hvor enig er du i, at man aldrig skal gå sulten i seng?", imposter: "Hvor tit spiser du sent om aftenen?" },

  // ——— Hvor pinligt ville det være, hvis ... ———
  { crew: "Hvor pinligt ville det være at falde offentligt?", imposter: "Hvor pinligt er det at snuble foran andre?" },
  { crew: "Hvor pinligt ville det være, hvis nogen læste dine noter?", imposter: "Hvor privat er din telefon for dig?" },
  { crew: "Hvor pinligt ville det være at synge for hele bordet?", imposter: "Hvor nervøs bliver du af at optræde?" },
  { crew: "Hvor pinligt ville det være at glemme en fødselsdag?", imposter: "Hvor dårlig samvittighed får du af en glemt aftale?" },
  { crew: "Hvor pinligt ville det være, hvis din mor så din bolig?", imposter: "Hvor rodet er der hjemme hos dig lige nu?" },
  { crew: "Hvor pinligt ville det være at vinke til en fremmed?", imposter: "Hvor tit forveksler du folk på gaden?" },
  { crew: "Hvor pinligt ville det være at tabe maden på gulvet?", imposter: "Hvor tit spilder du på dit tøj?" },
  { crew: "Hvor pinligt ville det være at komme forkert klædt?", imposter: "Hvor meget tænker du over din påklædning?" },
  { crew: "Hvor pinligt ville det være at kalde læreren for mor?", imposter: "Hvor tit siger du noget helt forkert?" },
  { crew: "Hvor pinligt ville det være at blive taget i en løgn?", imposter: "Hvor svært har du ved at holde en facade?" },
  { crew: "Hvor pinligt ville det være at grine på et alvorligt tidspunkt?", imposter: "Hvor svært har du ved at holde masken?" },
  { crew: "Hvor pinligt ville det være at glemme din tale?", imposter: "Hvor godt husker du under pres?" },

  // ——— Hvor godt kender / husker du ... ———
  { crew: "Hvor godt kender du dine naboer?", imposter: "Hvor tit hilser du på folk i opgangen?" },
  { crew: "Hvor godt kender du din egen by?", imposter: "Hvor tit opdager du et nyt sted lokalt?" },
  { crew: "Hvor godt kender du dine kollegers navne?", imposter: "Hvor tit forveksler du to kolleger?" },
  { crew: "Hvor godt husker du din barndom?", imposter: "Hvor tit tænker du tilbage på skoletiden?" },
  { crew: "Hvor godt husker du en film, du så sidste år?", imposter: "Hvor tit ser du det samme igen?" },
  { crew: "Hvor godt husker du sangtekster udenad?", imposter: "Hvor tit synger du forkert med vilje?" },
  { crew: "Hvor godt kender du din families historie?", imposter: "Hvor meget interesserer slægt dig?" },
  { crew: "Hvor godt kender du dine egne styrker?", imposter: "Hvor let er det at rose dig selv?" },
  { crew: "Hvor godt husker du en aftale uden kalender?", imposter: "Hvor meget stoler du på din hukommelse?" },
  { crew: "Hvor godt kender du reglerne i et brætspil?", imposter: "Hvor tit læser du vejledningen helt?" },

  // ——— Hurtighed, tid og tempo ———
  { crew: "Hvor hurtigt bliver du klar om morgenen?", imposter: "Hvor lang tid bruger du i badet?" },
  { crew: "Hvor hurtigt svarer du på en besked?", imposter: "Hvor tit lader du en besked ligge?" },
  { crew: "Hvor hurtigt spiser du din mad?", imposter: "Hvor tit er du den sidste, der er færdig?" },
  { crew: "Hvor hurtigt pakker du efter en ferie?", imposter: "Hvor længe står kufferten fremme?" },
  { crew: "Hvor hurtigt bliver du utålmodig ved en langsom hjemmeside?", imposter: "Hvor tit lukker du fanen i irritation?" },
  { crew: "Hvor hurtigt tilgiver du en ven?", imposter: "Hvor længe kan du være sur?" },
  { crew: "Hvor hurtigt træffer du en beslutning på en menu?", imposter: "Hvor tit vælger du det samme som sidst?" },
  { crew: "Hvor hurtigt går du i gang med en opgave?", imposter: "Hvor meget udsætter du det kedelige?" },
  { crew: "Hvor hurtigt lærer du en ny app at kende?", imposter: "Hvor tryg er du ved ny teknologi?" },
  { crew: "Hvor hurtigt falder du i søvn om aftenen?", imposter: "Hvor længe ligger du og tænker?" },

  // ——— Teknologi og skærme ———
  { crew: "Hvor afhængig er du af din telefon?", imposter: "Hvor svært ville en dag uden skærm være?" },
  { crew: "Hvor meget fylder sociale medier i din dag?", imposter: "Hvor tit scroller du uden grund?" },
  { crew: "Hvor tryg er du ved at handle på nettet?", imposter: "Hvor tit tjekker du anmeldelser først?" },
  { crew: "Hvor godt styr har du på dine adgangskoder?", imposter: "Hvor tit bruger du den samme kode?" },
  { crew: "Hvor ofte tager du billeder af din mad?", imposter: "Hvor mange billeder tager du om dagen?" },
  { crew: "Hvor irriteret bliver du af dårligt netværk?", imposter: "Hvor meget går du op i hurtigt internet?" },
  { crew: "Hvor gerne hjælper du andre med teknik?", imposter: "Hvor tit spørger familien dig om hjælp?" },
  { crew: "Hvor tit rydder du op i dine billeder?", imposter: "Hvor fyldt er din telefons hukommelse?" },

  // ——— Rejser og ferie ———
  { crew: "Hvor tidligt er du i lufthavnen?", imposter: "Hvor stresset bliver du af at rejse?" },
  { crew: "Hvor gerne planlægger du hver dag på ferien?", imposter: "Hvor godt kan du lide at improvisere?" },
  { crew: "Hvor meget pakker du med på en weekendtur?", imposter: "Hvor tit bruger du alt, du har med?" },
  { crew: "Hvor gerne rejser du alene?", imposter: "Hvor tryg er du i et fremmed land?" },
  { crew: "Hvor gerne prøver du lokal mad på ferie?", imposter: "Hvor tit søger du noget velkendt at spise?" },
  { crew: "Hvor godt kan du lide en lang køretur?", imposter: "Hvor gerne kører du selv på ferie?" },
  { crew: "Hvor meget nyder du at ligge på en strand?", imposter: "Hvor hurtigt keder du dig i solen?" },
  { crew: "Hvor gerne tager du på storbyferie?", imposter: "Hvor mange skridt går du på en ferie?" },
  { crew: "Hvor tit tjekker du arbejdsmail på ferie?", imposter: "Hvor svært er det at koble helt fra?" },

  // ——— Krop, sport og sundhed ———
  { crew: "Hvor ofte træner du om ugen?", imposter: "Hvor dårlig samvittighed får du af at springe over?" },
  { crew: "Hvor konkurrencepræget er du i et spil?", imposter: "Hvor dårlig taber er du?" },
  { crew: "Hvor øm er du dagen efter træning?", imposter: "Hvor hårdt træner du, når du først går i gang?" },
  { crew: "Hvor meget følger du med i sport?", imposter: "Hvor højt råber du foran en kamp?" },
  { crew: "Hvor sund er din kost i en normal uge?", imposter: "Hvor tit spiser du noget usundt om aftenen?" },
  { crew: "Hvor gerne står du tidligt op for at træne?", imposter: "Hvor tit træner du sent om aftenen?" },
  { crew: "Hvor smidig er du?", imposter: "Hvor let rører du dine tæer?" },
  { crew: "Hvor meget mærker du vejret i din krop?", imposter: "Hvor meget påvirker mørket dit humør?" },

  // ——— Følelser og humør ———
  { crew: "Hvor let bliver du rørt?", imposter: "Hvor tit får du en klump i halsen?" },
  { crew: "Hvor let bliver du stresset?", imposter: "Hvor godt håndterer du en deadline?" },
  { crew: "Hvor tit er du i godt humør om morgenen?", imposter: "Hvor meget skal der til at ødelægge din dag?" },
  { crew: "Hvor godt kan du skjule, at du er sur?", imposter: "Hvor tydeligt kan man se dit humør?" },
  { crew: "Hvor meget påvirker musik dit humør?", imposter: "Hvor tit sætter du musik på for at få energi?" },
  { crew: "Hvor tit savner du nogen?", imposter: "Hvor sentimental bliver du om aftenen?" },
  { crew: "Hvor let bliver du begejstret?", imposter: "Hvor højt jubler du over gode nyheder?" },
  { crew: "Hvor meget fylder bekymringer om natten?", imposter: "Hvor tit ligger du vågen og tænker?" },

  // ——— Humor og sjov ———
  { crew: "Hvor let får man dig til at grine?", imposter: "Hvor tit griner du af noget upassende?" },
  { crew: "Hvor gerne laver du sjov med dig selv?", imposter: "Hvor godt tager du imod drilleri?" },
  { crew: "Hvor ofte sender du en sjov video videre?", imposter: "Hvor mange memes ser du om dagen?" },
  { crew: "Hvor gerne laver du practical jokes?", imposter: "Hvor godt kan du holde på en spøg?" },
  { crew: "Hvor tit griner du af dine egne jokes?", imposter: "Hvor tit falder din joke til jorden?" },
  { crew: "Hvor sort er din humor?", imposter: "Hvor grov må en joke gerne være?" },

  // ——— Årstider og natur ———
  { crew: "Hvor godt kan du lide regnvejr?", imposter: "Hvor hyggeligt synes du, efteråret er?" },
  { crew: "Hvor meget nyder du sne?", imposter: "Hvor gerne går du tur i frostvejr?" },
  { crew: "Hvor tit går du en tur i skoven?", imposter: "Hvor meget betyder frisk luft for dig?" },
  { crew: "Hvor gerne sover du for åbent vindue?", imposter: "Hvor varmt vil du have i soveværelset?" },
  { crew: "Hvor meget glæder du dig til foråret?", imposter: "Hvor træt bliver du af vinteren?" },
  { crew: "Hvor gerne bader du i havet?", imposter: "Hvor koldt må vandet gerne være?" },
  { crew: "Hvor ofte kigger du på stjernerne?", imposter: "Hvor meget fascinerer rummet dig?" },

  // ——— Barndom, minder og fremtid ———
  { crew: "Hvor meget savner du at være barn?", imposter: "Hvor tit tænker du på gamle dage?" },
  { crew: "Hvor artig var du som barn?", imposter: "Hvor tit kom du i klemme i skolen?" },
  { crew: "Hvor godt kan du lide at planlægge langt frem?", imposter: "Hvor tryg er du ved ikke at vide, hvad der sker?" },
  { crew: "Hvor meget ligner du dine forældre?", imposter: "Hvor tit hører du dine forældre i din egen stemme?" },
  { crew: "Hvor godt kan du lide gamle billeder?", imposter: "Hvor tit kigger du i gamle album?" },
  { crew: "Hvor meget tror du, du forandrer dig om ti år?", imposter: "Hvor tilfreds er du med, hvor du er nu?" },

  // ——— Arbejde og studie ———
  { crew: "Hvor tit tjekker du mail uden for arbejdstid?", imposter: "Hvor svært er det at lade arbejdet ligge?" },
  { crew: "Hvor gerne arbejder du i en gruppe?", imposter: "Hvor meget foretrækker du at arbejde alene?" },
  { crew: "Hvor tit rækker du hånden op til et møde?", imposter: "Hvor gerne siger du noget foran mange?" },
  { crew: "Hvor godt arbejder du under pres?", imposter: "Hvor tit venter du til sidste øjeblik?" },
  { crew: "Hvor meget betyder en god chef for dig?", imposter: "Hvor vigtigt er et godt kollegaskab?" },
  { crew: "Hvor ofte holder du en rigtig pause?", imposter: "Hvor tit spiser du frokost ved skrivebordet?" },
  { crew: "Hvor ambitiøs er du med din karriere?", imposter: "Hvor vigtigt er en høj løn for dig?" },
  { crew: "Hvor tit tager du noter til et møde?", imposter: "Hvor godt husker du en aftale bagefter?" },
  { crew: "Hvor gerne ville du arbejde hjemmefra hver dag?", imposter: "Hvor meget savner du kollegerne?" },
  { crew: "Hvor tit siger du fra over for for meget arbejde?", imposter: "Hvor let brænder du ud?" },

  // ——— Trafik og transport ———
  { crew: "Hvor ofte overskrider du fartgrænsen?", imposter: "Hvor stresset bliver du af en langsom bilist?" },
  { crew: "Hvor gerne kører du langt uden pause?", imposter: "Hvor tit stopper du på en køretur?" },
  { crew: "Hvor godt kan du lide at køre i mørke?", imposter: "Hvor træt bliver du bag rattet?" },
  { crew: "Hvor tit tager du offentlig transport?", imposter: "Hvor tryg er du i en fyldt bus?" },
  { crew: "Hvor gerne cykler du i regnvejr?", imposter: "Hvor tit tager du regntøj på?" },
  { crew: "Hvor tit løber du efter et tog?", imposter: "Hvor tit misser du en afgang?" },
  { crew: "Hvor bange er du for at flyve?", imposter: "Hvor urolig bliver du af turbulens?" },
  { crew: "Hvor meget musik hører du i bilen?", imposter: "Hvor højt skruer du op?" },

  // ——— Tøj og udseende ———
  { crew: "Hvor lang tid bruger du på at gøre dig klar?", imposter: "Hvor tit skifter du tøj før du går ud?" },
  { crew: "Hvor ofte køber du nyt tøj?", imposter: "Hvor fuld er din garderobe?" },
  { crew: "Hvor gerne går du i farverigt tøj?", imposter: "Hvor meget sort har du i skabet?" },
  { crew: "Hvor vigtigt er det, at dine sko er rene?", imposter: "Hvor tit pudser du dine sko?" },
  { crew: "Hvor tit klæder du dig efter vejret?", imposter: "Hvor tit fryser du, fordi du gættede forkert?" },
  { crew: "Hvor meget går du op i mode?", imposter: "Hvor tit følger du en trend?" },
  { crew: "Hvor gerne prøver du en ny stil?", imposter: "Hvor tryg er du i dit sædvanlige tøj?" },
  { crew: "Hvor tit stryger du dit tøj?", imposter: "Hvor meget generer krøller dig?" },

  // ——— Spil og konkurrence ———
  { crew: "Hvor gerne spiller du brætspil en hel aften?", imposter: "Hvor tit foreslår du et spil?" },
  { crew: "Hvor snyder du i et spil?", imposter: "Hvor tit bøjer du reglerne lidt?" },
  { crew: "Hvor ofte vinder du i kortspil?", imposter: "Hvor heldig føler du dig generelt?" },
  { crew: "Hvor gerne ser du andre spille?", imposter: "Hvor tålmodig er du som tilskuer?" },
  { crew: "Hvor seriøst tager du et vennespil?", imposter: "Hvor sur bliver du over at tabe?" },
  { crew: "Hvor god er du til gætteleg?", imposter: "Hvor hurtigt gætter du et ord?" },
  { crew: "Hvor gerne spiller du computerspil?", imposter: "Hvor mange timer kan du spille i træk?" },

  // ——— Dyr ———
  { crew: "Hvor meget elsker du hunde?", imposter: "Hvor gerne lufter du en andens hund?" },
  { crew: "Hvor gerne ville du have en hest?", imposter: "Hvor tryg er du omkring store dyr?" },
  { crew: "Hvor bange er du for hvepse?", imposter: "Hvor meget generer myg dig om sommeren?" },
  { crew: "Hvor gerne fodrer du fugle om vinteren?", imposter: "Hvor tit lægger du mærke til fugle?" },
  { crew: "Hvor meget snakker du til dyr?", imposter: "Hvor tit giver du dyr et kælenavn?" },
  { crew: "Hvor gerne ville du have et akvarium?", imposter: "Hvor beroligende synes du, fisk er?" },

  // ——— Musik, film og kultur ———
  { crew: "Hvor tit hører du ny musik?", imposter: "Hvor gerne hører du det samme igen og igen?" },
  { crew: "Hvor gerne går du til koncert?", imposter: "Hvor tæt på scenen vil du stå?" },
  { crew: "Hvor tit ser du en film i biografen?", imposter: "Hvor gerne ser du film derhjemme?" },
  { crew: "Hvor gerne ser du en hel serie på en weekend?", imposter: "Hvor svært er det at stoppe efter én episode?" },
  { crew: "Hvor ofte læser du en bog om ugen?", imposter: "Hvor mange bøger har du liggende ulæste?" },
  { crew: "Hvor gerne går du på museum?", imposter: "Hvor længe holder du ud på en udstilling?" },
  { crew: "Hvor tit hører du podcast?", imposter: "Hvor gerne lytter du frem for at læse?" },
  { crew: "Hvor gerne ser du gyserfilm?", imposter: "Hvor let bliver du bange af en film?" },
  { crew: "Hvor meget betyder undertekster for dig?", imposter: "Hvor tit ser du noget på et andet sprog?" },

  // ——— Regler, moral og hensyn ———
  { crew: "Hvor tit går du over for rødt?", imposter: "Hvor meget generer det dig, når andre gør?" },
  { crew: "Hvor ofte sorterer du dit affald korrekt?", imposter: "Hvor meget tænker du på miljøet?" },
  { crew: "Hvor gerne hjælper du en fremmed?", imposter: "Hvor tit stopper du op for at spørge?" },
  { crew: "Hvor tit holder du døren for andre?", imposter: "Hvor opmærksom er du på folk omkring dig?" },
  { crew: "Hvor tit siger du undskyld, når det ikke var din skyld?", imposter: "Hvor konfliktsky er du i en kø?" },
  { crew: "Hvor ærlig er du om en fejl på arbejdet?", imposter: "Hvor svært er det at indrømme noget?" },
  { crew: "Hvor ofte giver du til velgørenhed?", imposter: "Hvor meget fylder andres nød hos dig?" },
  { crew: "Hvor tit afleverer du noget, du har fundet?", imposter: "Hvor ærlig er du, når ingen ser det?" },

  // ——— Kommunikation ———
  { crew: "Hvor tit ringer du frem for at skrive?", imposter: "Hvor gerne taler du i telefon?" },
  { crew: "Hvor mange emojis bruger du i en besked?", imposter: "Hvor formel er du, når du skriver?" },
  { crew: "Hvor ofte læser du en besked uden at svare?", imposter: "Hvor længe går der, før du svarer?" },
  { crew: "Hvor let siger du dine følelser højt?", imposter: "Hvor svært er det at rose nogen ansigt til ansigt?" },
  { crew: "Hvor tit afbryder du andre?", imposter: "Hvor utålmodig bliver du i en lang historie?" },
  { crew: "Hvor gerne skriver du håndskrevne kort?", imposter: "Hvor tit sender du et brev?" },
  { crew: "Hvor godt kan du lide at blive ringet op uanmeldt?", imposter: "Hvor gerne får du uventet besøg?" },

  // ——— Ved bordet og til fest ———
  { crew: "Hvor tit tager du den sidste bid på fadet?", imposter: "Hvor gerne deler du din mad?" },
  { crew: "Hvor ofte hjælper du med at dække bord?", imposter: "Hvor gerne rydder du af efter maden?" },
  { crew: "Hvor længe bliver du siddende efter maden?", imposter: "Hvor gerne bliver du til den sidste gæst går?" },
  { crew: "Hvor gerne holder du en tale til en fest?", imposter: "Hvor tit forbereder du dig grundigt?" },
  { crew: "Hvor tit tager du med til en fest, du ikke gider?", imposter: "Hvor svært er det at aflyse?" },
  { crew: "Hvor meget nyder du en lang middag?", imposter: "Hvor hurtigt vil du hjem fra et selskab?" },

  // ——— Søvn og morgener ———
  { crew: "Hvor godt sover du i et fremmed hus?", imposter: "Hvor meget betyder din egen pude?" },
  { crew: "Hvor tit vågner du før vækkeuret?", imposter: "Hvor fast er din døgnrytme?" },
  { crew: "Hvor mørkt skal der være, når du sover?", imposter: "Hvor følsom er du for lyd om natten?" },
  { crew: "Hvor ofte drømmer du om natten?", imposter: "Hvor godt husker du dine drømme?" },
  { crew: "Hvor gerne tager du en middagslur?", imposter: "Hvor træt er du klokken tre om eftermiddagen?" },

  // ——— Shopping og ting ———
  { crew: "Hvor gerne går du i butikker en lørdag?", imposter: "Hvor hurtigt bliver du træt af at shoppe?" },
  { crew: "Hvor tit køber du noget, du har set en reklame for?", imposter: "Hvor let bliver du fristet i en butik?" },
  { crew: "Hvor tit laver du en indkøbsseddel?", imposter: "Hvor tit glemmer du noget i supermarkedet?" },
  { crew: "Hvor længe beholder du en telefon?", imposter: "Hvor tit vil du have det nyeste?" },
  { crew: "Hvor ofte reparerer du noget i stedet for at købe nyt?", imposter: "Hvor svært er det at smide noget ødelagt ud?" },
  { crew: "Hvor meget fylder emballagen i din vurdering?", imposter: "Hvor vigtigt er et pænt design for dig?" },

  // ——— Samarbejde og ledelse ———
  { crew: "Hvor gerne tager du styringen i en gruppe?", imposter: "Hvor tit ender du med at bestemme?" },
  { crew: "Hvor let uddelegerer du en opgave?", imposter: "Hvor svært er det at stole på andres arbejde?" },
  { crew: "Hvor tit foreslår du planen, når I skal mødes?", imposter: "Hvor gerne følger du bare med?" },
  { crew: "Hvor god er du til at mægle i en uenighed?", imposter: "Hvor tit ender du i midten af en konflikt?" },
  { crew: "Hvor tit roser du andre højt?", imposter: "Hvor let falder det dig at give anerkendelse?" },

  // ——— Held og tilfældigheder ———
  { crew: "Hvor ofte rammer du grønt lys hele vejen?", imposter: "Hvor heldig er du i trafikken?" },
  { crew: "Hvor tit vinder du noget i et lotteri?", imposter: "Hvor tit køber du en skrabelod?" },
  { crew: "Hvor tit finder du penge i en gammel jakke?", imposter: "Hvor tit finder du noget, du havde glemt?" },
  { crew: "Hvor ofte vælger du den langsomste kø?", imposter: "Hvor utålmodig bliver du ved kassen?" },
  { crew: "Hvor meget tror du på skæbnen?", imposter: "Hvor tit føler du, at noget var meningen?" },

  // ——— Blandet: sjældnere formuleringer ———
  { crew: "Hvor svært ville det være at undvære kaffe en uge?", imposter: "Hvor afhængig er du af din morgenrutine?" },
  { crew: "Hvor svært ville det være at bo uden internet en måned?", imposter: "Hvor meget ville du savne dine serier?" },
  { crew: "Hvor svært er det for dig at holde en overraskelse?", imposter: "Hvor hurtigt sladrer du om en plan?" },
  { crew: "Hvor svært er det at stå tidligt op om vinteren?", imposter: "Hvor mørkt er der, når du står op?" },
  { crew: "Hvor svært er det at holde op med at scrolle?", imposter: "Hvor længe bliver du liggende om morgenen?" },
  { crew: "Hvor svært er det at vælge en film til aftenen?", imposter: "Hvor længe leder I efter noget at se?" },
  { crew: "Hvor svært er det at sige nej til en ekstra tallerken?", imposter: "Hvor mæt bliver du typisk?" },
  { crew: "Hvor vigtigt er det for dig at vinde?", imposter: "Hvor længe husker du et nederlag?" },
  { crew: "Hvor vigtigt er en fast plads i sofaen?", imposter: "Hvor meget generer det dig, hvis nogen sidder der?" },
  { crew: "Hvor vigtigt er det, at din mad ikke rører hinanden?", imposter: "Hvor pernitten er du ved bordet?" },
  { crew: "Hvor vigtigt er stilhed, når du skal koncentrere dig?", imposter: "Hvor let bliver du forstyrret?" },
  { crew: "Hvor vigtigt er det at have en plan for weekenden?", imposter: "Hvor rastløs bliver du uden noget at lave?" },
  { crew: "Hvor let bliver du køresyg?", imposter: "Hvor godt kan du læse i en bil?" },
  { crew: "Hvor let bliver du forpustet på en trappe?", imposter: "Hvor meget kondition har du?" },
  { crew: "Hvor let siger du din mening til en fremmed?", imposter: "Hvor tit blander du dig i noget?" },
  { crew: "Hvor let husker du en pinkode?", imposter: "Hvor tit skal du nulstille en adgangskode?" },
  { crew: "Hvor længe holder dine nytårsforsætter?", imposter: "Hvor seriøst mener du dem i januar?" },
  { crew: "Hvor længe kan du sidde stille uden telefon?", imposter: "Hvor rastløs er du i et venteværelse?" },
  { crew: "Hvor længe kan du holde en samtale i gang?", imposter: "Hvor akavet synes du, stilhed er?" },
  { crew: "Hvor længe bruger du på en indkøbstur?", imposter: "Hvor målrettet handler du ind?" },
  { crew: "Hvor tidligt møder du op til en aftale?", imposter: "Hvor stresset bliver du af at være sen?" },
  { crew: "Hvor tidligt begynder du at planlægge en ferie?", imposter: "Hvor meget glæde får du af selve planlægningen?" },
  { crew: "Hvor højt hører du musik derhjemme?", imposter: "Hvor meget fylder musik i din hverdag?" },
  { crew: "Hvor højt taler du i et fyldt lokale?", imposter: "Hvor tit bliver du bedt om at dæmpe dig?" },
  { crew: "Hvor tæt på fremmede kan du holde ud at stå?", imposter: "Hvor ubehageligt er en fyldt bus?" },
  { crew: "Hvor tæt på er du på at gøre noget helt nyt?", imposter: "Hvor klar er du til en stor forandring?" },
  { crew: "Hvor mange gange gentager du en historie?", imposter: "Hvor tit siger folk, at de har hørt den før?" },
  { crew: "Hvor mange planer aflyser du på en måned?", imposter: "Hvor socialt overbooket er du?" },
  { crew: "Hvor mange gange tjekker du, at døren er låst?", imposter: "Hvor tit vender du om for at tjekke noget?" },
  { crew: "Hvor mange uåbnede beskeder har du lige nu?", imposter: "Hvor stresset bliver du af en fyldt indbakke?" },
  { crew: "Hvor rodet er din bil indeni?", imposter: "Hvor tit gør du din bil ren?" },
  { crew: "Hvor gammeldags er du med teknologi?", imposter: "Hvor længe holder du fast i det, du kender?" },
  { crew: "Hvor grundig er du, når du læser en kontrakt?", imposter: "Hvor tit trykker du bare accepter?" },
  { crew: "Hvor omhyggelig er du med at pakke gaver ind?", imposter: "Hvor sent er du på den med gaverne?" },
  { crew: "Hvor sikker er du på din egen retningssans?", imposter: "Hvor tit tager du en omvej ved et uheld?" },
  { crew: "Hvor godt tåler du varme?", imposter: "Hvor meget generer sommervarme din søvn?" },
  { crew: "Hvor stille kan du sidde til en lang film?", imposter: "Hvor tit tjekker du telefonen undervejs?" },
  { crew: "Hvor kritisk er du over for en restaurant?", imposter: "Hvor tit skriver du en anmeldelse?" },
  { crew: "Hvor loyal er du over for et mærke?", imposter: "Hvor tit køber du det samme igen?" },
  { crew: "Hvor nem er du at overraske?", imposter: "Hvor tit gætter du en plan på forhånd?" },
  { crew: "Hvor sjældent skifter du mening?", imposter: "Hvor let lader du dig overbevise af fakta?" },
  { crew: "Hvor beskyttende er du over for dine ting?", imposter: "Hvor gerne låner du noget dyrt ud?" },
  { crew: "Hvor stort et rod kan du leve i?", imposter: "Hvor længe går der, før du må rydde op?" },
  { crew: "Hvor meget betyder en god madras for din nat?", imposter: "Hvor tit vågner du med ondt i ryggen?" },
  { crew: "Hvor tilfreds er du med din hverdag lige nu?", imposter: "Hvor meget ville du ændre, hvis du kunne?" },
];
