import type { ScalePair } from "./types";

// "Krydret indhold" — the adult-leaning Måleren pool. Opt-in via the host's
// settings toggle; never drawn unless someone explicitly turned it on.
//
// Register: what a group of adult friends actually asks each other after the
// second drink. Suggestive and blunt, but not crude — a prompt that would make
// someone genuinely uncomfortable to answer in front of friends is a bad party
// prompt, not a spicy one. Nothing here targets a real person, and nothing
// assumes anyone's relationship status, orientation, or gender.
//
// Same hard rules as the family pool: 70-character cap, both prompts must work
// on the identical 1–5 scale, and the imposter prompt sits ADJACENT to the crew
// one rather than opposite.

export const SCALE_PARTY: ScalePair[] = [
  // ——— Fest og druk ———
  { crew: "Hvor tit drikker du mere, end du havde planlagt?", imposter: "Hvor tit fortryder du den sidste genstand?" },
  { crew: "Hvor slemme er dine tømmermænd typisk?", imposter: "Hvor længe er du om at komme dig efter en bytur?" },
  { crew: "Hvor ofte er du den sidste, der går hjem?", imposter: "Hvor tit lukker du baren?" },
  { crew: "Hvor højlydt bliver du efter et par genstande?", imposter: "Hvor meget mere selvsikker bliver du?" },
  { crew: "Hvor tit ender du med at synge karaoke?", imposter: "Hvor gerne tager du mikrofonen?" },
  { crew: "Hvor ofte danser du på et bord?", imposter: "Hvor vild bliver du på dansegulvet?" },
  { crew: "Hvor godt husker du gårsdagens bytur?", imposter: "Hvor tit skal du have genfortalt din bytur?" },
  { crew: "Hvor tit tager du en shot, du ikke ville have?", imposter: "Hvor let bliver du overtalt til én mere?" },
  { crew: "Hvor mange gange har du drukket i en taxa hjem?", imposter: "Hvor tit ender du med natmad klokken tre?" },
  { crew: "Hvor tit sender du beskeder, du fortryder næste dag?", imposter: "Hvor tit ringer du til nogen alt for sent?" },
  { crew: "Hvor ofte falder du i søvn til en fest?", imposter: "Hvor tidligt løber du tør for energi?" },
  { crew: "Hvor godt kan du drikke uden at det ses?", imposter: "Hvor rød bliver du i hovedet af alkohol?" },
  { crew: "Hvor tit springer du en runde over?", imposter: "Hvor godt kan du sige nej til mere?" },
  { crew: "Hvor mange gange har du mistet din jakke i byen?", imposter: "Hvor mange ting glemmer du på en bytur?" },
  { crew: "Hvor tit tager du hjem med den forkerte jakke?", imposter: "Hvor rodet er din garderobe efter en fest?" },
  { crew: "Hvor gerne spiller du drukspil?", imposter: "Hvor konkurrencepræget bliver du til et spil?" },
  { crew: "Hvor ofte drikker du en hverdagsøl?", imposter: "Hvor tit åbner du en flaske vin alene?" },
  { crew: "Hvor tit lover du aldrig at drikke igen?", imposter: "Hvor længe holder et løfte om at drikke mindre?" },
  { crew: "Hvor grim er din dansestil?", imposter: "Hvor lidt går du op i, hvordan du ser ud?" },
  { crew: "Hvor ofte starter du festen før alle andre?", imposter: "Hvor tidligt begynder du at drikke?" },
  { crew: "Hvor tit tager du en fridag efter en fest?", imposter: "Hvor uarbejdsdygtig er du dagen derpå?" },
  { crew: "Hvor godt kender du din egen grænse?", imposter: "Hvor tit overskrider du din egen grænse?" },
  { crew: "Hvor ofte gør du noget, du ellers aldrig ville gøre?", imposter: "Hvor meget ændrer alkohol din personlighed?" },
  { crew: "Hvor tit bliver du filosofisk sent på natten?", imposter: "Hvor dybe bliver dine samtaler efter midnat?" },
  { crew: "Hvor følsom bliver du, når du har drukket?", imposter: "Hvor tit krammer du alle til en fest?" },

  // ——— Dating og flirt ———
  { crew: "Hvor god er du til at flirte?", imposter: "Hvor let opdager du, at nogen flirter med dig?" },
  { crew: "Hvor ofte tager du første skridt?", imposter: "Hvor gerne bliver du inviteret ud?" },
  { crew: "Hvor kræsen er du på en datingapp?", imposter: "Hvor hurtigt swiper du videre?" },
  { crew: "Hvor tit har du pyntet på en datingprofil?", imposter: "Hvor gammelt er dit bedste billede?" },
  { crew: "Hvor ofte ghoster du nogen?", imposter: "Hvor svært er det at sige, du ikke er interesseret?" },
  { crew: "Hvor tit er du blevet ghostet?", imposter: "Hvor meget fylder et manglende svar hos dig?" },
  { crew: "Hvor hurtigt forelsker du dig?", imposter: "Hvor let mister du interessen igen?" },
  { crew: "Hvor ofte tjekker du en eks på sociale medier?", imposter: "Hvor godt er du kommet over din seneste eks?" },
  { crew: "Hvor pinlig var din første date?", imposter: "Hvor nervøs er du på en første date?" },
  { crew: "Hvor tit betaler du hele regningen på en date?", imposter: "Hvor akavet er det at dele regningen?" },
  { crew: "Hvor ofte falder du for den forkerte type?", imposter: "Hvor godt kender du dit eget mønster?" },
  { crew: "Hvor gerne kysser du på en første date?", imposter: "Hvor hurtigt inviterer du nogen med hjem?" },
  { crew: "Hvor tit har du datet to på samme tid?", imposter: "Hvor svært er det at holde styr på flere dates?" },
  { crew: "Hvor mange gange har du sagt for meget for tidligt?", imposter: "Hvor hurtigt bliver du følelsesmæssigt involveret?" },
  { crew: "Hvor romantisk er du i det daglige?", imposter: "Hvor tit gør du noget uventet for en anden?" },
  { crew: "Hvor jaloux bliver du i et forhold?", imposter: "Hvor let bliver du usikker?" },
  { crew: "Hvor tit kigger du på en partners telefon?", imposter: "Hvor stor er din tillid i et forhold?" },
  { crew: "Hvor gerne præsenterer du en date for vennerne?", imposter: "Hvor hurtigt gør du det officielt?" },
  { crew: "Hvor ofte er et venskab blevet til noget mere?", imposter: "Hvor tit har du kysset en ven?" },
  { crew: "Hvor gerne dater du en kollega?", imposter: "Hvor svært ville det være at holde hemmeligt?" },
  { crew: "Hvor tit tænker du på en gammel flamme?", imposter: "Hvor meget fylder fortiden i dit hoved?" },
  { crew: "Hvor ofte giver du fremmede komplimenter?", imposter: "Hvor let falder det dig at rose nogen?" },
  { crew: "Hvor svært er det for dig at skuffe nogen?", imposter: "Hvor tit siger du ja for at være sød?" },
  { crew: "Hvor stor betydning har udseende for dig?", imposter: "Hvor meget vægter du en god humor?" },
  { crew: "Hvor tit har du slået op over en besked?", imposter: "Hvor konfliktsky er du i et brud?" },

  // ——— Pinlige indrømmelser ———
  { crew: "Hvor ofte lyver du om, hvorfor du kom for sent?", imposter: "Hvor kreativ er du med en undskyldning?" },
  { crew: "Hvor tit melder du dig syg uden at være det?", imposter: "Hvor let lyver du for en chef?" },
  { crew: "Hvor mange gange har du læst en andens beskeder?", imposter: "Hvor nysgerrig er du efter andres liv?" },
  { crew: "Hvor tit tager du noget med fra et hotelværelse?", imposter: "Hvor mange småting samler du op undervejs?" },
  { crew: "Hvor ofte siger du, at du elsker en gave, du hader?", imposter: "Hvor god er du til at lade som ingenting?" },
  { crew: "Hvor tit lader du som om du kender en person?", imposter: "Hvor svært er det at indrømme, du har glemt et navn?" },
  { crew: "Hvor ofte sladrer du om en ven?", imposter: "Hvor svært er det at holde på en hemmelighed?" },
  { crew: "Hvor grundigt tjekker du en ny bekendt på nettet?", imposter: "Hvor langt tilbage scroller du?" },
  { crew: "Hvor tit synger du for fuld hals alene?", imposter: "Hvor teatralsk er du, når ingen ser det?" },
  { crew: "Hvor ofte græder du over noget fjollet?", imposter: "Hvor sart er du, når du er træt?" },
  { crew: "Hvor tit springer du håndvasken over?", imposter: "Hvor nøjeregnende er du med hygiejne?" },
  { crew: "Hvor ofte bærer du det samme tøj to dage i træk?", imposter: "Hvor tit snuser du til tøjet først?" },
  { crew: "Hvor tit springer du et bad over?", imposter: "Hvor tit klarer deodorant hele jobbet?" },
  { crew: "Hvor ofte spiser du noget, der har været på gulvet?", imposter: "Hvor meget går du op i udløbsdatoer?" },
  { crew: "Hvor tit siger du ja til en plan, du aldrig følger?", imposter: "Hvor tit melder du afbud samme dag?" },
  { crew: "Hvor ofte lader du som om du forstod noget?", imposter: "Hvor svært er det at bede om en forklaring?" },
  { crew: "Hvor tit har du taget æren for andres arbejde?", imposter: "Hvor let er det at tie stille om en fejl?" },
  { crew: "Hvor ofte snød du i skolen?", imposter: "Hvor tit skrev du af fra en anden?" },
  { crew: "Hvor grimt et sprog har du til daglig?", imposter: "Hvor tit bander du foran de forkerte?" },
  { crew: "Hvor tit griner du af en, der falder?", imposter: "Hvor svært er det at lade være med at grine?" },
  { crew: "Hvor ofte undgår du nogen på gaden?", imposter: "Hvor tit har du gemt dig i en butik?" },
  { crew: "Hvor tit sender du en besked til den forkerte?", imposter: "Hvor hurtigt fortryder du en sendt besked?" },
  { crew: "Hvor ofte siger du noget grimt bag om ryggen?", imposter: "Hvor tit fortryder du noget, du har sagt?" },
  { crew: "Hvor tit glemmer du et vigtigt jubilæum?", imposter: "Hvor længe piner en fejl dig bagefter?" },
  { crew: "Hvor frækt går du efter en god plads i toget?", imposter: "Hvor tit sætter du dig på en reserveret plads?" },

  // ——— Krop og nærhed ———
  { crew: "Hvor tryg er du med bar overkrop foran andre?", imposter: "Hvor gerne går du i badetøj blandt fremmede?" },
  { crew: "Hvor ofte går du nøgen hjemme?", imposter: "Hvor tryg er du med gardinerne åbne?" },
  { crew: "Hvor gerne tager du i sauna med vennerne?", imposter: "Hvor akavet synes du, et omklædningsrum er?" },
  { crew: "Hvor tit taler du om sex med dine venner?", imposter: "Hvor åben er du om dit privatliv?" },
  { crew: "Hvor genert er du hos lægen?", imposter: "Hvor let taler du om din krop?" },
  { crew: "Hvor meget går du op i dit spejlbillede?", imposter: "Hvor tit tjekker du dig selv i en rude?" },
  { crew: "Hvor ofte flirter du bare for sjov?", imposter: "Hvor meget nyder du opmærksomhed?" },
  { crew: "Hvor eventyrlysten er du i soveværelset?", imposter: "Hvor gerne prøver du noget nyt med en partner?" },
  { crew: "Hvor vigtigt er nærhed for dig?", imposter: "Hvor meget fylder fysisk kontakt i din hverdag?" },
  { crew: "Hvor gerne krammer du folk, du lige har mødt?", imposter: "Hvor tæt på må fremmede komme?" },
  { crew: "Hvor tit sover du med tøj på?", imposter: "Hvor meget betyder komfort om natten?" },
  { crew: "Hvor mange billeder tager du, før du er tilfreds?", imposter: "Hvor tit sletter du et billede af dig selv?" },
  { crew: "Hvor meget bruger du på hudpleje?", imposter: "Hvor lang er din rutine om aftenen?" },
  { crew: "Hvor ofte går du til frisør?", imposter: "Hvor meget betyder dit hår for dit humør?" },
  { crew: "Hvor gerne ville du have en tatovering mere?", imposter: "Hvor impulsiv ville du være med den beslutning?" },

  // ——— Penge, løgn og moral ———
  { crew: "Hvor tit har du kørt uden billet?", imposter: "Hvor stor en chance tager du med kontrollen?" },
  { crew: "Hvor ofte beholder du for mange penge tilbage?", imposter: "Hvor hurtigt siger du det til ekspedienten?" },
  { crew: "Hvor mange streamingkonti låner du af andre?", imposter: "Hvor tit deler du dine egne koder?" },
  { crew: "Hvor tit klager du for at få rabat?", imposter: "Hvor frækt beder du om noget gratis?" },
  { crew: "Hvor grundig er du med dine papirer til skat?", imposter: "Hvor sent afleverer du dine papirer?" },
  { crew: "Hvor ofte låner du penge af venner?", imposter: "Hvor hurtigt betaler du tilbage?" },
  { crew: "Hvor tit glemmer du at betale din del?", imposter: "Hvor meget går du op i at dele lige?" },
  { crew: "Hvor ofte tager du en flaske med fra en fest?", imposter: "Hvor tit tager du rester med hjem?" },
  { crew: "Hvor gerne fremhæver du, hvad en gave kostede?", imposter: "Hvor meget betyder det, at gaven imponerer?" },
  { crew: "Hvor meget skulle der til at få dig til at flytte langt væk?", imposter: "Hvor let river du op i dit liv?" },
  { crew: "Hvor meget ville du give for at slippe for en pligt?", imposter: "Hvor doven er du med husarbejde?" },
  { crew: "Hvor tit lyver du om din alder?", imposter: "Hvor meget generer det dig at blive ældre?" },

  // ——— Venner og gruppedynamik ———
  { crew: "Hvor ofte er du den, der starter ballade?", imposter: "Hvor tit ender du midt i et skænderi?" },
  { crew: "Hvor tit er du gruppens fornuftige stemme?", imposter: "Hvor tit passer du på de andre?" },
  { crew: "Hvor ofte dømmer du dine venners valg?", imposter: "Hvor tit kritiserer du en ven ansigt til ansigt?" },
  { crew: "Hvor tit er du den, der bliver drillet?", imposter: "Hvor godt tager du imod grov humor?" },
  { crew: "Hvor ofte inviterer du dig selv med?", imposter: "Hvor bange er du for at gå glip af noget?" },
  { crew: "Hvor hurtigt spreder en nyhed sig gennem dig?", imposter: "Hvor tit sladrer du videre med det samme?" },
  { crew: "Hvor tit er du den, der tager regningen?", imposter: "Hvor gerne giver du en omgang?" },
  { crew: "Hvor svært er det at behandle alle venner ens?", imposter: "Hvor tit har du en klar favorit?" },
  { crew: "Hvor ofte tager du parti i en vennekonflikt?", imposter: "Hvor gerne holder du dig neutral?" },
  { crew: "Hvor tit går du fra en fest uden at sige farvel?", imposter: "Hvor akavet synes du, afskeder er?" },
  { crew: "Hvor ofte lader du din telefon ligge fremme?", imposter: "Hvor meget har du at skjule?" },
  { crew: "Hvor tit siger du ja til en skør idé?", imposter: "Hvor let lader du dig rive med?" },
  { crew: "Hvor ofte er du den mest voksne i rummet?", imposter: "Hvor gerne slipper du kontrollen?" },
  { crew: "Hvor meget dokumenterer du en aften med billeder?", imposter: "Hvor tit tager du et billede, andre ikke vil have?" },
  { crew: "Hvor tit deler du et billede uden at spørge?", imposter: "Hvor meget tænker du over andres privatliv?" },

  // ——— Grænser og hemmeligheder ———
  { crew: "Hvor mange hemmeligheder holder du lige nu?", imposter: "Hvor tungt vejer de på dig?" },
  { crew: "Hvor ofte siger du en hvid løgn på en dag?", imposter: "Hvor let glider en lille løgn ud af dig?" },
  { crew: "Hvor godt ville du klare en løgnedetektor?", imposter: "Hvor rolig er du, når du bliver udspurgt?" },
  { crew: "Hvor meget fortæller du på et førstemøde?", imposter: "Hvor hurtigt åbner du op for en fremmed?" },
  { crew: "Hvor tit skjuler du, hvordan du virkelig har det?", imposter: "Hvor god er du til at spille glad?" },
  { crew: "Hvor ofte fortryder du at have delt for meget?", imposter: "Hvor hurtigt bliver du fortrolig?" },
  { crew: "Hvor mange kender din adgangskode?", imposter: "Hvor meget deler du med din nærmeste?" },
  { crew: "Hvor tit har du en plan B, du ikke fortæller om?", imposter: "Hvor tæt holder du kortene ind til kroppen?" },
  { crew: "Hvor ofte tænker du noget, du aldrig ville sige højt?", imposter: "Hvor godt filter har du?" },
  { crew: "Hvor tit siger du for meget, når du er træt?", imposter: "Hvor tit fortryder du en tilståelse?" },
  { crew: "Hvor let ville nogen kunne læse dig?", imposter: "Hvor gennemsigtigt er dit ansigtsudtryk?" },
  { crew: "Hvor privat er du på nettet?", imposter: "Hvor meget kan man finde om dig med en søgning?" },

  // ——— Bytur og nattelivet ———
  { crew: "Hvor ofte tager du i byen på en hverdag?", imposter: "Hvor spontan er du med en aften ude?" },
  { crew: "Hvor tit står du i kø for at komme ind et sted?", imposter: "Hvor længe gider du vente?" },
  { crew: "Hvor ofte er du blevet afvist i døren?", imposter: "Hvor godt kender du dørmændene?" },
  { crew: "Hvor tit spiser du fastfood på vej hjem?", imposter: "Hvor uundgåelig er en burger klokken fire?" },
  { crew: "Hvor ofte mister du dine venner i byen?", imposter: "Hvor god er du til at samle gruppen?" },
  { crew: "Hvor tryg føler du dig på vej hjem om natten?", imposter: "Hvor tit går du hjem alene?" },
  { crew: "Hvor tit ender du et andet sted end planlagt?", imposter: "Hvor godt holder din plan for aftenen?" },
  { crew: "Hvor dyr bliver en typisk bytur for dig?", imposter: "Hvor tit får du et chok over kontoen dagen efter?" },
  { crew: "Hvor ofte tager du en efterfest med hjem?", imposter: "Hvor tit bliver din bolig til festens slutning?" },
  { crew: "Hvor tit sover du hos en ven efter en bytur?", imposter: "Hvor tit vågner du et sted, du ikke kender?" },

  // ——— Blandet krydret ———
  { crew: "Hvor tit ender en hyggeaften i en bytur?", imposter: "Hvor let bliver en enkelt øl til fem?" },
  { crew: "Hvor gerne tager du på en spontan weekendtur?", imposter: "Hvor hurtigt kan du pakke en taske?" },
  { crew: "Hvor mange gange har du sms'et en eks om natten?", imposter: "Hvor stærk er din selvbeherskelse klokken to?" },
  { crew: "Hvor gerne fortæller du om din vildeste ferie?", imposter: "Hvor meget pynter du på historien?" },
  { crew: "Hvor tit bliver du forelsket på en ferie?", imposter: "Hvor hurtigt glemmer du et feriebekendtskab?" },
  { crew: "Hvor gerne deler du en pinlig historie om dig selv?", imposter: "Hvor meget nyder du at få folk til at grine?" },
  { crew: "Hvor mange gange har du sneget dig ud som teenager?", imposter: "Hvor gode var dine forældre til at opdage det?" },
  { crew: "Hvor vild var du i din ungdom?", imposter: "Hvor meget har du lagt på hylden siden?" },
  { crew: "Hvor tit tager du en beslutning, du fortryder om morgenen?", imposter: "Hvor impulsiv bliver du sent om aftenen?" },
  { crew: "Hvor gerne bliver du oppe til solen står op?", imposter: "Hvor tit ser du en nat gå på hæld?" },
  { crew: "Hvor tit har du kysset nogen på et dansegulv?", imposter: "Hvor modig bliver du på et dansegulv?" },
  { crew: "Hvor gerne fortæller du om dit kærlighedsliv?", imposter: "Hvor privat er du med dine forhold?" },
  { crew: "Hvor mange gange har du forelsket dig i en ven?", imposter: "Hvor tit har det ødelagt venskabet?" },
  { crew: "Hvor tit tjekker du, om nogen har set din besked?", imposter: "Hvor meget betyder et hurtigt svar for dig?" },
  { crew: "Hvor tit skriver du først dagen efter en date?", imposter: "Hvor længe venter du med vilje?" },
  { crew: "Hvor gerne tager du på blind date?", imposter: "Hvor meget stoler du på venners smag?" },
  { crew: "Hvor mange gange har du løjet om dit job til en fest?", imposter: "Hvor gerne pynter du på din titel?" },
  { crew: "Hvor tit siger du noget frækt for at chokere?", imposter: "Hvor gerne provokerer du lidt?" },
  { crew: "Hvor godt kan du holde på en andens hemmelighed?", imposter: "Hvor tit har du røbet noget ved et uheld?" },
  { crew: "Hvor tit har du danset til musik, du hader?", imposter: "Hvor let river stemningen dig med?" },
  { crew: "Hvor gerne tager du tøj af til en badetur om natten?", imposter: "Hvor spontan er du ved vandet?" },
  { crew: "Hvor tit har du sovet i dit tøj efter en fest?", imposter: "Hvor grundig er du, når du er træt?" },
  { crew: "Hvor mange gange har du tabt din telefon på en flisegang?", imposter: "Hvor godt passer du på dine ting?" },
  { crew: "Hvor tit ender du i en dyb snak med en fremmed?", imposter: "Hvor let åbner du op for nogen, du lige har mødt?" },
  { crew: "Hvor gerne synger du med på en fællessang i baren?", imposter: "Hvor højt synger du med?" },
  { crew: "Hvor tit har du taget en taxa, du ikke havde råd til?", imposter: "Hvor dyr bliver din vej hjem?" },
  { crew: "Hvor gerne prøver du en ny drink frem for din faste?", imposter: "Hvor loyal er du over for din yndlingsdrink?" },
  { crew: "Hvor tit bliver du gruppens fotograf på en aften?", imposter: "Hvor mange billeder ender i albummet dagen efter?" },
  { crew: "Hvor tit har du tændt en cigaret, du ikke ville have?", imposter: "Hvor let falder du i gamle vaner?" },
  { crew: "Hvor gerne tager du en dyst mod en ven?", imposter: "Hvor meget skal der til, før du siger ja til et væddemål?" },
  { crew: "Hvor tit har du tabt et væddemål?", imposter: "Hvor dårligt vurderer du dine egne chancer?" },
  { crew: "Hvor gerne tager du i sommerhus med vennerne?", imposter: "Hvor vild bliver en hyttetur med vennerne?" },
  { crew: "Hvor tit har du løjet for at slippe ud af en plan?", imposter: "Hvor kreativ bliver du under pres?" },
  { crew: "Hvor mange gange har du fortrudt en frisure?", imposter: "Hvor impulsiv er du hos frisøren?" },
  { crew: "Hvor gerne prøver du noget, der skræmmer dig lidt?", imposter: "Hvor meget kick får du af at være nervøs?" },
];
